### ISSUE TITLE
Possível redução do Spawnrate dos Meteoros do Applied

### ISSUE THREAD

**Issue by fadoartpokebr** [ArtpokeBr/Minecraft-Ultimato#1]
Art o ultimato está um modpack ótimo 

o verdadeiro motivo para eu te enviar isso é porque os meteoros do applied (n sei como escreve) estão num range de Spawn muito alto logo no começo do jogo achei 3 meteoros 2 deles tinham estragado algumas dungeas uma delas foi a do inventory pets
e outra só achei vestígios dela

**Comment by fadoartpokebr** [comment]
obs: só sei q a dungea estragada foi a do inventory pets porque vi os items relacionados a ele dropados envolta do centro do meteoro

**Comment by ArtpokeBr** [comment]
não coloque no título "para não sei quem" só escreva o Erro mesmo kkk, que no caso é o SpawnRate dos Meteoros do Applied.

**Comment by ArtpokeBr** [comment]
já está muito baixa, só reza pra n destruir nada importante...
