### ISSUE TITLE
Não consigo instalar pelo App do CurseForge

### ISSUE THREAD

**Issue by LegalPlayer** [ArtpokeBr/Minecraft-Ultimato#100]
ArtpokeBr eu quando instalei o modpack deu erro no app do curseforge e queria alguma sugestão de algo que possa fazer 
e não é por causa do meu computador pois ele é até que bom e foi comprado recentemente, achei que era algum erro do modpack pois tem mods que necessitam de outros para rodar mas como vi as pessoas no seu comentário
 dizendo que tinha funcionado ignorei. Bom se leu isso obrgiado pela atenção e espero que responda.
![Captura de tela 2020-12-04 170246](https://user-images.githubusercontent.com/75500633/101209554-aea1f580-3652-11eb-86d2-bfbd9d805c65.png)

**Comment by ArtpokeBr** [comment]
Isso é problema da Curse, o App está em beta agora depois da migração, então tenha paciência :T vou fechar.
