### ISSUE TITLE
Problema em craftar um item do "Industrial Craft 2"

### ISSUE THREAD

**Issue by atlas2468** [ArtpokeBr/Minecraft-Ultimato#101]
Não consigo craftar o "Insulated Copper Cable", para craftar o item é preciso de um "Copper Cable" e uma "Rubber", ou uma "Rubber Bar" ou um "Plastic" mas tentei com a "Rubber", "Rubber Bar" e o "Plastic" e nada, coloco na crafting table e simplesmente nao aparece nada, mesmo a receita do item sendo colocada corretamente na crafting table.

**Comment by ArtpokeBr** [comment]
no JEI aparece tudo corretamente? você está jogando no SinglePlayer ou em um Servidor?

**Comment by ArtpokeBr** [comment]
Agradeceria prints.

**Comment by atlas2468** [comment]
> Agradeceria prints.

estou jogando no singleplayer
mesmo fazendo o crafting correto, e testando todas as 3 possibilidades do crafting nao é possivel craftar

![Captura de Tela (12)](https://user-images.githubusercontent.com/75504748/101230424-9e524080-367b-11eb-9a3b-31b40ae57485.png)
![Captura de Tela (13)](https://user-images.githubusercontent.com/75504748/101230428-a01c0400-367b-11eb-918b-4cb59f586819.png)
![Captura de Tela (14)](https://user-images.githubusercontent.com/75504748/101230429-a0b49a80-367b-11eb-8f2e-750f8ba1fd1f.png)
