### ISSUE TITLE
EMC Bugado

### ISSUE THREAD

**Issue by c67r** [ArtpokeBr/Minecraft-Ultimato#104]
O EMC do ferro está errado (uma barra de ferro vale 256 de EMC, enquanto um minério de ferro vale 768 de EMC).
Provavelmente outros minérios também estão assim, mas não olhei para ter certeza.

Espero ter ajudado :)

**Comment by c67r** [comment]
![image](https://user-images.githubusercontent.com/75510067/101229353-92b44900-367e-11eb-9ef1-df78f111c492.png)
![image](https://user-images.githubusercontent.com/75510067/101229359-9ba51a80-367e-11eb-8614-bad904b86598.png)

**Comment by FantasyCraft864** [comment]
eu ia falar isso, cada minério tem exatamente 3 vezes o valor de sua respectiva barra. isso deveria ser alterado para cada minério ter 5 vezes o valor da barra. Pois usando o Mekanism é possível quintuplicar cada minério

**Comment by FantasyCraft864** [comment]
pensando bem, é melhor tirar o emc dos minérios. se eu tenho 1 minério que vale 5 vezes a barra posso usar o Project e para a quintuplicarão. E se eu tenho um minério que vale menos que a barra posso duplicar o minério usando os mods e trocando de volta ao minério para voltar a duplicação.

**Comment by ArtpokeBr** [comment]
Eu já tirei o EMC de todos os Ores, então já foi corrigido :)
