### ISSUE TITLE
nn sei se é bem um erro

### ISSUE THREAD

**Issue by Peladinhopro** [ArtpokeBr/Minecraft-Ultimato#107]
nn sei bem se é um bug ou nn 
mas se tiver com o pet da aranha e uma pistola 
e segurar o shift 
nn toma dano de queda
OBS: estou no meu mundo 
configuração ta a mesma do mod

**Comment by ArtpokeBr** [comment]
Provavelmente é coisa do Pet da aranha? n sei kkkk vou fechar pq tá confuso.
