### ISSUE TITLE
Problema de ram

### ISSUE THREAD

**Issue by PerryGamerPT** [ArtpokeBr/Minecraft-Ultimato#108]
Descobri que a tradução para inglês faz o nosso computador utilizar menos ram '-'
![image](https://user-images.githubusercontent.com/20173828/101237415-c3c16780-36d8-11eb-886d-25bac723ec4e.png)

**Comment by ArtpokeBr** [comment]
esqueci de atualizar em baixo mesmo, já vou atualizar aqui.
