### ISSUE TITLE
Bug em mobfarm/ Daria pra farmar muito emc

### ISSUE THREAD

**Issue by Crizinha** [ArtpokeBr/Minecraft-Ultimato#109]
Olá não sei se ja reportarão mas quando o mob morre para qualquer tipo de trap ou spike ele esta dropando muita cabeça (mas muita mesmo)
Ótimo pra quem gosta de farmar emc kkkkk! peninha que não gosto mas imagina chagar no baú e ter 6k de cabeça de esqueleto creeper e zumbis então uiui  rsrsrs fora isto estou amando jogar! Parabéns pelo esforço!

**Comment by ArtpokeBr** [comment]
Qualquer Spike ou trap? tinham me passado essa informação e eu tinha testado na verdade só com o Matador do Mob Grinding Utils, mas isso tá acontecendo com qualquer matador??
