### ISSUE TITLE
Mod de emojis não funciona

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#11]
Mod de emojis de chat nao funciona por causa do mod de Emoticons
![image](https://user-images.githubusercontent.com/54782518/100307613-11293080-2f85-11eb-8d82-6524c645df67.png)

**Comment by ArtpokeBr** [comment]
Isso é conflito com o Quark mesmo, posso desabilitar para não causar problemas com a galera.
