### ISSUE TITLE
MC da cabeça de wither

### ISSUE THREAD

**Issue by karutoplays** [ArtpokeBr/Minecraft-Ultimato#110]
Fala Jovem.. 
Viu quero te mostrar aqui como esta desbalanceado o MC da cabeça de whiter..
pq eu to farmando muito MC so com cabeça de item.. tem um item que é uma cabeça de ghast que com ele vc pode craftar cabeça de wither.. e o mc desse item de ghast é muito baixo.. entao eu farmo muito ele nao mesa de MC e transformo tudo em cabeça de wither e jogo tudo na mesa de MC.. praticamente 6x mais MC.. veja as imagens ...
![2020-12-05_10 34 31](https://user-images.githubusercontent.com/75497419/101244543-f160dd80-36e5-11eb-8f32-bbe4397967ff.png)
![2020-12-05_10 34 33](https://user-images.githubusercontent.com/75497419/101244545-f32aa100-36e5-11eb-8572-dc4056401cfb.png)
![2020-12-05_10 35 17](https://user-images.githubusercontent.com/75497419/101244547-f32aa100-36e5-11eb-9a4d-95b215012d52.png)

**Comment by HeitorEgito** [comment]
Bom dia, gostaria de saber qual as peças do seu pc, pq queria baixar mas, não sei se o meu pc aguenta. Boa Tarde, aguardo resposta

**Comment by karutoplays** [comment]
Fala Jovem..
Meu Computador: Processador Ryzen 5 1600af Placa-mae GA -AB350M Memoria:
16Gb DDR4 2666Mhz Armazenamento Sdd Kingston 256GD - Hdd 1TB Seagate
Barracuda Placa de Video RX 560D 4GB Microfone BM-800 HeadSet H310 7.1

tenho um canal no Youtube,, se puder entrar la dar uma olhada

https://www.youtube.com/watch?v=2aJdXlvCH1E&t=28s

Em sáb., 5 de dez. de 2020 às 12:18, HeitorEgito <notifications@github.com>
escreveu:
