### ISSUE TITLE
sou eu de novo, como faz para jogar com meu amigo

### ISSUE THREAD

**Issue by amigodetodos** [ArtpokeBr/Minecraft-Ultimato#112]
quando eu tento entrar no mundo dele da o mesmo problema toda vez alguem sabe como faz para dar certo
![Captura de Tela (21)](https://user-images.githubusercontent.com/75332723/101246416-f88de880-36f1-11eb-809c-a33975c52191.png)

**Comment by ArtpokeBr** [comment]
Isso não me parece erro do Modpack, e sim da coneção ai que se tá tentando fazer com seu amigo. os arquivos pra servidor ainda não foram disponibilizados então quando for fazer um server tenha isso em mente!

**Comment by amigodetodos** [comment]
Vcs sabem em qual data mais ou menos vcs vao disponibilizar o arquivo do
servirdor, ou vcs nao vão disponibilizar?

Em sáb, 5 de dez de 2020 12:32 PM, ArtpokeBr <notifications@github.com>
escreveu:

**Comment by ArtpokeBr** [comment]
vai ser disponibilizado assim que o próximo patch for lançado, eu diria que até o fim do mês.

**Comment by amigodetodos** [comment]
Valeu!

Em sáb, 5 de dez de 2020 7:08 PM, ArtpokeBr <notifications@github.com>
escreveu:

**Comment by amigodetodos** [comment]
Opa sou eu de novo faz um tempin, so queria fazer uma pergunta, vcs ja
liberaram para jogar com amigo no mod pack ultimato?

Em sáb, 5 de dez de 2020 9:00 PM, ArtpokeBr <notifications@github.com>
escreveu:
