### ISSUE TITLE
Sem geração de platinum

### ISSUE THREAD

**Issue by Progamadormirim** [ArtpokeBr/Minecraft-Ultimato#113]
Não é um bug, é só que platinum não está sendo generado no mundo, tem mudar as configurações do Thermal Foundation.
Sem platinum não da para fazer o Atomic Disassembler do Mekanism.
Eu fiz o backup do arquivo 01_thermalfoundation_ore.json para modifica-lo, mudei a config do platinum, retrogen para true mudei a altura de spawn e a quantidade que vem por veia de minério.
E não crashou ...

**Comment by ArtpokeBr** [comment]
Confere, pq se eu n me engane platinum tá gerando em outras dims tbm, além do que se eu bem me lembre, platinum é bem raro mas gera sim!
