### ISSUE TITLE
Bug MC Ultimato ao abrir

### ISSUE THREAD

**Issue by Twisted1408** [ArtpokeBr/Minecraft-Ultimato#114]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Descrição:**
Ao abrir o jogo, depois de carregar todos os mods dá esse erro https://prnt.sc/vwfdum
Não faço a mínima ideia do que seja o problema

**Sugestão de Solução:**

**Passo a Passo para chegar no Problema (Opcional):**
Logo depois de carregar os mods aparece essa mensagem.

**Crash Log:**
Crash
[crash-2020-12-05_14.30.31-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5647418/crash-2020-12-05_14.30.31-client.txt)

**Screenshots:**
https://prnt.sc/vwfdum

**Comment by ArtpokeBr** [comment]
Alocou a quantidade correta de RAM pro modpack? teu jogo tá reclamando por falta de memória.

**Comment by Twisted1408** [comment]
coloquei 4gb '-'

**Comment by ArtpokeBr** [comment]
o Mínimo é 5GB, aloca mais se puder e deve resolver o BO.
