### ISSUE TITLE
bug na geração de vila no mundo dos dragões

### ISSUE THREAD

**Issue by Peladinhopro** [ArtpokeBr/Minecraft-Ultimato#115]
![dsoajfghodsfgkj](https://user-images.githubusercontent.com/75514182/101258530-d00dea80-3701-11eb-91a5-127d09b896b2.PNG)

as casas e os vilarg não estão sendo gerados

joguei a uma printe que tirei aqui

**Comment by misteryous18** [comment]
Está a acontecer para mim independentemente do tipo de mundo gerado, seja default seja superflat sempre fica só os trilho, nada de casas nem villagers.

**Comment by ArtpokeBr** [comment]
Vilas não são geradas mesmo, bug interno, e outra coisa, por que não usou a Template dos Issues?
