### ISSUE TITLE
Informação versão do Java

### ISSUE THREAD

**Issue by pgbezerra** [ArtpokeBr/Minecraft-Ultimato#116]
Adicionar informações da versão do Java na pagina do modpack, aparentemente a mesma só roda na versão 8(1.8) do Java

![image](https://user-images.githubusercontent.com/22059237/101259108-9fc84b00-3705-11eb-97d5-9a161c9830d9.png)

Utilizando a versão 11 (LTS) o modpack não inicia

![image](https://user-images.githubusercontent.com/22059237/101259137-cb4b3580-3705-11eb-987b-2475d5b68db3.png)

![image](https://user-images.githubusercontent.com/22059237/101259156-e1f18c80-3705-11eb-973f-8e7b9d5c4854.png)

**Comment by ArtpokeBr** [comment]
a questão do java eu nem sabia justamente por que o normal é ter o java mais recente né kkk

**Comment by pgbezerra** [comment]
Realmente, como sou desenvolvedor Java geralmente eu uso a ultima versão LTS que atualmente é a 11 e fui surpreendido com esse "problema", mas é algo simples
