### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by XxSlaDoidoxX** [ArtpokeBr/Minecraft-Ultimato#117]
**Versão do Modpack:**
1.12.2

**Descrição:**
O Modpack possui 236 mods... eu acho que isso não funcione pra todo mundo que baixou o modpack inclusive eu, quando eu inicio o jogo, o mundo que eu crio demora MUITO pra carregar e o modpack também mas quando eu finalmente entro no jogo o lag é tão grande que nem com os gráficos no mínimo meu pc aguenta.

**Sugestão de Solução:**
A minha sugestão é vocês fazerem uma versão LITE do modpack com menos mods para ele ser mais acessível para mais pessoas que não tem um pc que roda tudo isso.

**Crash Log:**
Nenhum.

**Screenshots:**
Eu não to com saco pra rodar esse modpack de novo na moral :/

**Comment by ArtpokeBr** [comment]
Olha, fazer Modpacks dá trabalho, não ache que fazer uma versão lite é tão simples assim kkk, quanto de RAM tu alocou pro Pack? normalmente abrir qualquer Modpack extenso leva um tempinho, isso é normal. se tu não roda o Modpack infelizmente não posso fazer nada, já tá otimamente optimizado  =/
