### ISSUE TITLE
Erro Ao dar play 

### ISSUE THREAD

**Issue by ghost** [ArtpokeBr/Minecraft-Ultimato#118]
Eu estou tentando jogar o modpack, mas quando eu dou play aparece que o jogo parou de funcionar e nem inicia 
![Captura de Tela (17)](https://user-images.githubusercontent.com/75542240/101260788-01da7d80-3711-11eb-98bd-c863579ef656.png)

**Comment by ArtpokeBr** [comment]
Primeiro, USE A TEMPLATE DE REPORT MEU DEUS! segundo, isso provavelmente é falta de Memória RAM, quanto alocou?
