### ISSUE TITLE
Quando itens são quebrados não são dropados

### ISSUE THREAD

**Issue by PIFSZINn** [ArtpokeBr/Minecraft-Ultimato#121]
Quando quebro itens eles somem, não importa oque.
Isso começou quando eu estava minerando, primeiro achei que era lag sai e entrei do modpack e não resolveu.

**Comment by ArtpokeBr** [comment]
talvez seja Lag de TPS e não FPS, o TPS estando zuado o mapa n dropa os blocos mesmo, próximo patch talvez alivie isso, por que na verdade não sei exatamente o que está causando isso, já reportaram já.

**Comment by FantasyCraft864** [comment]
Isso aconteceu comigo, acho que sei o que é, bem vamos lá.

Quando você está minerando você provavelmente está usando o mod FTB Ultimate (que é como o Vein Miner, que quebra muitos blocos iguais que estão em conjunto). Tem uma chance de que quando você quebra a picareta que está na sua mão ela "duplique" em uma picareta fantasma ela quebra blocos como uma picareta normal, mas o bloco não dropa e também volta como se fosse LAG de servidor, e se você ficar insistindo em quebrar o bloco, ele some, pois você quebrou o bloco com a mão o que por sua causa faz com que ele não drope. E sair e entrar no mapa; fechar e abrir o ModPack não resolve pois a "picareta fantasma" não desaparece, ela só vai desaparecer quando você colocar um item em cima dela.

**Comment by ArtpokeBr** [comment]
Putz, problema total de TPS isso.
