### ISSUE TITLE
Memória Ram

### ISSUE THREAD

**Issue by Trofiix** [ArtpokeBr/Minecraft-Ultimato#122]
Ola, jogo normalmente o modpack dedicando 8gb de memoria ram para o modpack, mas toda ez que vou jogar tenho que dedicar os 8gb nas configurações, pois ele não sala minhas preferencias e toda vez abre com 4gb dedicados, existe um meio para mim salvar essas preferencias?
![Captura de tela 2020-12-05 173656](https://user-images.githubusercontent.com/75545437/101262904-9c8e8880-3720-11eb-80c5-79a34b1f0adc.png)

**Comment by ArtpokeBr** [comment]
tá usando o Launcher da Curse? por ele tu tem como definir um padrãozinho pro Pack ai nunca perde as configs. recomendo colocar 6GB primeiro não 8GB pro pack.
