### ISSUE TITLE
Mechanical Parts do TechGuns estão sem crafting.

### ISSUE THREAD

**Issue by username-para-mc-ultimato** [ArtpokeBr/Minecraft-Ultimato#125]
**Versão do Modpack:**
1.0.2

**Descrição:**
Alguns itens do mod techguns, como o _Mechanical Parts (Carbon)_ e _Mechanical Parts (Hardened)_, são feitos com a máquina _Metal Press_ do mod, que está inativa no modpack. Parece que seria possível obter esses itens reciclando as armas que são feitas deles no Grinder, mas como não é possível gerá-las sem os itens, caímos num ciclo. 

Esses itens são necessários para construir o Fabricator e a Reaction Chamber, que são máquinas essenciais para o progresso no mod do Techguns. 

**Sugestão de Solução:**
Não tenho certeza se há conflitos dessa máquina com outros mods, mas acredito que a solução mais simples seria ativar o item _Metal Press_. 

**Screenshots:**
No print, a receita do item  _Mechanical Parts (Carbon)_. Deveria existir uma aba para a criação dele com a Metal Press. 

O item  _Mechanical Parts (Hardened)_ nem apresenta receita quando clicado. Acho que este não é possível obter reciclando outros componentes. 

![image](https://user-images.githubusercontent.com/75550387/101268573-1b94b880-3743-11eb-8902-776d6269a700.png)

**Comment by ArtpokeBr** [comment]
Primeiramente, obrigado pelo report bem escrito, isso tem sido incomum. mas fique tranquilo que isso já foi corrigido no próximo patch de correções. eu desativei a metal press pq ela só tinha 2 receitas realmente úteis! o resto eram todas receitas que outras máquinas conseguiam fazer, então desativei por redundância! mas infelizmente não sou onisciente então erros acontecem kkkkk
