### ISSUE TITLE
Conflito de craft

### ISSUE THREAD

**Issue by PIFSZINn** [ArtpokeBr/Minecraft-Ultimato#126]
Quando craftar a engrenagem de iron do mod  "thermal fundation" ele faz um anel de iron do mod "the aether"

**Comment by jubinhaa** [comment]
estou com o mesmo problema, to tentando resolver

**Comment by jubinhaa** [comment]
consegui arrumar, só botei o mod NoMoreRecipeConflict que ja resolveu, baixa a versão 1.12.2

**Comment by ArtpokeBr** [comment]
Esse problema de receita já foi corrigido no próximo patch. fica tranqs :)

**Comment by PIFSZINn** [comment]
por a onde vc instalou esse mod, coloca o link ou fala por a onde?
