### ISSUE TITLE
industrial craft 2 

### ISSUE THREAD

**Issue by guto0938** [ArtpokeBr/Minecraft-Ultimato#127]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
Minecraft Ultimato-1.0.2.zip

**Descrição:**
Substitua este texto por uma descrição do seu problema! sobre o que exatamente está acontecendo, como você chegou á este problema e etc. tenha em mente que isto é importante para que eu possa entender o seu problema.

**Sugestão de Solução:**
industrial craft2

**Passo a Passo para chegar no Problema (Opcional):**
abri o jogo mas n inicia

**Crash Log:**
[crash-2020-12-06_11.26.17-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5648916/crash-2020-12-06_11.26.17-client.txt)

**Screenshots:**
![Captura de tela 2020-12-06 113724](https://user-images.githubusercontent.com/75574626/101283185-ae6f3a80-37b7-11eb-8e2c-6a6c3550b13e.png)

**Comment by ArtpokeBr** [comment]
Antes mesmo deu olhar o Crash Report, quanto de RAM tem no PC? normalmente erros antes de Abrir com o IC2 é por falta de memória alocada.

**Comment by guto0938** [comment]
8gb
tem como eu mudar o tanto q o mine vai usar ?

**Comment by ArtpokeBr** [comment]
tem e você DEVE mudar inclusive, como possui 8GB no pc, aloque 5 ou 6 e teste.

**Comment by guto0938** [comment]
vc fez um vídeo ensinando como faz? se sim pode me passar o link ?

**Comment by ArtpokeBr** [comment]
Nope, esse é o conhecimento mínimo que se deve ter ao jogar Mine e etc. qual launcher está usando? se for a curse é só ir nas configurações do launcher mesmo e ir na aba mine, lá vai ter um lugar pra tu especificar no geral o quanto os Modpacks instalados devem usar.
