### ISSUE TITLE
Techguns "Metal Press"

### ISSUE THREAD

**Issue by GabrielFl4** [ArtpokeBr/Minecraft-Ultimato#129]
No momento não estou no pc do qual eu jogo o Ultimato, porém creio que seja a versão mais recente (Baixei recentemente)

**Descrição:**
O problema é a falta de um item, o item é do mod "TechGuns" e é uma espécie de bancada para o crafting de um componente essencial para avançar no mod. O nome da bancada é "metal press" e é presente em todos os vídeos tutorial sobre o mod.
Como sendo a única forma de conseguir craftar itens avançados, ela é fundamental.
Quando eu clico na receita de algum item feito na metal press, nada acontece, não tem crafting. Realmente não sei se você conseguira adiciona-la ao modpack, mas eu gostaria muito!

**Sugestão de Solução:**
Bem, como é a falta de um item para um mod, acho que a única solução seria tentar adiciona-lo ao mod manualmente. (Eu não me dou muito bem fazendo isso)

**Passo a Passo para chegar no Problema (Opcional):**
Apenas veja o crafting de uma arma como uma M4, que utiliza componentes de carbono (Os quais são feitos na metal press)

**Screenshots:** 
(A print vem de um vídeo tutorial)
![image](https://user-images.githubusercontent.com/75579401/101286891-ea13ff80-37cb-11eb-98e1-1bd8889c95d6.png)

**Comment by ArtpokeBr** [comment]
a Metal press foi tirada por conta de redundâncias, ela só tinha realmente 2 craftings úteis dentro dela, então a removi. isso acabou gerando um probleminha msm com 2 receitas do Tech, mas isso já foi corrigido no próximo patch que chega esse mês!
