### ISSUE TITLE
Itens não são dropados

### ISSUE THREAD

**Issue by tijolotatico** [ArtpokeBr/Minecraft-Ultimato#13]
quando se passa algum tempo jogado, toda vez que você dropa algum item ou quebra algum bloco as entidades de item somem, é como se o bloco não dropasse nada.

**Comment by ArtpokeBr** [comment]
teria como demonstrar isso melhor? algum vídeo ou qualquer outra informação ajudaria.... pois desse jeito não consigo saber oq é kkk

**Comment by tijolotatico** [comment]
https://www.youtube.com/watch?v=MjzNszWcFtQ

**Comment by ArtpokeBr** [comment]
Issso faz o jogo crashar ou só os itens dropados que não existem? testou com outras ferramentas? ou só as Wub?

**Comment by tijolotatico** [comment]
não, isso aconteceu em meu mundo solo tbm e eu estava com itens de pedra e ferro.
