### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by Peladinhopro** [ArtpokeBr/Minecraft-Ultimato#130]
no modpack tem um mod que mostra o tier e essas coisas 
o mod q aparece na centro superior da tela 
o meu esta disabiltado e nn sei como abilitar e nem o nome desse mod

**Comment by ArtpokeBr** [comment]
como assim o seu está desabilitado? e como assim mod que mostra o tier das coisas? se quer dizer o Waila ou o TheOneProbe? outra coisa, por que não forneceu uma print? fica difícil assim kk

**Comment by Peladinhopro** [comment]
![adsjf](https://user-images.githubusercontent.com/75514182/101295386-25c6bd80-37fc-11eb-9396-75b7c922e520.PNG)
o mod que da a descrição 
que fica uma telinha dentro do circulo azul

**Comment by ArtpokeBr** [comment]
TheOneProbe mesmo, vem por padrão no modpack, não sei oq tu fez.

**Comment by Peladinhopro** [comment]
tem como habilitar ele ?
só tava jogando e sumiu do nada 
nn tem alguma configuração q desabilita ou habilita ele ?

**Comment by ArtpokeBr** [comment]
deve ter uma keybind, dá uma olhada.

**Comment by Peladinhopro** [comment]
eu nn sei nem oq é isso kkk

**Comment by ArtpokeBr** [comment]
Olhe as teclas, deve ter uma para desativar e habilitar.

**Comment by Peladinhopro** [comment]
![çlkjdsfa](https://user-images.githubusercontent.com/75514182/101298189-814c7780-380b-11eb-9b7a-ce2e6229c0a3.PNG)
só tem esta
mas nn funcionou

**Comment by ArtpokeBr** [comment]
marca a categoria ali, isso limita a pesquisa pra um determinado mod.

**Comment by Peladinhopro** [comment]
![sahiof](https://user-images.githubusercontent.com/75514182/101299213-1baeba00-3810-11eb-8e32-7d94f83ee43d.PNG)
tbm nn habilito

**Comment by ArtpokeBr** [comment]
meu deus, pega o papelzinho do Mod então e tenta configurar dnv um local pra ficar.

**Comment by Peladinhopro** [comment]
![654156](https://user-images.githubusercontent.com/75514182/101410669-73a3fa00-38be-11eb-850b-94821f259460.PNG)
acho q o mod desistiu de funciona kkk
nn deu tbm

**Comment by ArtpokeBr** [comment]
Ah, tenta pegar o item chamado probe que existe no Mod, tenta segurar ele na mão que ele geralmente força tu ver algo, se isso n funfar, joga sem mesmo kkk

**Comment by Peladinhopro** [comment]
![AASGDF](https://user-images.githubusercontent.com/75514182/101415143-27f54e80-38c6-11eb-9967-2f55a15e67b3.PNG)
sera que se remove abri e fecha o jogo e coloca dnv nn resolve ?

**Comment by Peladinhopro** [comment]
![khjsdfad](https://user-images.githubusercontent.com/75514182/101416820-5aed1180-38c9-11eb-9d07-7304ce06e053.PNG)
coloquei aqui e funciono 
vl man
pode fecha esse problema
