### ISSUE TITLE
Bug de visão constante 

### ISSUE THREAD

**Issue by iceteaftw** [ArtpokeBr/Minecraft-Ultimato#132]
Cada vez que eu tenho algum efeito de velocidade o meu campo de visão diminui bastante e isso é muito estranho não consigo jogar assim, alguém sabe se isso é um bug ?

**Comment by ArtpokeBr** [comment]
Isto é um bug visual que tem ocorrido não só com você, e infelizmente não sei daonde ele vem.

**Comment by iceteaftw** [comment]
Mas desaparece ou fica lá para sempre ?~

**Comment by ArtpokeBr** [comment]
Até aonde sei só realmente acontece quando você está com algum tipo de alteração de velocidade, ou talvez quando seu FOV está alterado demais do normal e etc.

**Comment by iceteaftw** [comment]
Outra coisa, desculpa estar-te a dar tanto trabalho, mas as galinhas do roost estão a spawnar muito pouco, as galinhas principais como a galinha de flint.

**Comment by ArtpokeBr** [comment]
normal, os spawns foram reduzidos pro server da série não ter problema.

**Comment by iceteaftw** [comment]
As galinhas principais dão spawn em qualquer sitio do overworld ou cada uma tem o seu bioma ?

**Comment by ArtpokeBr** [comment]
o spawn delas só foi reduzido, mas não trocado, então os padrões do mod se aplicam nesse caso.

**Comment by iceteaftw** [comment]
Ok muito obrigado pelo seu tempo .
