### ISSUE TITLE
Terra dos dragões

### ISSUE THREAD

**Issue by OtavioCSalvador** [ArtpokeBr/Minecraft-Ultimato#133]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Descrição:**
Quando eu crio o portal para a terra dos dragões, não carrega nenhuma cópia do overworld, só é criado uma plataforma de terracota com algumas tochas!!!

**Passo a Passo para chegar no Problema (Opcional):**
Tentar entrar na terra dos dragões com o portal!

**Comment by ArtpokeBr** [comment]
crie o mundo usando o preset do topography, sem ele a terra de dragões não é carregada, isso é um erro seu.

**Comment by ArtpokeBr** [comment]
e não é pra soar tão rude assim é só que é cada erro que me aparece de vez enquando do pessoal que n presta a atenção kkk
