### ISSUE TITLE
Vilas do vanila e outras estruturas não dão spawn

### ISSUE THREAD

**Issue by JoaoMAdureira1** [ArtpokeBr/Minecraft-Ultimato#134]
As vilas do vanila não são geradas apesar dos caminhos de terra diferentes aparecerem.
Mesmo depois de mexer nas configs do mod Ice and Fire e aumentar a chance de aparecer a gruta ou o ninho dos dragões eles não aparecem.

**Comment by ArtpokeBr** [comment]
primeiro, NÃO MEXA NAS CONFIGS E DEPOIS VENHA RECLAMAR! segundo, a template de report de bugs é boa viu, poderia ter usado ela... e teceiro, as vilas não gerarem é algo conhecido, um bug que n consigo consertar e etc, e por fim, os dragões geram numa dimensão específica, mas se você não leu o diário do thanos para se informar...

**Comment by ArtpokeBr** [comment]
e não é pra soar tão rude assim é só que é cada erro que me aparece de vez enquando do pessoal que n presta a atenção kkk

**Comment by JoaoMAdureira1** [comment]
Peço desculpa, não era minha intenção soar rude xD
Eu só mexi nas configs depois de testar as default :/
Mais uma vez não era para ser rude, como sou de Portugal a minha escrita pode ser um pouco diferente desculpe!

**Comment by ArtpokeBr** [comment]
nah n foi por ser portuga não, é mais fácil eu soar rude ao responder issues, pq as vezes só quero resolver, mas dá uma olhada na documentação antes de reportar algo, e se precisar, use a template fornecida pois facilita.
