### ISSUE TITLE
Ideia de mod + bug

### ISSUE THREAD

**Issue by PIFSZINn** [ArtpokeBr/Minecraft-Ultimato#135]
Ter um mod de chunk load só para quem esta jogando survival, pq no server eu sei que laga. Porque eu estava longe da minha casa e queria abrir meu sistema de itens e não dava pq a chunk nao estava carregada.

bug: quando eu deito na cama não esta marcando spawnpoint.

**Comment by ArtpokeBr** [comment]
quanto a cama não esta marcando spawnpoint não sei do que se trata, mas em relação a chunk loaders, recomendo que você instale por contra própia, as exigências para série e para o servidor rodar tranquilamente foram justamente que eu desativasse então... sugestão minha, bota o FTB Utilities e seja feliz kkk

**Comment by ArtpokeBr** [comment]
vou fechar pra n ter confusão.
