### ISSUE TITLE
Conflitos com os controles

### ISSUE THREAD

**Issue by HugoFidalgo** [ArtpokeBr/Minecraft-Ultimato#137]
**Versão do Modpack:**
1.0.2

**Descrição:**
Olá, desculpe incomodar, mas alguns controles aprecem com conflito, não sei se é um problema só meu, agradeço a atenção

**Screenshots:**
![Captura de Ecrã (2)](https://user-images.githubusercontent.com/75612477/101337427-91983d00-3873-11eb-83f2-9ab3b8fa8866.png)

**Comment by ArtpokeBr** [comment]
vou fechar para não ter confusão :)
