### ISSUE TITLE
Itens dropados, quebrados no mundo são excluídos

### ISSUE THREAD

**Issue by JvGame** [ArtpokeBr/Minecraft-Ultimato#138]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:** 1.0.2

**Descrição:**Estava eu e meu amigos jogando normalmente num mundo lan que ele criou e donada la pelas 12 noite eu voltei da twilight e ele me fala que quando quebra os blocos os itens nao saem, ai eu tentei quebrar tambem e nao ia nem usar aquele ` grave do teclado pra quebra rapido varios blocos nao tava funcionando ai eu fui ver minha farm de emc de maca tambem nao estava dropando maca eu tava tentando dropar blocos no chao e eles sumiam, entao ta praticamente injogavel, porque nao da pra minerar jogar itens no chao e nem tudo que seja com itens no chao, e nos nao sabemos como resolver.

**Sugestão de Solução:**Sinceramente n faco ideia

**Passo a Passo para chegar no Problema (Opcional):**Nao achei como resolver

**Crash Log:**Nao consigo

**Screenshots:**Nada

Se vc quiser ver os Crashs Log do meu amigos eu peco pra ele tambem posso mandar video de como ta dentro do jogo...

**Comment by ArtpokeBr** [comment]
Olha, os itens e blocos não estarem droppando muito provavelmente é problema de TPS, ou seja, o servidor está laggando com algumas coisas no mapa e etc, até o fim do mês sai um patch que deve ajudar um pouco nisso, mas por enquanto, cuidado com essa "farmzinha de EMC" e qualquer outra coisa no mapa que pareça ineficiente ou exagerada. normalmente servidores não gostam disso.

**Comment by ArtpokeBr** [comment]
vou fechar já que não posso fazer muita coisa agora, e o jeito é esperar o patch chegar, qualquer outra coisa me informe.
