### ISSUE TITLE
minecraft não abre

### ISSUE THREAD

**Issue by xandegp** [ArtpokeBr/Minecraft-Ultimato#139]
toda vez que tento abrir o minecraft ele crasha e não consigo jogar

ja coloquei o ram no maximo no mult mc

**Comment by ArtpokeBr** [comment]
o Erro está exatamente na sua mensagem, alocar o máximo de memória disponível não é aconselhável e muito provavelmente é o Motivo de tu nem conseguir abrir o Modpack, quanto de RAM tem no PC inteiro ai?

**Comment by xandegp** [comment]
ola artpokebr, meu pc tem 8 gigas de ran

**Comment by ArtpokeBr** [comment]
Aloca 5GB de poco pro Modpack que isso é o suficiente. não precisa alocar e não deve alocar tudo que tem no PC.

**Comment by xandegp** [comment]
obrigado
