### ISSUE TITLE
Muitos Mobs na água.... 

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#14]
Preciso dizer alguma coisa? kkk Tem q nerfar isso aqui
![image](https://user-images.githubusercontent.com/54782518/100391806-70ce1d00-3013-11eb-90a2-669648fccd56.png)

**Comment by ArtpokeBr** [comment]
pior que todos os Mobs do Mod em si estão com menos do que 10 ou 5 de chance de spawnar e mesmo assim spawnam um bucado em determinadas situações...

**Comment by Christtiann** [comment]
![image](https://user-images.githubusercontent.com/54782518/100409725-6596e380-304b-11eb-94d2-542b1c68cd37.png)
cara...

**Comment by Christtiann** [comment]
Mesmo removendo nas configs....
![image](https://user-images.githubusercontent.com/54782518/100410455-8f510a00-304d-11eb-8e5c-c8b64bb3c883.png)
Olha aqui desativado...
![image](https://user-images.githubusercontent.com/54782518/100410500-ad1e6f00-304d-11eb-8603-df046488494a.png)
Acho que é alguma coisa do topografy porem nao sei mexer...

**Comment by ArtpokeBr** [comment]
o Topography não controla necessáriamente os Mobs, ainda mais estando no Overworld normal... o Overworld normal não está sendo afetado pelo topography em nada kkk

**Comment by ArtpokeBr** [comment]
Pois é, isso possivelmente é problema do Mod mesmo... =/

**Comment by Christtiann** [comment]
Tive que tirar... os mobs nao somem... ficou com 2k de mobs o lag estava absurdo

**Comment by ArtpokeBr** [comment]
Ok, acho que devo fechar o Issue então? pq se você mesmo reduziu ao máximo ai e não deu certo, n adiantaria eu tentar...

**Comment by Christtiann** [comment]
Pode fechar, só estou avisando por causa do server deles la... Enquanto a gente construía o spawn gerou 2k de mobs kkkkk
