### ISSUE TITLE
Items e blocos pararam de dropar

### ISSUE THREAD

**Issue by desconection** [ArtpokeBr/Minecraft-Ultimato#140]
**Versão do Modpack:**
1.0.2

**Descrição:**
Estava jogando em LAN com um amigo e do nada nenhum item ou bloco estava dropando, simplesmente não dropa absolutamente nada, você quebra e o bloco "some".

**Passo a Passo para chegar no Problema (Opcional):**

Não sei, foi aleatório depois de um tempo, só resolve criando outro mundo, o que é um problema, já que estavamos muito tempo nesse mundo.

**Crash Log:**

Não tem crash

**Comment by ArtpokeBr** [comment]
Isso normalmente é problema de TPS, o próximo patch do Modpack deve ajudar um pouco, mas qualquer coisa, procura a tecla do Laggoggles ai e usa o Mod pra localizar aonde tá tendo Lag de TPS, mas geralmente setups ineficientes e afins costumam atrapalhar.

**Comment by ArtpokeBr** [comment]
vou fechar, já que não posso fazer muita coisa agora. o jeito é esperar o Próximo patch pra ajudar nesses problemas, qualquer outra coisa me reporte.
