### ISSUE TITLE
Não posso mudar Angel Ring no Chisel

### ISSUE THREAD

**Issue by GamesRevolution** [ArtpokeBr/Minecraft-Ultimato#141]
**Versão do Modpack:**
1.0.2

**Descrição:**
A descrição do Angel Ring fala que você pode colocar o Angel Ring no Chisel para mudar o estilo de asa, mas isso não acontece

**Screenshots:**
![image](https://user-images.githubusercontent.com/75512432/101369532-340deb80-3887-11eb-87e3-116ea319c011.png)

**Comment by ArtpokeBr** [comment]
Oxi não tá acontecendo? tem como mandar uma Print com o mouse em cima do Angel ring msm? suspeito que seja algum problema de NBT... esse é o angel ring padrão né?

**Comment by GamesRevolution** [comment]
![image](https://user-images.githubusercontent.com/75512432/101370194-f493cf00-3887-11eb-9e7f-8e8b3b4ceca7.png)

**Comment by ArtpokeBr** [comment]
Half hearted? Oxi, de onde saiu isso? ele pegou um atributo do Quality Tools? meu deus...

**Comment by GamesRevolution** [comment]
Esse Quality Tools coloca atributo em um monte de coisas, imagino que tenha outras ferramentas ou item que podem pegar um atributo mesmo que não seja pretendido

**Comment by ArtpokeBr** [comment]
vou ter que dar uma checada pra talvez remover do Angel Ring ent.
