### ISSUE TITLE
Bug nas armaduras do avaritia / tinkers

### ISSUE THREAD

**Issue by gxrdin** [ArtpokeBr/Minecraft-Ultimato#142]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Descrição:**
A textura das armaduras do tinkers / avaritia estao bugadas

**Sugestão de Solução:**
nao sei uma solução

**Passo a Passo para chegar no Problema (Opcional):**
Crie uma armadura do tinkers / avaritia, a armadura do tinkers foi feita de Knight slime, Demon ingot e obsidian

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5653642/latest.log)

**Screenshots:**
![image](https://user-images.githubusercontent.com/75629177/101371724-dd55e100-3889-11eb-8d54-926888773ffd.png)

**Comment by ArtpokeBr** [comment]
se estiver com o Mod do Emoticons habilitado, eu diria que o motivo é ele kk
