### ISSUE TITLE
Conflito de Receita de Iron Gear com o Iron Ring

### ISSUE THREAD

**Issue by GamesRevolution** [ArtpokeBr/Minecraft-Ultimato#143]
**Versão do Modpack:**
1.0.2

**Descrição:**
Não é possível fazer uma iron gear pela crafting table, pois você vai fazer uma iron ring ao invés

**Sugestão de Solução:**
Mudar a receita ou colocar um mod de alternar receitas na crafting table, assim podendo escolher qual receita você quer usar

**Screenshots:**

![image](https://user-images.githubusercontent.com/75512432/101374130-8dc4e480-388c-11eb-952b-6a4a2be0649e.png)
![image](https://user-images.githubusercontent.com/75512432/101374171-9b7a6a00-388c-11eb-9e53-da989cfa052a.png)

**Comment by ArtpokeBr** [comment]
já foi corrigido no próximo patch.
