### ISSUE TITLE
Wither Skeletons não estão spawnando

### ISSUE THREAD

**Issue by GamesRevolution** [ArtpokeBr/Minecraft-Ultimato#144]
**Versão do Modpack:**
1.0.2

**Descrição:**
Wither Skeletons não spawnam nas fortalezas do Nether, esperei por mais de 30 minutos para spawnar mas nada spawnou, unica coisa que spawna é blazes dos spawners

**Screenshots:**
![image](https://user-images.githubusercontent.com/75512432/101375248-eb0d6580-388d-11eb-82c8-1a8758b9aaf4.png)

**Comment by ArtpokeBr** [comment]
Provavelmente é azar o seu, pois até na série do Ultimato já vi participante enfrentando wither skeleton.

**Comment by ArtpokeBr** [comment]
ou pode ser problema do patch atual, já que o dos participantes é ligeiramente diferente. vou fechar pra n ter confusão.

**Comment by ShenzenKG79** [comment]
Existe uma estrutura do Inventory Pets que gera no nivel da lava no nether, lá dentro tem uns 10 wither skeletons invisiveis, foi assim que eu peguei os drops deles.
