### ISSUE TITLE
Digital Miner do Mekanism não coletando todos os minerios

### ISSUE THREAD

**Issue by Hirothewolf** [ArtpokeBr/Minecraft-Ultimato#146]
**Versão do Modpack:**
Minecraft Ultimato 1.12.2

**Descrição:**
Apos o Preparo para a montagem da "Digital Miner" do Mod "Mekanism" percebi que a mesma so estava reconhecendo e minerando somente dois tipos de minerio o "Wub Wub Ore" e o "Ender Ore"(os dois do Tiny Progressions), Mudei o local aonde estava o "Digital Miner" e o resultado foi o mesmo, inclusive em uma das prints tem minerio de carvão logo dentro da area da mesma

**Sugestão de Solução:**
Não sei se realmente é algum bug do proprio mekanism ou se eu fiz algo diferente(ja fazia essa configuração antigamente)

**Screenshots:**
![2020-12-07_20 05 14](https://user-images.githubusercontent.com/75646500/101416753-3c871600-38c9-11eb-8377-62dd7baafff2.png)
![2020-12-07_20 05 24](https://user-images.githubusercontent.com/75646500/101416762-40b33380-38c9-11eb-9572-4fc7e6efa8c6.png)
![2020-12-07_20 04 41](https://user-images.githubusercontent.com/75646500/101416768-43158d80-38c9-11eb-8735-744c8eae7a92.png)
![2020-12-07_20 04 46](https://user-images.githubusercontent.com/75646500/101416771-4577e780-38c9-11eb-9971-68b0a9eb695c.png)
![2020-12-07_20 05 05](https://user-images.githubusercontent.com/75646500/101416776-47da4180-38c9-11eb-96dd-3cc67797071b.png)

**Comment by ArtpokeBr** [comment]
se tentou colocar especificamente um OreDict de algum minério? ali tu colocou podendo ser qualquer ore, mas talvez isso possa estar sendo o problema slá, tenta especificar algum tipo de ferro ou coisa do tipo

**Comment by VF-Plays** [comment]
Tenta colocar o "Ore" no filtro com o "O" minusculo
