### ISSUE TITLE
Erro a instalação do modpack no aplicativo da forge

### ISSUE THREAD

**Issue by PedroHenrique2008** [ArtpokeBr/Minecraft-Ultimato#147]
Na instalação do modpack no aplicativo da CurseForge na parte do carregamento do mod do The Betweenlands,o erro vem com o cancelamento do dowload e uma mensagem em vermelha escrito TimeOut e mais outras coisas que infelizmente nao lembro pois fechei a mensagem,se pudesse fazer uma versão tirando o Betweenlands,ou algo pra tirar esse erro agradeceria muito.

https://prnt.sc/vxwfgk

**Comment by ArtpokeBr** [comment]
Isso infelizmente é da cuse, o launcher ainda está com leves problemas até mesmo por estar em beta, peço que aguarde até mesmo para versões novas do Modpack, que talvez esse problema se solucione sozinho. vou fechar para não ter confusão.

**Comment by ShenzenKG79** [comment]
Eu estava tendo o mesmo problema, o jeito é esperar um dia em que sua internet estiver bem boa e daí tentar denovo, não é problema da curseforge, o launcher da twitch ja era assim.
