### ISSUE TITLE
Não consigo entrar no meu mapa

### ISSUE THREAD

**Issue by gxrdin** [ArtpokeBr/Minecraft-Ultimato#148]
**Nota**: !

**Versão do Modpack:**
1.0.2

**Descrição:**
O modpack abre normal, mas quando eu tento entrar no meu mapa especifico, ele da um crash do topography

**Sugestão de Solução:**
nao sei

**Passo a Passo para chegar no Problema (Opcional):**
Eu abro o modpack, mas quando eu tento entrar no meu mapa especifico, ele da um crash do topography
**Crash Log:**
[crash-2020-12-07_15.35.44-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5656152/crash-2020-12-07_15.35.44-server.txt)

**Screenshots:**

**Comment by ArtpokeBr** [comment]
tá com a RAM Alocada certinha? criou o Mundo certinho pelo topography?

**Comment by gxrdin** [comment]
> tá com a RAM Alocada certinha? criou o Mundo certinho pelo topography?

eu aloquei 7619gb d ram, e o mundo foi criado certin, eu até tava jgnd nele, mas eu reiniciei o mine, e ele deu esse erro qnd eu tentei entrar no mapa dnv

**Comment by ArtpokeBr** [comment]
bom, o Erro foi de TPS, eu diria que o próximo patch deve dar uma ajuda com esse tipo de problema, tenta outro mapa, mas se acontecer dnv no momento não sei oq fazer para corrigir =/

**Comment by gxrdin** [comment]
Ok, será que não foi o time in a bottle que causou o crash? E vlw ae por ter tentado ajudar
