### ISSUE TITLE
Impossível completar o avaritia....

### ISSUE THREAD

**Issue by Lellis26** [ArtpokeBr/Minecraft-Ultimato#149]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1,0,2
**Descrição:**
Rapaz eu encontrei vários problemas em relação a crafts, Primeiro com o techguns que 2 dos 3 mechanicals n tem craft, o titanio pra poder fazer a singularidade tbm não tem como fazer, as joias do infinito também não da.... To mandando alguns prints q eu achei relevante...

Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.
 
![trigo jei](https://user-images.githubusercontent.com/75538967/101435352-fa6ecc00-38ea-11eb-8d9c-2b7f92b1fb7f.png)
![trigo](https://user-images.githubusercontent.com/75538967/101435356-fb9ff900-38ea-11eb-98b7-0860b850c193.png)
![techguns sem craft](https://user-images.githubusercontent.com/75538967/101435369-fe9ae980-38ea-11eb-9d7f-6cac397efe58.png)
![balsamo jei](https://user-images.githubusercontent.com/75538967/101435388-065a8e00-38eb-11eb-9c20-abb48964ed64.png)
![balsamo](https://user-images.githubusercontent.com/75538967/101435390-078bbb00-38eb-11eb-8547-27464c2aba2c.png)
![joiajei](https://user-images.githubusercontent.com/75538967/101435511-3a35b380-38eb-11eb-98a1-8a40418652d9.png)
![joia](https://user-images.githubusercontent.com/75538967/101435513-3ace4a00-38eb-11eb-9a69-8e15ab6bcb81.png)

**Comment by ArtpokeBr** [comment]
Acabei de perceber que esse Issue não apareceu pra mim na época, mas o problemas ainda persistem? não sei se chegou a testar as versões mais recentes.

Provavelmente deve ter sido um problema com o Git pra eu n ter visto isso antes =/

Vou fechar, qualquer coisa só falar!
