### ISSUE TITLE
o único Erro que está acontecendo na receita é apenas por código mesmo, mas pegar o pufferfish não deve ser problemático não, existem várias formas de se farmar peixe.

### ISSUE THREAD

**Issue by ShadowSZ2** [ArtpokeBr/Minecraft-Ultimato#152]
o único Erro que está acontecendo na receita é apenas por código mesmo, mas pegar o pufferfish não deve ser problemático não, existem várias formas de se farmar peixe.

_Originally posted by @ArtpokeBr in https://github.com/ArtpokeBr/Minecraft-Ultimato/issues/150#issuecomment-740365651_                                                                                 então art não e possivel pegar o pufferfish tenta ae pegar ele ai voce ira ver!

**Comment by ArtpokeBr** [comment]
por que tu abriu um Issue novo? era só responder naquele...
