### ISSUE TITLE
Chickens de Roost (mod) não gera no overworld.

### ISSUE THREAD

**Issue by Nuturn** [ArtpokeBr/Minecraft-Ultimato#153]
Bom estou com esse problema das galinhas de minérios não dão spawn no overworld, rodei o mapa por 15-20min é não encontrei uma sequer, achei que era um problema em meu mundo, então fui e criei outro mundo é ainda assim aconteceu a mesma coisa, elas não dão spawn. Por incrível que pareça no Nether aparece algumas ,o problema é so no overworld.
Estou utilizando a ultima versão do modpack.
Não sei se isso é um bug ou uma configuração que precisa ser ajustada pelo próprio player, porque na serie a galera (youtubers) encontram bastante essas galinhas do mod (roost).

**Comment by ArtpokeBr** [comment]
Isso talvez se dê pelo fato do Zawa na versão em questão do Modpack estar consumindo todo o Spawn. 
[ZAWASpawnConfigurations.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5659991/ZAWASpawnConfigurations.zip) substitua o arquivo dentro da pasta de configs do zawa e seja feliz, talvez funcione.

**Comment by Nuturn** [comment]
Com essa alteração aumento o Spawn das normais (vanilla) mas nada do mod, Fiquei sabendo hj da dimensão "terra dos dragões" lá elas dão Spawn, ficar lá até o próximo patch.
