### ISSUE TITLE
Bug com FTUltimine e Tiny Progression

### ISSUE THREAD

**Issue by hazeofc** [ArtpokeBr/Minecraft-Ultimato#154]
**Versão do Modpack:**
Minecraft Ultimato 1.12.2

**Descrição:**
Bom, eu estava minerando, usando o Wub Hammer, até eu quebrar um bloco usando o Vein Miner (FTUltimine), logo em seguida qualquer bloco que eu quebrava não dropava o item, e quando eu dropava qualquer item, ele sumia,  pra voltar ao normal eu tinha que reiniciar o meu Minecraft, e quando acontecia este bug, meu amigo tambem não conseguia dropar items e nem dropava os items dos blocos que ele quebrava. ("Host" do servidor era pelo Radmin)

**Passo a Passo para chegar no Problema (Opcional):**
Craftei Wub Hammer e quebrei uma pedra com o Vein Miner (FTUltimine)

**Screenshots:**
Um video mostrando o bug: https://youtu.be/FUO4Bi_ERD4

**Comment by cachorropp** [comment]
SIIIM!!! Nossa que coincidência, eu iria reportar o mesmo bug agora, e vejo você já falando. Só que eu estava em dúvida porquê eu acrescentei 2 mods no modpack: Thaumcraft e ThaumicJEI, aí como eles eram os unicos mods que não foram configurados, pensei que poderiam ser eles e tirei do meu server. Além disso o meu não é um server LAN, eu comprei um na reishost. Mas agora descobri o que é (tirei o thaumcraft a toa :C ), meu amigo estava utilizando o wub hammer e ele deve ter feito bugar as duas vezes.

**Comment by desconection** [comment]
Tive  o mesmo bug, mas não sabia a causa kkk, então era isso o tempo todo...

**Comment by ArtpokeBr** [comment]
bom, dá pra ver no vídeo inclusive que o método de quebrar 3x3 do Wub hammer é diferente dos hammers convencionais, então meu chute é que ao misturar com o Excavate, o server fica num loop eterno tentando calcular/fazer as quebras de blocos e isso se mantem por um bom tempo ferrando com o TPS e não deixando outras coisas funfarem e etc. vou remover o Wub hammer no próximo Patch ent.
