### ISSUE TITLE
Universal cable mekanism NBT no ProjectE

### ISSUE THREAD

**Issue by pgbezerra** [ArtpokeBr/Minecraft-Ultimato#156]
Quando você tem pegar outro cabo que não seja o Basic Universal Cable vc só tem o retorno do basic, isso fica mais visivel no energy condenser

![2020-12-08_13 14 08](https://user-images.githubusercontent.com/22059237/101515524-3478b600-395d-11eb-96e0-04645b41ce2c.png)
![2020-12-08_13 14 10](https://user-images.githubusercontent.com/22059237/101515530-36427980-395d-11eb-8907-f407b0ba3f00.png)
![2020-12-08_13 14 17](https://user-images.githubusercontent.com/22059237/101515535-36427980-395d-11eb-85f2-bfa1604bc964.png)
![2020-12-08_13 14 20](https://user-images.githubusercontent.com/22059237/101515537-36db1000-395d-11eb-9e60-106a8f6d99f0.png)
![2020-12-08_13 14 27](https://user-images.githubusercontent.com/22059237/101515540-3773a680-395d-11eb-9785-f0e5f0385b83.png)
![2020-12-08_13 14 29](https://user-images.githubusercontent.com/22059237/101515541-380c3d00-395d-11eb-813b-102a6d783f64.png)

**Comment by ArtpokeBr** [comment]
Isso é coisa de NBT, todos os itens do Mekanism tem seus tiers registrados apenas com um NBT diferente, enão a solução seria só eu remover o EMC do básico pra n ter confusão msm.
