### ISSUE TITLE
galinhas do mod @chikens não nascem

### ISSUE THREAD

**Issue by xandegp** [ArtpokeBr/Minecraft-Ultimato#158]
no meu mundo não esta nascendo nenhuma galinha desse mod so as normais
nem na dimenção do dragão
so esta gerando as galinhas do nether

**Comment by ArtpokeBr** [comment]
Como você me reporta que seu jogo não abre e logo depois que as galinhas não nascem???

**Comment by xandegp** [comment]
antes acontecia isso '-'

**Comment by xandegp** [comment]
ai que ja reportei os dois

**Comment by ArtpokeBr** [comment]
bom, deletei o outro. e relacionado ás galinhas, O Spawn delas ainda acontece, só está bem reduzido por conta do Zawa no overworld consumir muito as chances de spawn de Mobs. 
[ZAWASpawnConfigurations.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5660779/ZAWASpawnConfigurations.zip) substitua dentro da pasta de configs do Zawa e deve ajudar, se não funcionar, aguarde o próximo patch.

**Comment by xandegp** [comment]
como faço isso '-'?

**Comment by ArtpokeBr** [comment]
ué, não ficou óbvio? dentro da pasta de configs do Modpack vai ter outra pasta específica pro zawa, é só colocar lá o conteúdo dentro da Zip, substituindo e etc, isso vai remover o spawn dos Animais do Zawa e deve talvez aumentar o Spawn de outros Mobs.

**Comment by xandegp** [comment]
ataaaaaaaaaa, mas como resolvo o bug do mine não abrir? ' -'

**Comment by smurfvegetariano** [comment]
alterei o arquivo no servidor apenas e parece que melhorou... pelo menos já achei 2 galinhas, rs
