### ISSUE TITLE
Confito de item

### ISSUE THREAD

**Issue by MarlonBEP** [ArtpokeBr/Minecraft-Ultimato#159]
quando vai pegar o bafo do drag ele faz outro fraco com ender air bottle e nao tem como pegar Dragon's breath.

![image](https://user-images.githubusercontent.com/75400607/101517998-1fe9ed00-3960-11eb-91dc-765fe29f4dfc.png)
![image](https://user-images.githubusercontent.com/75400607/101518038-29735500-3960-11eb-936c-b4074e6565a7.png)
![image](https://user-images.githubusercontent.com/75400607/101518139-46a82380-3960-11eb-8fe4-987102b603fc.png)

**Comment by ArtpokeBr** [comment]
Isso é uma coisinha conhecida, pra tu ter certeza que está pegando dragons breath se tem que mirar no ar estando perto do bafo em si, se tu clicar mirando numa EndStone vai pegar o do botania sem querer. vou fechar por isso não é um problema específico do Modpack kk
