### ISSUE TITLE
Erro da textura do avaritia e draconic

### ISSUE THREAD

**Issue by Mcyuop** [ArtpokeBr/Minecraft-Ultimato#16]
https://prnt.sc/vrgtji  https://prnt.sc/vrgu5t eu estou zoando no criativo e achei isso

**Comment by ArtpokeBr** [comment]
Isso é por causa do Emoticons, ele acaba puxando a textura antiga para poder não bugar o 3D e etc, e como não posso tirar o Emoticons num futuro patch, é ixto :T

**Comment by Mcyuop** [comment]
ata obg :)
