### ISSUE TITLE
Bug Energy Upgrade

### ISSUE THREAD

**Issue by LeonardoBellotti** [ArtpokeBr/Minecraft-Ultimato#162]
Minecraft Ultimato-1.0.2.zip

Os Energy Upgrades do Mekanism não estão funcionando no Electrolytic Separator.
Estava testando alguns sistemas de geração de energia no criativo e achei esse bug.

A primeira print está sem nenhum upgrade e a segunda está com 8 upgrades de energia.
![image](https://user-images.githubusercontent.com/75697104/101535270-2b94de00-3977-11eb-9d71-5d8d9d731621.png)
![image](https://user-images.githubusercontent.com/75697104/101535362-4bc49d00-3977-11eb-95e0-2f6b07b6f70c.png)

**Comment by ArtpokeBr** [comment]
Estranho, pode ser que seja Bug interno do Mekanism, vou ver se ele teve algum Update corrigindo ou coisa parecida, se eles mesmos não tiverem corrigido creio que eu não possa fazer nada =/
