### ISSUE TITLE
Intro do modpack tocando ao usar o Magma Crucible

### ISSUE THREAD

**Issue by ShenzenKG79** [ArtpokeBr/Minecraft-Ultimato#163]
**Versão do Modpack:**
Minecraft Ultimato-1.0.2.zip, Curseforge.

**Descrição:**
Usar um Magma Crucible para derreter XP Solidificado faz o som da intro do modpack (Thanos dizendo "Inevitável" e estalando os dedos) rodar em loop até a máquina parar.

**Log:**
Eu não acho que o log ajudará muito nessa situação, mas não diz (opcional) do lado, então vou enviar igual.
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5662638/latest.log)

**Comment by ArtpokeBr** [comment]
Bug conhecido, já corrigido no próximo patch, fica tranquilo.

**Comment by ArtpokeBr** [comment]
vou fechar pra n ter confusão.
