### ISSUE TITLE
quero baixar o mod pack no launcher original do mine

### ISSUE THREAD

**Issue by JordoJNS** [ArtpokeBr/Minecraft-Ultimato#164]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Descrição:**
quero baixar esse mod pack para o launcher original, porem no laucher original so funciona se eu tiver as pastas mods, config e outras, nao quero usar launcher pirata pois sei q isso vai contra as diretrises da mojang, e nao quero registrar minha conta em launchers q pessam meu logim da mojang, entao por obsequio, poderia disponibilizar o dawnload dos arquivos nessessarios para usar esse mod pack no launcher original do minecraft

**Sugestão de Solução:**
caso nao possa postar o dowload dos arquivos para o launcher original no site da curse forge, poderia me mandar um email com linck privado ou algo assim, realmente quero muito jogar esse mod mas so jogo se for no launcher original

<img width="753" alt="mine riginal" src="https://user-images.githubusercontent.com/75704979/101556292-4d9f5800-3999-11eb-9238-23f61a2a8441.png">

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ShenzenKG79** [comment]
Eu não vejo onde está exatamente o problema. **"nao quero usar launcher pirata pois sei q isso vai contra as diretrises da mojang"** Baixar esse modpack é muito mas difícil para pirata, se é do MultiMC que você fala, ele não é um launcher pirata, você ainda precisa do Minecraft original para jogar usando ele.

Eu pessoalmente acho a maneira mais simples e fácil (porém pode ser difícil se sua internet é muito ruim) baixar o modpack pela Curseforge.

**Comment by ArtpokeBr** [comment]
o Launcher da Curse utiliza justamente o Launcher original de fundo pro jogo se isso é oq te preocupa. então instale normalmente pela curse que não deve te dar problemas :)

**Comment by JordoJNS** [comment]
eu nao quero usar curse forge pois sei q ele altera algumas config no launcher original, exp: se eu abro o mine pelo curse forge nao aparece as versoens q tenho instaladas no launcher original, serio por favor me ajudem so quero jogar esse mod mas nao quero usar outro launcher se nao o da mojang, curse forge launcher sei q se utiliza do original mas tbm sei q altera o mesmo de maneiras q nao gosto, por favor me ajudem so quero um linck com o dowload dos arquivos , tipo um zip com a pasta a config e o q for preciso pra rodar...

**Comment by JordoJNS** [comment]
so oq quero é um linck de dowload q tenha todas as pastas do mod em um arquivo zip...

**Comment by ArtpokeBr** [comment]
Jordo, para jogar Modpacks, você precisa usar um Launcher sem ser o da Mojang, PRA QUE que tu não quer que mexa nas versions? isso não altera em nada sua experiência e não usar o Launcher correto só vai se prejudicial pra tu! eu não posso disponibilizar os Mods sem ser pela curse pelo simples fato de que disponibilizando por fora eu não dou créditos aos autores originais! o que é muito pior do que você simplesmente ficar aleatóriamente não querendo usar o Launcher certo kkkk

**Comment by JordoJNS** [comment]
ta ok eu vou utilizar a curse forge mas antes quero uma info, onde ficam salvos as pastas de mod desse launcher?? um amigo meu disse q testou e q os mods nao ficam nem sequer na appdata, é q tem alguns mods q desejo retirar e outros q desejo acrecentar, exp, o de galinhas eu quero tirar e quero por um de better foliage, mas se a pasta mods nao fica na appdata tal qual meu amigo dis entao onde ela fica??

**Comment by ShenzenKG79** [comment]
Após instalar o modpack na curseforge e clicar play ele abrirá o launcher original, então clique em **instantes** acima e daí ao lado de uma fornalha escrito **MC Ultimato** terá um símbolo de pasta, isso abrirá a pasta do modpack.

**Comment by JordoJNS** [comment]
ok obrigado vou tentar
