### ISSUE TITLE
Como crio um server deste modpack

### ISSUE THREAD

**Issue by L4ST23** [ArtpokeBr/Minecraft-Ultimato#168]
Eu tenho um server de ftb que dei download da pasta do servidor ja criada a partir deste site e cria agora saber se consigo fazer o mesmo para o Mc Ultimato ou se tenho de criar o servidor de raiz. Obrigado

**Comment by L4ST23** [comment]
Eu tenho um server de ftb que dei download da pasta do servidor ja criada a partir deste site e cria agora saber se consigo fazer o mesmo para o Mc Ultimato ou se tenho de criar o servidor de raiz. Obrigado

**Comment by ArtpokeBr** [comment]
vem cá, por que tu fez o report não substituiu o texto? se sabe que ele é feito pra isso né? leia da próxima vez...

**Comment by ArtpokeBr** [comment]
e no caso do Ultimato, em questão de servers atualmente de fato está complicado e bem manual para se fazer um server, mas os arquivos de servidor devem sair assim que o próximo patch de correções for lançado, então, só aguardar.

**Comment by L4ST23** [comment]
quando e o proximo patch de correções?

**Comment by L4ST23** [comment]
Tem algum video de como fazer o server manual para este modpack?

**Comment by ArtpokeBr** [comment]
o Patch de correções deve sair até o fim do mês.
