### ISSUE TITLE
problemas com TinyProgressions

### ISSUE THREAD

**Issue by FukaseAlecrim** [ArtpokeBr/Minecraft-Ultimato#171]
eu estava jogando na versão 1.0.2, estava minerando com o Hammer de wub gem do TinnyProgressions e sem querer ativei o vein miner (que eu tinha colocado naqueles botões extras do mouse) e aparece uma mensagem que o TinyProgressions deu problema, e nenhum boco que eu quebrava (tanto com o Hammer do TinyProgressions quanto com qualquer ferramenta) não dropava ou ia para o meu inventario

**Comment by ArtpokeBr** [comment]
o Hammer vai ser removido no próximo Patch, tem um bugzinho com ele mesmo. então apenas não o use para evitar esse tipo de problema :)

**Comment by ArtpokeBr** [comment]
vou fechar pq já foi reportado.
