### ISSUE TITLE
como q eu aloco mais memoria ran do mod pack??

### ISSUE THREAD

**Issue by JordoJNS** [ArtpokeBr/Minecraft-Ultimato#172]
**Versão do Modpack:**
1.0.2

**Descrição:**
como faço pra alocar 8gb de ram no mod pack??

**Screenshots:**
<img width="346" alt="print" src="https://user-images.githubusercontent.com/75704979/101667580-41b1a580-3a2e-11eb-941a-cf4b47e02c2d.png">

**Comment by ArtpokeBr** [comment]
Cara, por favor usa um Launcher decente kkkk o padrão do Mine é uma porcaria até pra alocar RAM. mas normalmente é logo depois do xmx kkk

**Comment by JordoJNS** [comment]
sim estou usando o curse forge mas o sistema de colocar ram ta diferente,  mandei uma print de como esta a ram e nao sei como faço pra alterar...

**Comment by JordoJNS** [comment]
tipo la ta em mb pelo q percebi e nao sei quantos mb tem em 8gb...

**Comment by ArtpokeBr** [comment]
na curse, é só ir nas configurações da Instância e especificar o quanto quer.
