### ISSUE TITLE
Jogo está crashando aleatoriamente

### ISSUE THREAD

**Issue by Felipemm21** [ArtpokeBr/Minecraft-Ultimato#174]
Depois de um tempo jogando no modpack (jogo rodando liso a 50 fps sem travar) o minecraft para de responder e eu tenho que fechar o app, meu amigo tambem esta jogando o modpack e me falou que com ele tambem esta acontecendo, acredito que nao seja um problema do computador pq aloquei 7 gb de ram pro mine, sabe se tem solução? (alias parabens pelo modpack pq esta sensacional)

**Comment by ArtpokeBr** [comment]
7GB é muito pro Modpack, aloca 5 e pouco ou 6GB.

**Comment by Felipemm21** [comment]
Eu tinha deixado 5.8GB quando comecei a jogar e ja tava dando esse problema, ai aumentei pq achei q tava crashando pq tinha pouca ram mas nao mudou muita coisa

**Comment by ArtpokeBr** [comment]
Bom, dá uma aguardada, deve em breve sair um Patch que terá algumas correções e deve aliviar isso tudo.
