### ISSUE TITLE
Meu mc ultimato nao incia, ele para na tela de carregamento de mods

### ISSUE THREAD

**Issue by Senhoreli** [ArtpokeBr/Minecraft-Ultimato#175]
**Versão do Modpack:**
1.0.2

**Descrição:**
Quando eu incio meu modpack pelo forge, ele abre o maine launcher, ai selecio  meu mc ultimato e quando ele esta carregando os mods, ele para e mostra uma mensagem de erro falando de algo desconhecido.   Obs: estou com 5gb para inciar o ultimato

**Sugestão de Solução:**
Nao entendo de mods, sorry. 

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5668515/latest.log)
[crash-2020-12-09_15.48.48-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5668516/crash-2020-12-09_15.48.48-client.txt)
[crash-2020-12-09_18.15.19-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5668517/crash-2020-12-09_18.15.19-client.txt)

**Screenshots:**

![image](https://user-images.githubusercontent.com/75756418/101683699-12a62e80-3a44-11eb-8cd9-c5c19cd5ba2f.png)
Achei que esse print poderia ser util
![image](https://user-images.githubusercontent.com/75756418/101684193-ca3b4080-3a44-11eb-9e1b-32eb8680825b.png)

**Comment by pgbezerra** [comment]
StitcherException, problemas de carregamento com o GalactCraftCore, seu jogo esta apenas com minimo de memoria abaixo do requerimento

Valide também se seu processador 2x Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz aguenta o modpack e se vc tem o minimo de memoria disponivel pra JVM

**Comment by ArtpokeBr** [comment]
Obrigado pela ajuga Pg.

**Comment by ArtpokeBr** [comment]
e sim pelo visto tem algo haver com a alocação de Memória. tenta subir um pouquinho pra ver se resolve, principalmente na curse, as vezes tu coloca lá 5 mas ele puxa só 4 e pouco então confira.

**Comment by Senhoreli** [comment]
Tem como eu tirar um mod específico do modpack?

**Comment by ArtpokeBr** [comment]
não tem necessidade, apenas aumente um pouco a memória Alocada que deve resolver.

**Comment by lucasqof1009** [comment]
mano o meu apareceu isso tbm
o que eu faço por favor me ajuda 
desde que o modpack foi criado eu tento resolver isso até hoje

**Comment by lucasqof1009** [comment]
![Captura de Tela (164)](https://user-images.githubusercontent.com/86856712/124333614-1da0e780-db6b-11eb-9765-cf4dca0fdb26.png)

**Comment by ArtpokeBr** [comment]
Só a print disso n adianta, me manda esse arquivo TXT que ele justamente se referencia. assim dá pra saber o motivo do crash ao iniciar o Modpack.

**Comment by lucasqof1009** [comment]
https://paste.dimdev.org/exunofayuf.mccrash

**Comment by lucasqof1009** [comment]
Achou o erro ?

**Comment by ArtpokeBr** [comment]
se tá usando algum Texture Pack? e outra coisa, seu jogo é oficial né?

**Comment by lucasqof1009** [comment]
não estou usando nenhum pacote de textura, sim meu jogo é oficial

**Comment by ArtpokeBr** [comment]
Quanto de RAM Alocada?

**Comment by ArtpokeBr** [comment]
na pior das hipóteses, se pode tenta reinstalar, pois aparentemente foi um Erro de textura... está com o Optifine instalado? se tiver tenta abrir sem ele.

**Comment by lucasqof1009** [comment]
sim eu tava com o optifine na pasta de mods do modpack, então eu reinstalo o modpack e não coloco o optifine ? é isso ?

**Comment by ArtpokeBr** [comment]
primeiro tenta abrir o jogo sem o Optifine pra ver se muda em algo, se não funcionar, tenta reinstalar o Modpack.

**Comment by lucasqof1009** [comment]
eu reinstalei o modpcack sem o optifine e entrei aí apareceu a mesma coisa  do erro desconhecido

**Comment by lucasqof1009** [comment]
AH E EU ESQUECI, EU ALOQUEI 6GB DE RAM

**Comment by lucasqof1009** [comment]
vou tentar no minecraft pirata

**Comment by ArtpokeBr** [comment]
> fiz do jeito que vc pediu mas não deu certo
> Tem alguma sugestão do que eu posso fazer ?

mas foi o mesmo erro?

**Comment by lucasqof1009** [comment]
sim foi o mesmo erro

**Comment by ArtpokeBr** [comment]
tenta ver se teu java está atualizado ou, atualize o thermal expansion, que é quem está dando o erro afinal de contas.

**Comment by lucasqof1009** [comment]
mano o meu java está atualizado
Mais eu n entendi esse negócio de expansão térmica kkk
Se vc poder me explicar como posso fazer isso ?

**Comment by lucasqof1009** [comment]
mais para atualizar ele eu tenho que ir lá no site do curseforge né ?
mais quando eu vou lá ele está na mesma versão do thermal expansion do modpack

**Comment by lucasqof1009** [comment]
EU TENTEI TIRAR O THERMAL EXPANSION, AÍ EU ACHEI Q IA DÁ CERTO MAS NÃO DEU, EU ESTOU COM DÚVIDA PARA ATUALIZAR ESSE MOD POIS A VERSÃO DELE LÁ NO SITE DO CURSEFORGE É A MESMA DO MODPACK,ELE JÁ ESTA NA VERSÃO MAIS ATUALIZADA, AÍ FICA A DÚVIDA

**Comment by ArtpokeBr** [comment]
Olha, não sei exatamente o que há de errado ai no seu PC então, pois o Erro não é de memória é simplesmente de carregamento de textura, o que é estranho... e uma dica, NÃO remova um Mod de um Modpack já pronto, literalmente removendo o Thermal o Modpack simplesmente não funcionaria ;p

**Comment by lucasqof1009** [comment]
ok eu n tirei o termal
mais eu n sei pq o erro é de textura pq eu n estou usando nenhum pacote de textura

**Comment by lucasqof1009** [comment]
e tem alguma coisa que eu possa fazer para ajeitar esse carregamento de textura ?

**Comment by Leozinnn7777** [comment]
Olha não sou um especialista mas acho q Você poderia reiniciar a máquina, o modpack ou se não funcionar reinstale o modpack

**Comment by lucasqof1009** [comment]
Artpokebr vou tentar pelo multimc depois 
Tem alguma diferença ?

**Comment by ArtpokeBr** [comment]
vou fechar já que por enquanto não tem solução, mas pelo MultiMC talvez rode diferente, pode tentar.

**Comment by lucasqof1009** [comment]
ok

**Comment by lucasqof1009** [comment]
mano o multimc está bugado, eu coloco o meu email e senha correto e dá errado
Artpokebr, quando vc achar a solução certa por favor fala aqui
vou ficar olhando todos os dias

**Comment by Leozinnn7777** [comment]
Bem acho que é a sua versão do Windows se for o Windows 95, 98, 2000, Melenium, XP, Vista ou 7 atualize para o Windows 10 ou o 8 deve ser isso.

**Comment by lucasqof1009** [comment]
o meu é o windows 10

**Comment by Leozinnn7777** [comment]
> o meu é o windows 10 pro versão 21H1
> 
É que pelas screenshots parece um 2000 mas ok deve ser talvez um corrompimento no arquivo

**Comment by Pedrinhojrgames** [comment]
opa eu queria informa-lo que eu também estou tendo o mesmo erro
Alguém já achou a solução deste problema

**Comment by Leozinnn7777** [comment]
> opa eu queria informa-lo que eu também estou tendo o mesmo erro
> 
> Alguém já achou a solução deste problema ?

Ok tentaremos resolver mas para isso abra um novo issue e não, não resolvemos
