### ISSUE TITLE
Problema do portal dos dragões

### ISSUE THREAD

**Issue by Diiogooh** [ArtpokeBr/Minecraft-Ultimato#177]
**Versão do Modpack:**
Estou jogando no Minecraft Ultimato na versão 1.12.2.

**Descrição:**
Tenho um problema, criei um server de mc Ultimato pra jogar com amigos e quando entro no portal dos dragões aquilo faz uma plataforma como se fosse skyfactory 4.

**Sugestão de Solução:**
Preciso de um tutorial que faça com que configure o portal dos dragões num server.

**Passo a Passo para chegar no Problema (Opcional):**
Fui fazer o portal dos dragões e quando entro nele reparo que estou numa plataforma de terracota

**Screenshots:**
![2020-12-09_21 54 51](https://user-images.githubusercontent.com/75759196/101693786-092fbd00-3a6a-11eb-8166-96f0290719bf.png)

**Comment by ArtpokeBr** [comment]
Ao criar um servidor você PRECISA colocar nas generator settings dele o gerador do Topography, pois se não por, não vai funcionar. tenta colocar isso aqui logo depois do generator settings sem espaço e recria o Mapa {"Topography-Preset":"UltimatoOverworld"}
