### ISSUE TITLE
Crafting mostrado no JEI do Slimey Generator não esta correta

### ISSUE THREAD

**Issue by GamesRevolution** [ArtpokeBr/Minecraft-Ultimato#178]
**Versão do Modpack:**
1.0.2

**Descrição:**
O crafting que o JEI mostra do Slimy Generator do Extra Utilities não funciona

**Passo a Passo para chegar no Problema (Opcional):**
Eu coloquei os item do jeito que o JEI mostrou na minha Crafting Grid do refined Storage e não fez nenhum crafting, mas se colocado um Slime Block no meio da crafting grid, você poderá craftalo de novo

**Screenshots:**
![2020-12-09_19 50 12](https://user-images.githubusercontent.com/75512432/101693566-9534eb00-3a50-11eb-9cc3-29b4bdf37f55.png)
![2020-12-09_19 50 03](https://user-images.githubusercontent.com/75512432/101693562-936b2780-3a50-11eb-9ab6-55a482e7f556.png)
![2020-12-09_19 58 11](https://user-images.githubusercontent.com/75512432/101693557-91a16400-3a50-11eb-91af-9cb800487cc6.png)

**Comment by ArtpokeBr** [comment]
Bug estranho do JEI. vou ver dps.
