### ISSUE TITLE
Meu Minecraft falha ao inicializar

### ISSUE THREAD

**Issue by yHoleezp** [ArtpokeBr/Minecraft-Ultimato#179]
Eu abro o Minecraft pelo MultiMC, e da erro ao inicializar, ele até inicializa, só que depois da erro do IndustrialCraft 2.
Por favor, se alguém me ajudar agradeço!
![image](https://user-images.githubusercontent.com/75759925/101696718-49387500-3a55-11eb-8f76-7a5a5274bf9d.png)

**Comment by ArtpokeBr** [comment]
Aloca mais RAM, tá faltando.

**Comment by yHoleezp** [comment]
Mais da pra alocar RAM pelo MultiMC?

**Comment by yHoleezp** [comment]
Art, Obg!!!!! Aloquei mais RAM e agr foiiii <3!!! VLWW
