### ISSUE TITLE
Problemas na sessão 

### ISSUE THREAD

**Issue by ReaperHimura** [ArtpokeBr/Minecraft-Ultimato#180]
Sempre que tento entrar, diz que a sessão não esta OK, o qu eme impede de jogar, gostaria de saber como resolver 

![sessão](https://user-images.githubusercontent.com/75766184/101712313-0043e900-3a74-11eb-8157-951314b682ef.jpg)

**Comment by ArtpokeBr** [comment]
isso é erro do MultiMC kkk n sei resolver não. vou fechar pq n é relacionado ao Modpack. qualquer coisa pergunte no Discord.
