### ISSUE TITLE
Mob Crusher do Industrial Foregoing dropando +50 cabeças de mobs

### ISSUE THREAD

**Issue by hazeofc** [ArtpokeBr/Minecraft-Ultimato#181]
**Versão do Modpack:**
Minecraft Ultimato 1.12.2

**Descrição:**
Bom, eu fui fazer uma farm de mobs no Minecraft Ultimato e acabei me deparando com esse bug, eu estava usando o Mob Crusher do Industrial Foregoing, e qualquer mob que o Crusher matava ele dropava 50 cabeças do mob ou até mais..

**Passo a Passo para chegar no Problema (Opcional):**
Eu cavei uma area para os mobs nascerem, usei o Drop Of Evil e o Mob Crusher do Industrial Foregoing para matar eles e conseguir Mob Essence..

**Screenshots:**
![image](https://user-images.githubusercontent.com/75665499/101728771-bbc94500-3a95-11eb-83f3-5af8ae7690f8.png)
![image](https://user-images.githubusercontent.com/75665499/101728793-c84d9d80-3a95-11eb-92c8-36db048cec6d.png)

**Comment by ArtpokeBr** [comment]
por algum motivo Mobs estão droppando cabeças demais no Ultimato, o foi feito pra corrigir isso foi remover o EMC de todas as cabeças.
