### ISSUE TITLE
Conflitos com receitas no Minecraft Ultimato

### ISSUE THREAD

**Issue by hazeofc** [ArtpokeBr/Minecraft-Ultimato#182]
**Versão do Modpack:**
Minecraft Ultimato 1.12.2

**Descrição:**
Bom, tem algumas receitas que eu encontrei que estão com conflitos no modpack, uma delas é para craftar a Gold Gear, Iron Gear e o bloco Tyrian. Por enquanto esse são as unicas receitas que eu vi com conflitos, devem ter mais que eu não vi eu acho. Mas não sei se foi algum erro meu ao instalar o modpack ou se é algum bug mesmo.. 

**Screenshots:**
Tyrian: 
![image](https://user-images.githubusercontent.com/75665499/101731640-aefb2000-3a9a-11eb-9f2f-0ae5a0df29e8.png)
![image](https://user-images.githubusercontent.com/75665499/101731656-b6222e00-3a9a-11eb-9312-88041ea28756.png)

Iron Gear:
![image](https://user-images.githubusercontent.com/75665499/101731688-c0dcc300-3a9a-11eb-8796-202f50ea2955.png)
![image](https://user-images.githubusercontent.com/75665499/101731705-ca662b00-3a9a-11eb-84c9-cc53322e99bd.png)

Gold Gear:
![image](https://user-images.githubusercontent.com/75665499/101731753-df42be80-3a9a-11eb-9c12-1e2db42e16c9.png)
![image](https://user-images.githubusercontent.com/75665499/101731734-d81bb080-3a9a-11eb-95a1-91d812cd0c89.png)

**Comment by ArtpokeBr** [comment]
As Engrenagens eu já tava sabendo,mas o Tyrian é novidade...

**Comment by jvfd3** [comment]
Eu ia postar sobre a mesma coisa, ainda bem que vi esse antes. Deve ser muito chato pra você ficar recebendo um monte de report repetido.
