### ISSUE TITLE
quando abre aparece um aviso /foto em anexo/

### ISSUE THREAD

**Issue by xablaupk** [ArtpokeBr/Minecraft-Ultimato#183]
![erro](https://user-images.githubusercontent.com/75790067/101773498-9c4d0f00-3acb-11eb-90f3-143cf8fe75f9.jpeg)

**Comment by xablaupk** [comment]
desculpa não tinha visto que vc já tinha resolvido isso

**Comment by ArtpokeBr** [comment]
kkkk eu resolvi mas nem te respondi? Ok né kkk
