### ISSUE TITLE
Problema com Simple Storage

### ISSUE THREAD

**Issue by FukaseAlecrim** [ArtpokeBr/Minecraft-Ultimato#184]
Versão do Modpack: 1.0.2

Descrição: Os itens aparecem duplicados dentro do sistema de armazenamento do Simple Storage

**Comment by ArtpokeBr** [comment]
Prints? e na verdade provavelmente isso é um Bug do Simple Storage em si..

**Comment by aladekom** [comment]
> Versão do Modpack: 1.0.2
> 
> Descrição: Os itens aparecem duplicados dentro do sistema de armazenamento do Simple Storage

é apenas apertar shift que para.... eles mostram o numero arredondado

**Comment by zNinjaFrosTz** [comment]
isso nao é um bug, é pq tem um 2 cabos conectando no mesmo bau, tenta usar uma wrench no cabo pra tirar a conexão do bau.
