### ISSUE TITLE
Conflito de spawn de mobs e dungeons

### ISSUE THREAD

**Issue by Marcinho63** [ArtpokeBr/Minecraft-Ultimato#185]
**Versão do Modpack:**
1.0.2.

**Descrição:**
Muitas criaturas e construções estão deixando de spawnar devido a algum conflito, estive jogando já a quase uma semana e reparei que criaturas do Ice and Fire não aparecem, apenas ciclope, hippocampus, hippogrifo e stymphalian bird e sea serpent estão aparecendo, também a dimensão dos insetos só da spawn no flautista dos ratos, os ninhos de Dragon mounts também não foram encontrados em lugar algum no meu mundo, assim como vilas.

**Sugestão de Solução:**
Imagino que exista um mod ou comando ativo que impede o spawn de vilas, assim as outras dungeons de mods que talvez tenham sido feitas usando o mesmo codigo de spawn de vila também sejam afetadas. já os spawns de mobs eu não tenho ideia de algum possivel motivo.

**Passo a Passo para chegar no Problema (Opcional):**
Bom, basicamente eu estive jogando e cheguei na parte "quero dragões, quero visitar novas dimensões" como eu já tinha uma armadura para voar eu fui e voei diversos xxxx de distância e nada dos devidos spawns do problema acima.

**Crash Log:**
A log é extremamente grande pra enviar aqui, posso enviar no discord se quiser Shizukesa#6593

**Comment by ArtpokeBr** [comment]
Os Dragões e suas respecitvas estruturas do Ice And Fire só são geradas na dimensão deles. e no caso do DragonMounts, as estruturas foram desativadas então para obter os ovos é só converter algum do Ice usando a chisel.

**Comment by Marcinho63** [comment]
Certo, mas e os insetos do Erebus?

**Comment by ArtpokeBr** [comment]
provavelmente por causa do Zawa, pelo menos nas dimensões normais o Zawa tava comendo as chance de Spawn de outros Mods, e isso já foi corrigido pq no próximo patch os bixo do Zawa não vão mais gerar no Mapa.

**Comment by Marcinho63** [comment]
Receio não ser o Zawa dessa vez, pois eu andei por todos os biomas dessa dimensão e só vi Ratos e Flautistas, apenas.
