### ISSUE TITLE
Items do IndustrialCraf não tem nome!

### ISSUE THREAD

**Issue by CrJoga** [ArtpokeBr/Minecraft-Ultimato#189]
**Nota**: Items do IndustrialCraf não tem nome!

**Versão do Modpack:**
1.0.2

**Descrição:**
Para poder pesquesar alguma coisa do IndustrialCraft para ver a riceita tem que ser por @IndustrialCraft

**Screenshots:**
![2020-12-11_04 19 13](https://user-images.githubusercontent.com/75815941/101861725-acff9280-3b68-11eb-80b4-3f5b7cc5c9e8.png)

**Comment by ArtpokeBr** [comment]
Esquisito, não lembro deles estarem sem nome aqui não...
