### ISSUE TITLE
Stronghold não gerada

### ISSUE THREAD

**Issue by leofoda** [ArtpokeBr/Minecraft-Ultimato#19]
Nada muito a acrescentar, a stronghold nao foi gerada, dei /locate e tp, mas mesmo assim nao foi

**Comment by ArtpokeBr** [comment]
Stronghold não gerou? Poderia acrescentar uma Print por favor? só pra conferir as Cords e afins.

**Comment by leofoda** [comment]
> Stronghold não gerou? Poderia acrescentar uma Print por favor? só pra conferir as Cords e afins.

Problema resolvido, era só burrada minha kkkkk

Mas entrando em outro tópico, no the end está spawnando muitos endermans mutantes. demorei uns 13 minutos pra matar o ender dragon sendo que com os meus item demoraria uns 2 minutos. Tirei uma print mas nao salvou, enfim tinha 6 enderman mutante, com eles dao cegueira, spawnando endermans invisiveis e dando um knockback de uns 50 blocos.

**Comment by ArtpokeBr** [comment]
Por favor, se é esse o caso, dá uma analisadazinha nisso, e faz um report separado com prints falando sobre o spawn excessivo de Endermans mutantes ent, que ai eu já me organizo. vou fechar esse probleminha aqui :)
