### ISSUE TITLE
Portal do Fim Não Gera !

### ISSUE THREAD

**Issue by XpGameOfi** [ArtpokeBr/Minecraft-Ultimato#190]
Estou com um problema que o portal do fim não esta gerando em no mundo normal nem no mundo dos dragoes !
já resetei chucks e nada.
tem alguma solução ?
ou algum outro modo de ir pro the ender ?

**Comment by ArtpokeBr** [comment]
não está gerando mesmo? tentou usar um /locate?

**Comment by XpGameOfi** [comment]
O comando não!
Mais , Minecraft tem somente 1 portão do fim , eu acredito kkkk

Eu achei o portal na sala do portal tem nada nada, a asala está toda limpa.
Resetei a chunck um monte de vez e nada do portal aparece.
A pérola só fim, sempre indica pra mesma sala e quebra sempre no mesmo lugar.
Anoite posto prints
