### ISSUE TITLE
Não da para conseguir a cabeça do enderman no survival

### ISSUE THREAD

**Issue by Progamadormirim** [ArtpokeBr/Minecraft-Ultimato#192]
**Versão do Modpack:**
1.0.2

**Descrição:**
O uso da Ender, espada do Ender IO, com todos os upgrades, espadas do Tinkers com Beheadind V e Looting, espadas do Vanilla com Looting, nada, não há nem receita de drop da cabeça do enderman no JEI, não tem como conseguir a cabeça do enderman no survival, eu procurei nos arquivos para achar a configuração de drop mas não achei nem mesmo o block_enderman_skull nos arquivos do Ender IO.

**Sugestão de Solução:**
¯\_(ツ)_/¯

**Passo a Passo para chegar no Problema (Opcional):**
Erro de sistema.

**Crash Log:**
Não é crash

**Screenshots:**
Não é problema visual

**Comment by ArtpokeBr** [comment]
as cabeças estão meio bugadas mesmo, mata com um Mobcrusher um enderman pra tu ver ent. kkk
