### ISSUE TITLE
caída muito grande de fps

### ISSUE THREAD

**Issue by aladekom** [ArtpokeBr/Minecraft-Ultimato#193]
Quando abri o modpack pela primeira vez era impossivel de jogar... ficava com 30 de fps e caia pra 0
pensei que era o mod de movimentação, então tireio o mod emotes. quando abri denovo melhorou um pouco fiquei com uns 50 porem do nada cai pra uns 0 a 10
se pudesse me ajudar seria muito bom

**Comment by ArtpokeBr** [comment]
Quanto de RAM Alocada?

**Comment by aladekom** [comment]
6480= 6 de ram

**Comment by ArtpokeBr** [comment]
tá com o Optifine instalado? tenta talvea abaixar pra 5 e pouco também.

**Comment by aladekom** [comment]
é pra deixar com 5 de ram e botar optifine?
