### ISSUE TITLE
O mod Topography esta dando erro ao eu tentar entrar no meu mundo

### ISSUE THREAD

**Issue by titanjunior54** [ArtpokeBr/Minecraft-Ultimato#194]
Eu não estou conseguindo mais entrar no meu mundo, esse mod fica dando erro.
![Captura de Tela (15)](https://user-images.githubusercontent.com/75854531/101935769-53c24e00-3bbe-11eb-9d85-515674d7f7dc.png)

**Comment by ArtpokeBr** [comment]
mandar só essa tela não adianta, manda o Crash mais recente.

**Comment by titanjunior54** [comment]
Onde eu encontro o Crash mais recente? se for no botão Get link eu nn consigo usa-lo, quando eu clico nele ele não faz nada, apenas trava um pouco o mine e não acontece nada.

**Comment by titanjunior54** [comment]
esta aqui o Crash mais recente:
![Captura de Tela (26)](https://user-images.githubusercontent.com/75854531/101943096-4eb6cc00-3bc9-11eb-9887-2a97e41ae2d9.png)
![Captura de Tela (17)](https://user-images.githubusercontent.com/75854531/101943099-4fe7f900-3bc9-11eb-8474-82ada43fa909.png)
![Captura de Tela (18)](https://user-images.githubusercontent.com/75854531/101943100-50808f80-3bc9-11eb-853f-3c8dde637eb3.png)
![Captura de Tela (19)](https://user-images.githubusercontent.com/75854531/101943103-50808f80-3bc9-11eb-80fd-e89de693dc9b.png)
![Captura de Tela (24)](https://user-images.githubusercontent.com/75854531/101943105-51192600-3bc9-11eb-9e02-0d057ce46c6e.png)
![Captura de Tela (25)](https://user-images.githubusercontent.com/75854531/101943108-51b1bc80-3bc9-11eb-93b4-9722f4378886.png)

**Comment by ArtpokeBr** [comment]
tu tá tentando entrar em um Server ou é singleplayer mesmo?

**Comment by titanjunior54** [comment]
No singleplayer

**Comment by titanjunior54** [comment]
Eu tava jogando de boa hoje, ai eu sai do jogo e quando voltei deu esse erro.

**Comment by titanjunior54** [comment]
to jogando faz 3 dias
