### ISSUE TITLE
As armuduras do tinkeres e a do galacticraft (foram as que eu testei) estão com bugs visuais por favor arrume!!

### ISSUE THREAD

**Issue by ruan12354** [ArtpokeBr/Minecraft-Ultimato#195]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
Minecraft Ultimato-1.0.2.zip

**Descrição:**
As armuduras do tinkeres e a do galacticraft (foram as que eu testei) estão com bugs visuais por favor arrume!! Ao colocar a armudura ela não fica com a aparência normal fica sem textura.

**Sugestão de Solução:**
Infelizmente não sei como resolver

**Passo a Passo para chegar no Problema (Opcional):**
Eu construi a armadura do tinkeres a Demonic e quando fui vesti-la ela estava com a textura toda bugada

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5680747/latest.log)

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.
![image](https://user-images.githubusercontent.com/75855177/101936824-ce3f9d80-3bbf-11eb-87c5-e59bba1f9977.png)
![image](https://user-images.githubusercontent.com/75855177/101936848-da2b5f80-3bbf-11eb-9fd9-8ee756362017.png)
![image](https://user-images.githubusercontent.com/75855177/101936882-e4e5f480-3bbf-11eb-8e7a-f7835336dbf4.png)

**Comment by ruan12354** [comment]
![image](https://user-images.githubusercontent.com/75855177/101936968-0050ff80-3bc0-11eb-84d8-5f77d35c924b.png)

**Comment by ruan12354** [comment]
![image](https://user-images.githubusercontent.com/75855177/101937006-0ba42b00-3bc0-11eb-925b-32483187fbfb.png)

**Comment by ruan12354** [comment]
![image](https://user-images.githubusercontent.com/75855177/101937049-1e1e6480-3bc0-11eb-999e-57f9d3c73395.png)

**Comment by ArtpokeBr** [comment]
tá com as animações padrões do Emoticons desativadas? elas que normalmente causam esses BO's e no próximo patch por isso justamente que elas vão estar desativadas.

**Comment by ruan12354** [comment]
Como desativa amigo?

**Comment by ArtpokeBr** [comment]
nas configs do Emoticons, vai ter um "disable animations" ou coisa do tipo, pode desativar pq ele n vai remover as funcionalidades de apertar uma tecla e seu personagem dançar e etc, ele só move as animações mais normais como de andar e etc.
