### ISSUE TITLE
As configurações estão ilegíveis/cortadas

### ISSUE THREAD

**Issue by Danivain123** [ArtpokeBr/Minecraft-Ultimato#198]
![bugazera](https://user-images.githubusercontent.com/73195607/101949235-0a7bf980-3bd2-11eb-8263-9964619be4f3.png)

**Comment by Danivain123** [comment]
alguma ajuda?

**Comment by ArtpokeBr** [comment]
isso ai é por conta do tamanho da sua Hud, coloca ela menor para que possa ajeitar as Configs e depois volte ao normal. isso infelizmente não é um problema que eu sequer possa consertar kkk isso é do própio mine. vou fechar.
