### ISSUE TITLE
Ploblema no mod Schematica

### ISSUE THREAD

**Issue by C1n0x** [ArtpokeBr/Minecraft-Ultimato#199]
**Versão do Modpack:**
1.0.2

Descrição:
Quando tiro schematica de alguma construção ou estrutura multi bloco troca os blocos

Passo a Passo:
Eu estava fazendo o reator e a turbina do Extreme Reactors, e quando fui tirar a schematica para passar pro outro mapa vi que os blocos estavão trocados

Era para ser isso
![Era Pra ser isso](https://user-images.githubusercontent.com/75707808/101952184-00102e80-3bd7-11eb-8fd2-f9c840fe389b.png)

Mas virou isso
![Mas virou isso](https://user-images.githubusercontent.com/75707808/101952213-09010000-3bd7-11eb-8364-5ddb39faef35.png)

**Comment by ArtpokeBr** [comment]
Isso deve ser Bug do Schematica, infelizmente não posso fazer nada :( vou fechar.
