### ISSUE TITLE
Crash com o Topography.

### ISSUE THREAD

**Issue by iOkamii** [ArtpokeBr/Minecraft-Ultimato#2]
Fui criar um mundo e o Topography crashou.
Eu retirei alguns mods (Tech Guns, Dragon Mounts e umas dimensões)
Segue o crash log ->

[crash-2020-11-24_21.24.13-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5593607/crash-2020-11-24_21.24.13-client.txt)

**Comment by iOkamii** [comment]
Crash no Pastebin ->
https://pastebin.com/R8xAFBbw

**Comment by ArtpokeBr** [comment]
Esse, "umas dimensões" que tu tirou foi oq? o Crash foi relacionado ao GalacticCraft também. não recomendo mexer muito na Modlist sem necessidade, está rodando o Pack do jeito que está? pra que querer tirar mods? kkk

**Comment by iOkamii** [comment]
Atum, Erebus, GalactCraft e Aether

**Comment by ArtpokeBr** [comment]
Este problema provavelmente foi por que tirou Mods, não tire se não precisar ;p vou fechar o problema...
