### ISSUE TITLE
Minecraft não iniciou

### ISSUE THREAD

**Issue by C3sarB1ts** [ArtpokeBr/Minecraft-Ultimato#20]
@ArtpokeBr dois mods não deixaram meu mine iniciar. Anexo aqui o crash report:

[crash-2020-11-27_22.05.05-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5609902/crash-2020-11-27_22.05.05-client.txt)

**Comment by Christtiann** [comment]
@C3sarB1ts seu minecraft é original???

**Comment by ArtpokeBr** [comment]
Deu um erro que não entendi com o EnderStorage, por aonde tu baixou o Modpack? como que tá a instalação ai? to achando que se cometeu algum erro nessa parte.

**Comment by C3sarB1ts** [comment]
> @C3sarB1ts seu minecraft é original???

Nop

**Comment by C3sarB1ts** [comment]
> Deu um erro que não entendi com o EnderStorage, por aonde tu baixou o Modpack? como que tá a instalação ai? to achando que se cometeu algum erro nessa parte.

Eu baixei direto pelo TLauncher, vou ver se baixar o modpack pelo curseforge e colocar manualmente na pasta mods funciona

**Comment by C3sarB1ts** [comment]
> > Deu um erro que não entendi com o EnderStorage, por aonde tu baixou o Modpack? como que tá a instalação ai? to achando que se cometeu algum erro nessa parte.
> 
> Eu baixei direto pelo TLauncher, vou ver se baixar o modpack pelo curseforge e colocar manualmente na pasta mods funciona

EU NEM FIZ NADA E DEU CERTO AGORA KKKKKKKK INICIEI O MODPACK PELO TLAUNCHER SEM FAZER 1 MODIFICAÇÃO SEQUER E DEU CERTO, GG

**Comment by ArtpokeBr** [comment]
Bom, que bom que funcionou... e só uma coisa, certifique-se de comprar o Mine assim que puder tá? O Preço é caro mas vale cada centavo.
