### ISSUE TITLE
Erro no mod Topography ao tentar entrar no meu mundo.

### ISSUE THREAD

**Issue by titanzin** [ArtpokeBr/Minecraft-Ultimato#200]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2.

**Descrição:**
O meu mundo no minecraft não esta entrando, aparece que o mod Topography esta dando erro. Eu consigo criar novos mundos e jogar normal neles, só nesse mundo esta dando erro, e esse é o meu mundo principal, ja virei noites jogando nele, fiz um progresso incrível, por favor me ajude, estou desesperado e não sei oque fazer. ( Esses mundos são no singleplayer).

**Sugestão de Solução:**
Eu acho que o problema esta no mod Topography, talvez substitui-lo ou corrirgir algum bug dele. Não acho que o problema seja o meu PC, pq eu estava conseguindo roda-lo a +100 FPS.

**Passo a Passo para chegar no Problema (Opcional):**
Eu estava jogando normal e meu pc crashou (possivelmente por usar toda a memória RAM, sim, eu coloquei para o mundo usar 10 Gb de RAM do meu total de 16 Gb para ter um melhor fps) após o pc reiniciar, entrei no minecraft e na hora de entrar no mundo da esse erro, ja tentei mudar a quantidade de RAM para mais, para menos, deixar ela normal do jeito que vem e etc.

**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest". 

[crash-2020-12-11_19.38.56-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5681775/crash-2020-12-11_19.38.56-server.txt)

**Screenshots:**
![Captura de Tela (28)](https://user-images.githubusercontent.com/75854442/101959570-520b8100-3be4-11eb-9744-cc68581e5812.png)

**Comment by titanzin** [comment]
se vc quiser discutir sobre isso pelo discord, estou deixando ele aqui: Trackinas @9852

**Comment by ArtpokeBr** [comment]
Uma pesquisa rápida sobre o problema, e parece que realmente, por conta do seu jogo ter crashado, a level.dat do seu mapa pode ter corrompido. acho que vou por um Mod de Backups automáticos no próximo update então.. não é a primeira pessoa que tem esse problema =/

**Comment by titanzin** [comment]
Blz cara, tem algum jeito de recuperar?
