### ISSUE TITLE
Problemas com Crafts

### ISSUE THREAD

**Issue by TutuiCardoso2007** [ArtpokeBr/Minecraft-Ultimato#201]
**Versão do Modpack:**
Minecraft Ultimato 1.0.2

**Descrição:**
Quando vou fazer um craft,ele tem mais de 1 recipe ou seja coloco 4 barras de ouro e aparece 1 recipe apenas,não tem a opção de olhar os outros crafts iguais.

**Passo a Passo para chegar no Problema (Opcional):**
Entro na crafting table e coloco ouro em cima, em baixo e dos 2 lados e então não tem a opção em baixo do item craftável de mudar o craft

**Screenshots:**

![image](https://user-images.githubusercontent.com/75325329/101966337-285b5580-3bf6-11eb-9e86-1ddb562958e5.png)

**Comment by ArtpokeBr** [comment]
Já foi corrigido, vou fechar e não se preocupe :)
