### ISSUE TITLE
Problema com o Quantum Compressor e Neutronium Compressor para fazer Singularidades

### ISSUE THREAD

**Issue by zNazguL** [ArtpokeBr/Minecraft-Ultimato#204]
Nao sei se estou usando errado ou algo do tipo ( Se estiver me desculpe , e me corrija )
Mas ao colocar os itens para fazer tal singularidade os itens nao sao inseridos no compressor e entao começar o processo de singularidade 
![Screenshot_2](https://user-images.githubusercontent.com/75873609/101976623-af73f200-3c25-11eb-8a25-af2e5fdc35fa.png)
![Screenshot_3](https://user-images.githubusercontent.com/75873609/101976625-b13db580-3c25-11eb-9742-c5e3601f55ff.png)

**Comment by ArtpokeBr** [comment]
tenta quebrar e colocar dnv, já me disseram que isso poderia acontecer mas tenta quebrar e colocar dnv kkk

**Comment by zNazguL** [comment]
> tenta quebrar e colocar dnv, já me disseram que isso poderia acontecer mas tenta quebrar e colocar dnv kkk

Ok vou tentar , obrigado pela ajuda <3
