### ISSUE TITLE
Crash ao iniciar modpack.

### ISSUE THREAD

**Issue by lhpmarcos** [ArtpokeBr/Minecraft-Ultimato#205]
Boa tarde ! Ontem a noite joguei o pack de boa sem problemas, mas hoje pela manha ele nao inicia, ele crasha durante o processo de carregar os mods. Segue abaixo o crash report.

[crash-2020-12-12_12.16.50-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5683308/crash-2020-12-12_12.16.50-client.txt)

**Comment by ArtpokeBr** [comment]
Crash com o Addon de Armaduras do Tinker's, não sei exatamente como corrigir no momento, mas se n ligar pra ele, pode desabilitar ele de carregar pelo Launcher que acredito ser de boas.
