### ISSUE TITLE
Nao tem vilas no mapa.

### ISSUE THREAD

**Issue by PretaTheDog** [ArtpokeBr/Minecraft-Ultimato#206]
eu criei vários mundos , no topographic e no padrão porem ambos , não são geradas vilas mesmo com a opção de gerar estruturas ativadas.

porem sempre fica esses caminhos e as veses uma estatua
![image](https://user-images.githubusercontent.com/75818648/101988123-98a9bb80-3c76-11eb-952b-806ed9ca3dbb.png)

![image](https://user-images.githubusercontent.com/75818648/101988194-dd355700-3c76-11eb-8724-e6bf66bcba2a.png)

**Comment by ArtpokeBr** [comment]
Coisa normal do Modpack, se acha que o Thanos não passou pelo mapa? :P vilas não existem mesmo foi tudo limpado pelo thanos!

**Comment by ArtpokeBr** [comment]
vou fechar.
