### ISSUE TITLE
Alguns líquidos do Thermal Foundation estão sem textura

### ISSUE THREAD

**Issue by XDeme** [ArtpokeBr/Minecraft-Ultimato#207]
**Versão do Modpack:**
1.0.2

**Descrição:**
Os liquidos Molten Invar, Molten Enderium, Molten Lumium, Molten Signalum, Molten Iridium e Molten Platinum estão sem texturas e aparecem um bloco preto e rosa no lugar, todos são liquidos do Thermal Foundation.
**Sugestão de Solução:**
Adicionar a textura dos liquidos ao mod Thermal Foundation.

**Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5683330/latest.log)

**Screenshots:**
![2020-12-12_13 42 02](https://user-images.githubusercontent.com/66138117/101988418-32259d00-3c78-11eb-9bcf-24fad8940b06.png)
![2020-12-12_13 17 48](https://user-images.githubusercontent.com/66138117/101988421-38b41480-3c78-11eb-9622-0418b510070e.png)
![2020-12-12_13 15 35](https://user-images.githubusercontent.com/66138117/101988422-4073b900-3c78-11eb-9739-c70d361fa293.png)

**Comment by ArtpokeBr** [comment]
Putz, isso é um problema clássico do Tinker's na verdade, infelizmente está fora da minha jurisdição kkk vou fechar.
