### ISSUE TITLE
Craftings bugados

### ISSUE THREAD

**Issue by MAVECCHIO** [ArtpokeBr/Minecraft-Ultimato#209]
Um crafting do pulverized coal coke , so funciona no crusher do immersive engeniring (nao sei escreve) , mas esse crusher nao aparece no jei , pq vc desativou

**Comment by ArtpokeBr** [comment]
O Pulverized Coal coke do Immersive? e outra coisa, quando for reportar, leia no jogo e mande prints. existe uma template de report para isso.

**Comment by GabrielFl4** [comment]
Opa, aqui temos uma falha do próprio usuário que enviou o issue. O pulverized coal coke **só pode** ser feito no crusher do immersive e este não tem crafting pois é uma máquina multibloco (Requer mais de um bloco) e para encontrar como faze-la, faça um livro do immersive engineering (Um livro e uma alavanca em uma mesa de crafting). Procure em maquinas avançadas "Crusher"
Espero ter ajudado no mal entendido!
![image](https://user-images.githubusercontent.com/75579401/102019401-273f3b00-3d52-11eb-893f-6bba732d00a9.png)
![image](https://user-images.githubusercontent.com/75579401/102019418-4342dc80-3d52-11eb-93d8-6922cf507f28.png)

**Comment by MAVECCHIO** [comment]
Muito obrigado!




De: GabrielFl4<mailto:notifications@github.com>
Enviado:domingo, 13 de dezembro de 2020 14:49
Para: ArtpokeBr/Minecraft-Ultimato<mailto:Minecraft-Ultimato@noreply.github.com>
Cc:MAVECCHIO<mailto:marco.antonio.vecchio@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [ArtpokeBr/Minecraft-Ultimato] Craftings bugados (#209)


Opa, aqui temos uma falha do próprio usuário que enviou o issue. O pulverized coal coke só pode ser feito no crusher do immersive e este não tem crafting pois é uma máquina multibloco (Requer mais de um bloco) e para encontrar como faze-la, faça um livro do immersive engineering (Um livro e uma alavanca em uma mesa de crafting). Procure em maquinas avançadas "Crusher"
Espero ter ajudado no mal entendido!
[image]<https://user-images.githubusercontent.com/75579401/102019401-273f3b00-3d52-11eb-893f-6bba732d00a9.png>
[image]<https://user-images.githubusercontent.com/75579401/102019418-4342dc80-3d52-11eb-93d8-6922cf507f28.png>
