### ISSUE TITLE
queria saber se tem como fazer a dimensão dos dragões com um mundo ja criado 

### ISSUE THREAD

**Issue by linezada** [ArtpokeBr/Minecraft-Ultimato#210]
eu criei um mapa já a um tempo e agora estamos procurando as dimensões vi em cima que pra ter essa dimensão precisa colocar um código na criação de mundo n teria outra forma de criar ela sem perder o mapa ?

**Comment by ArtpokeBr** [comment]
A Dimensão dos Dragões só é disponível se o gerador de mundo no caso do Singleplayer tiver sido o Topography. e no caso de servidores, precisa estar com a mesma, se não, a dimensão não carrega corretamente.

**Comment by linezada** [comment]
a vlw entao irmao , modpack mt pica fazia mt tempo q eu n jogava um bom assim
