### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Marcinho63** [ArtpokeBr/Minecraft-Ultimato#211]
O modpack possui o mod ZAWA, seguindo o caminho dos animais, pq não adicionar também o mod Mo'Creatures? pra evitar problemas de spawns também seria interessante criar uma dimensão própria para os mobs desses mesmos mods, Mo'Creatures é um mod que poderia ativar a nostalgia para viewers de diversos youtubers, assim como Venom podendo ser um bom exemplo.

**Comment by ArtpokeBr** [comment]
Já tem o Zawa e a série já está acontecendo, não tem como adicionar o Mó Creatures :)
