### ISSUE TITLE
Sugestão, chunk loading

### ISSUE THREAD

**Issue by HotDogPod** [ArtpokeBr/Minecraft-Ultimato#212]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas

**Versão do Modpack:**
1.0.2
**Descrição:**
Você poderia colocar um jeito de quem está jogando em singleplayer poder usar o chunck loading, se tiver como ativar isso nas configs do jogo, estou jogando só e não consigo acessar meu sistema de longe

**Comment by ArtpokeBr** [comment]
Minha sugestão é instalar o FTB Utilities. mas posso pensar no Assunto.

**Comment by HotDogPod** [comment]
Oque eu devo fazer ao instalar o FTB Utilities?

**Comment by ArtpokeBr** [comment]
Ué, não tá com o Modpack na curse? abre as configurações de perfil pra poder habilitar a caixinha de "modificações de perfil" depois é só pesquisar na lista por FTB Utilities e instalar, mas estou pensando em por no próximo patch talvez.

**Comment by GabrielFl4** [comment]
Art, eu iria fazer a mesma sugestão então só me resta fazer uma pergunta, quando o novo patch sai ? (Não estou querendo apressar, apenas quero jogar o modpack e muitas coisas se encontram quebradas atualmente (EMC, falta de alguns itens e etc...) Muitos problemas já foram reportados para você, então creio que o próximo patch vai resolver MUITA coisa. Estou ansioso
