### ISSUE TITLE
Itens com mesmo crafting

### ISSUE THREAD

**Issue by Skuldafn** [ArtpokeBr/Minecraft-Ultimato#214]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Descrição:**
Existem itens com mesmo crafting, sendo que na sério do Minecraft Ultimato os youtubers tem um botão a mais no inventario e nas crafting table para alterar entre esses craftings iguais.

![imagem_2020-12-13_112412](https://user-images.githubusercontent.com/75939839/102014631-b9851600-3d35-11eb-915e-2f8b8c34ade7.png)
![Sem título](https://user-images.githubusercontent.com/75939839/102014661-dc172f00-3d35-11eb-8d6e-957e53ddf6e9.png)

**Comment by ArtpokeBr** [comment]
A Versão que está com os Participantes é um pouco diferente da atual pública e se tem alguma receita em conflito, reporte-me! e em específico dessa da Obsidian ai... já foi corrigida!
