### ISSUE TITLE
como ativa o relogio no projecte dnv ??

### ISSUE THREAD

**Issue by KyurahK** [ArtpokeBr/Minecraft-Ultimato#217]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2

**Comment by ArtpokeBr** [comment]
Não ativa, procure outras alternativas ué! respeite minhas decisões criativas rapaiz..

**Comment by KyurahK** [comment]
e pq eu queria um que ativasse em area e em toda hora

**Comment by ArtpokeBr** [comment]
o Astral Sorcery possui um Ritual de aceleração em área que não foi desativado.
