### ISSUE TITLE
Não consigo instalar o mod 

### ISSUE THREAD

**Issue by Luck6280** [ArtpokeBr/Minecraft-Ultimato#218]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
11/24/2020
Minecraft Ultimato-1.0.2.zip
Release
1.12.2

**Descrição:**
Pelo CurseForge não estou conseguindo instalar e pelo MultiMC da erro quando vai carregar o mod IndustrialCraft 2
**Sugestão de Solução:**
Só quero saber oque pode causar esses erros

**Passo a Passo para chegar no Problema (Opcional):**

**Crash Log:**
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 09/12/20 19:08
Description: Updating screen events

java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at bnm.i(SourceFile:222)
	at bnm.a(SourceFile:188)
	at bcy$3$1.a(SourceFile:1233)
	at awy.a(SourceFile:50)
	at axu.a(SourceFile:350)
	at axu.k(SourceFile:413)
	at axu.p(SourceFile:390)
	at ave.s(SourceFile:1498)
	at ave.av(SourceFile:889)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at bnm.i(SourceFile:222)
	at bnm.a(SourceFile:188)
	at bcy$3$1.a(SourceFile:1233)
	at awy.a(SourceFile:50)
	at axu.a(SourceFile:350)
	at axu.k(SourceFile:413)
	at axu.p(SourceFile:390)

-- Affected screen --
Details:
	Screen name: awy

-- Affected level --
Details:
	Level name: MpServer
	All players: 11 total; [bew['Luck_6280_'/613020, l='MpServer', x=-20,61, y=15,00, z=0,50], bex['_yara'/105, l='MpServer', x=-21,79, y=15,00, z=-16,01], bex['Mate_extreme'/118, l='MpServer', x=-2,84, y=16,83, z=3,11], bex['kissv'/107, l='MpServer', x=-7,11, y=15,00, z=-2,90], bex['ste_ephano'/106, l='MpServer', x=3,80, y=15,00, z=1,16], bex['SteelBerry93'/124, l='MpServer', x=-20,63, y=27,48, z=0,50], bex['Munkel_'/111, l='MpServer', x=38,16, y=15,00, z=2,59], bex['brai23'/114, l='MpServer', x=40,50, y=15,00, z=0,50], bex['mordeu'/116, l='MpServer', x=21,42, y=15,81, z=4,81], bex['VulpixFX_'/119, l='MpServer', x=32,13, y=15,00, z=2,09], bex['MIGUELZZ'/121, l='MpServer', x=27,83, y=16,55, z=4,43]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,15,00,0,00 - World: (0,15,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 169694645 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 71 total; [bex['MIGUELZZ'/121, l='MpServer', x=27,83, y=16,55, z=4,43], bex['VulpixFX_'/119, l='MpServer', x=32,13, y=15,00, z=2,09], bex['mordeu'/116, l='MpServer', x=21,42, y=15,81, z=4,81], bex['brai23'/114, l='MpServer', x=40,50, y=15,00, z=0,50], bex['Munkel_'/111, l='MpServer', x=38,16, y=15,00, z=2,59], um['Suporte de Armaduras'/41, l='MpServer', x=-32,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/42, l='MpServer', x=-32,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/43, l='MpServer', x=-32,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/44, l='MpServer', x=-32,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/45, l='MpServer', x=-32,50, y=15,00, z=39,50], um['Suporte de Armaduras'/46, l='MpServer', x=-32,50, y=15,00, z=39,50], um['Suporte de Armaduras'/47, l='MpServer', x=-32,50, y=15,00, z=39,50], um['Suporte de Armaduras'/48, l='MpServer', x=-32,50, y=15,00, z=39,50], um['Suporte de Armaduras'/49, l='MpServer', x=-24,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/50, l='MpServer', x=-24,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/51, l='MpServer', x=-24,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/52, l='MpServer', x=-24,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/53, l='MpServer', x=-24,50, y=15,00, z=39,50], um['Suporte de Armaduras'/54, l='MpServer', x=-24,50, y=15,00, z=39,50], um['Suporte de Armaduras'/55, l='MpServer', x=-24,50, y=15,00, z=39,50], um['Suporte de Armaduras'/56, l='MpServer', x=-24,50, y=15,00, z=39,50], um['Suporte de Armaduras'/57, l='MpServer', x=-5,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/58, l='MpServer', x=-13,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/59, l='MpServer', x=-4,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/60, l='MpServer', x=-13,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/61, l='MpServer', x=-4,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/62, l='MpServer', x=-13,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/63, l='MpServer', x=-4,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/64, l='MpServer', x=-13,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/65, l='MpServer', x=-4,50, y=15,00, z=39,50], um['Suporte de Armaduras'/66, l='MpServer', x=-13,50, y=15,00, z=39,50], um['Suporte de Armaduras'/67, l='MpServer', x=-4,50, y=15,00, z=39,50], um['Suporte de Armaduras'/68, l='MpServer', x=-13,50, y=15,00, z=39,50], um['Suporte de Armaduras'/69, l='MpServer', x=-4,50, y=15,00, z=39,50], um['Suporte de Armaduras'/70, l='MpServer', x=-13,50, y=15,00, z=39,50], um['Suporte de Armaduras'/71, l='MpServer', x=-4,50, y=15,00, z=39,50], um['Suporte de Armaduras'/72, l='MpServer', x=-13,50, y=15,00, z=39,50], bex['ste_ephano'/106, l='MpServer', x=3,80, y=15,00, z=1,16], um['Suporte de Armaduras'/73, l='MpServer', x=5,50, y=15,00, z=-38,50], bex['kissv'/107, l='MpServer', x=-7,11, y=15,00, z=-2,90], um['Suporte de Armaduras'/74, l='MpServer', x=14,50, y=15,00, z=-38,50], bex['Mate_extreme'/118, l='MpServer', x=-2,84, y=16,83, z=3,11], um['Suporte de Armaduras'/75, l='MpServer', x=5,50, y=15,00, z=-38,50], bex['_yara'/105, l='MpServer', x=-21,79, y=15,00, z=-16,01], um['Suporte de Armaduras'/76, l='MpServer', x=14,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/77, l='MpServer', x=5,50, y=15,00, z=-38,50], bew['Luck_6280_'/613020, l='MpServer', x=-20,61, y=15,00, z=0,50], um['Suporte de Armaduras'/78, l='MpServer', x=14,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/79, l='MpServer', x=6,50, y=15,00, z=39,50], um['Suporte de Armaduras'/80, l='MpServer', x=14,50, y=15,00, z=39,50], uk['§e§lJogando §f§lFOOTBALL §e§lno §a§lMC.HYPIXEL.NET'/-1234, l='MpServer', x=12,38, y=14,97, z=0,47], um['Suporte de Armaduras'/81, l='MpServer', x=25,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/82, l='MpServer', x=25,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/83, l='MpServer', x=25,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/84, l='MpServer', x=25,50, y=15,00, z=39,50], um['Suporte de Armaduras'/85, l='MpServer', x=33,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/86, l='MpServer', x=33,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/87, l='MpServer', x=33,50, y=15,00, z=-38,50], um['Suporte de Armaduras'/88, l='MpServer', x=33,50, y=15,00, z=39,50], bex['SteelBerry93'/124, l='MpServer', x=-20,63, y=27,48, z=0,50], bex['_yara'/105, l='MpServer', x=-21,79, y=15,00, z=-16,01], bex['ste_ephano'/106, l='MpServer', x=3,80, y=15,00, z=1,16], bex['kissv'/107, l='MpServer', x=-7,11, y=15,00, z=-2,90], bex['Munkel_'/111, l='MpServer', x=38,16, y=15,00, z=2,59], um['Suporte de Armaduras'/113, l='MpServer', x=0,50, y=14,28, z=0,50], bex['brai23'/114, l='MpServer', x=40,50, y=15,00, z=0,50], bex['mordeu'/116, l='MpServer', x=21,42, y=15,81, z=4,81], bex['Mate_extreme'/118, l='MpServer', x=-2,84, y=16,83, z=3,11], bex['VulpixFX_'/119, l='MpServer', x=32,13, y=15,00, z=2,09], bex['MIGUELZZ'/121, l='MpServer', x=27,83, y=16,55, z=4,43], bex['SteelBerry93'/124, l='MpServer', x=-20,63, y=27,48, z=0,50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bdb.a(SourceFile:309)
	at ave.b(SourceFile:2311)
	at ave.a(SourceFile:334)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 568555232 bytes (542 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: TheLegend27.zip
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor .

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
Tenta aumentar a RAM Alocada, muitas vezes o IC2 Buga na hora de carregar por falta de RAM Alocada.
