### ISSUE TITLE
techguns ta dando dano da armadura do draconic

### ISSUE THREAD

**Issue by luizgzmed** [ArtpokeBr/Minecraft-Ultimato#219]
**Nota**: techguns ta dando muito dano da armadura do draconic 

**Versão do Modpack:**
versao mais recente

**Descrição:**
os mobs com arma tao dando dano com a armadura de draconic

**Comment by ArtpokeBr** [comment]
Coisa do Mod. infelizmente n sei se teria como eu resolver não...
