### ISSUE TITLE
Reaction Chambler controller crashou o mapa

### ISSUE THREAD

**Issue by guisorip** [ArtpokeBr/Minecraft-Ultimato#221]
1.12.2
Fiz a maquina para conseguir transformar titaniun ore
Porém ao colocar todas as configurações exatas o mapa crashou e eu não consigo mais entrar no mesmo.

**Comment by ArtpokeBr** [comment]
Se n me mandar o Crash report fica difícil kkk sem falar que poderia ter usado a Template de Report disponível né?

**Comment by guisorip** [comment]
nem to ligado mano que precisava disso, proxima vez eu mando certinho
