### ISSUE TITLE
Craft de alguns item

### ISSUE THREAD

**Issue by AltairNeri** [ArtpokeBr/Minecraft-Ultimato#222]
Na hora de craftar alguns item que tem o mesmo crafts tipo as hamers e a linha do yoyo não aparece a opção de selecionar qual craft quero fazer e sim fica sempre no mesmo

**Comment by ArtpokeBr** [comment]
Se há craftings com Problemas, mande Print. aliás existe uma template de Report de problemas justamente por isso! para não faltar informação que ajuda ;p
