### ISSUE TITLE
Advanced Universal Cable não é aprendido pela Transmutation Table

### ISSUE THREAD

**Issue by jvfd3** [ArtpokeBr/Minecraft-Ultimato#225]
**Versão do Modpack:**
1.0.2

**Descrição:**
Ao utilizar o advanced universal cable do mod Mekanism na transmutation table do mod Project E, o item é perdido, o EMC é obtido, mas o crafting não é aprendido

**Sugestão de Solução:**
Conferir o que pode estar fazendo com que esse item não seja aprendido pelo Project E

**Passo a Passo para chegar no Problema (Opcional):**
**Screenshots:**
![1](https://user-images.githubusercontent.com/10092672/102038827-06ed9b80-3da7-11eb-99ba-94d2ad56684d.png)
![2](https://user-images.githubusercontent.com/10092672/102038821-05bc6e80-3da7-11eb-8132-ff015638fb1a.png)
![3](https://user-images.githubusercontent.com/10092672/102038822-06ed9b80-3da7-11eb-970d-b86b78652c38.png)
![4](https://user-images.githubusercontent.com/10092672/102038825-06ed9b80-3da7-11eb-85e4-33965c847df7.png)

**Comment by ArtpokeBr** [comment]
Normal, os Cabos do Mekanism são definidos por NBT, então o ProjectE não lida bem com isso. já foi corrigido.

**Comment by jvfd3** [comment]
Excelente
