### ISSUE TITLE
O mod que anima os player está prejudicando minha gameplay

### ISSUE THREAD

**Issue by LegalPlayer** [ArtpokeBr/Minecraft-Ultimato#228]
Queria saber qual o nome do mod que anima os player, porque está prejudicando o meu fps, pois meu pc n eh tão bom, queria retira-lo da pasta "mods" mas n sei o nome do mod, consequentemente crashando de vez em quando.

**Comment by ArtpokeBr** [comment]
Emoticons, ele é apenas estético, então se estiver jogando no Singleplayer mesmo, pode desativar. vou fechar.
