### ISSUE TITLE
Modpack n inicia

### ISSUE THREAD

**Issue by 1Marquin** [ArtpokeBr/Minecraft-Ultimato#229]
Versão:1.0.2

Ola art, primeiramente peço desculpas por estar incomodando com isso mas já fui atrás de resolver isso e n consegui, bom qnd eu abro o modpack mostra o seguinte

![Captura de Tela (2)](https://user-images.githubusercontent.com/76008759/102125274-2ed11380-3e28-11eb-8015-752a382525b8.png)

Eu já procurei em diversos sites coisas relacionadas a isso, se puder me ajudar eu agradeceria muito :)

**Comment by 1Marquin** [comment]
Eu ja tentei atualizar o Java
instalar um bagui de OpenGL la
e nada deu certo :(

**Comment by ArtpokeBr** [comment]
tentou aumentar a RAM Alocada?

**Comment by 1Marquin** [comment]
Meu computador tem 8G de ram tentei alocar 6G mas n funcionava

**Comment by 1Marquin** [comment]
Eu tenho um I5 de sétima geração n sei se eh por isso mas achei melhor avisar

**Comment by ArtpokeBr** [comment]
Tenta colocar essas Java args:  -version:1.8+ -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M e vê se funfa.

**Comment by 1Marquin** [comment]
eh eu sou leigo e n sei onde bota isso ;-;

**Comment by 1Marquin** [comment]
acho q botei no lugar certo
apareceu o mesmo erro ;-;

**Comment by 1Marquin** [comment]
Art o estranho eh q isso acontece com TODOS os modpacks da 1.12.2 pra cima ent eh muito estranho pq ate mesmo um mod SUPER leve com 10 mods eu n consigo jogar no curseforge

**Comment by ArtpokeBr** [comment]
tentou reinstalar o Mine na CurseForge? pode ser por causa disso nem sei, o Launcher da Curse ainda está em Beta então de vez enquando dá essas zuadas mas o pior é que isso é um erro do Mine =/

**Comment by 1Marquin** [comment]
eh... como eu faco isso ;-;

**Comment by 1Marquin** [comment]
desculpa incomodar com isso to tentando fazer agora obrigado pela ajuda caso n funcione eu dou meu jeitinho aqui obrigado :)

**Comment by 1Marquin** [comment]
cara acho q vou desistir :( tentei no MultiMC e deu crash, n tentei desinstalar o mine pq n sei fazer isso ;-;

**Comment by 1Marquin** [comment]
Art oq aconteceria se eu deletasse a pasta do mine da twitch do PC?

**Comment by 1Marquin** [comment]
Art acredito ter descoberto o problema, as pastas das versoes do forge n tem o arquivo Java so o .Json n sei se eh isso mas fui ver na minhas pasta do mine normal e tinha o arquivo Java, tentei pegar o arquivo java da pasta do mine e n funfo MAS caso isso seja anormal da um help ae

**Comment by 1Marquin** [comment]
Desculpa por estar sendo chato e mandando um monte de msg aqui mas eh q queria muito jogar os mods da curse e pa
