### ISSUE TITLE
ideia para um dowlond melhor

### ISSUE THREAD

**Issue by nija00** [ArtpokeBr/Minecraft-Ultimato#23]
a minha ideia é deixar todos os mods juntos com a pasta pra dowlond (em versao server se nao me engano), dai tem uma ideia do peso do modpack e outras coisas, tipo eu fiz tudo mod por mod em 4 horas dai vai la e nao abre por que um mod desconhecido nao abre, alem de tirar essa chance ajuda muito quem nao tem mine original

**Comment by ArtpokeBr** [comment]
O Modpack está upado da forma correta, infelizmente não posso também ficar incentivando Mine Pirata desse jeito... e na real, basta ter um launcher que consiga importar instâncias da Curse, só isso.. e já ouvi falar de Launchers que conseguem fazer isso! só baixar o rar pelo site da curse e importar!
