### ISSUE TITLE
Monstros Extremamente Overpower no deep Dark

### ISSUE THREAD

**Issue by Hirothewolf** [ArtpokeBr/Minecraft-Ultimato#230]
A dimensão do Deep dark é extremamente rica em minerios mas tem alto risco de morte, alguns monstros de la são extremamente fortes ao ponto de serem mais fortes que diversos tipos de Boss, tornando as torres de defesa do Techguns Inuteis para defesa

ja vi aranhas do deep dark com mais de 8 mil de vida(não é meme) e que quase me mataram com um hit com a armadura do draconic(prints tiradas em um mapa copiado para teste de armas e maquinas)

![2020-12-14_16 19 11](https://user-images.githubusercontent.com/75646500/102125389-6049df00-3e28-11eb-9701-cff5e57a00ec.png)
![2020-12-14_16 05 48](https://user-images.githubusercontent.com/75646500/102124529-2af0c180-3e27-11eb-8e22-9c1d47f07cb3.png)
![2020-12-14_16 05 19](https://user-images.githubusercontent.com/75646500/102124566-380db080-3e27-11eb-914f-f12593c94774.png)

**Comment by ArtpokeBr** [comment]
Isso é normal da Deep, ela Multiplica os Status dos Mobs.. olha, do jeito que é fácil farmar sem ir pra lá, n vejo motivo pra mexer não kkk
