### ISSUE TITLE
Download do Modpack da erro

### ISSUE THREAD

**Issue by zThuurzin** [ArtpokeBr/Minecraft-Ultimato#234]
erro no download 1.0.4
ele baixa normalmente so que no mod TheBetweenlands da erro de download
![Desktop Screenshot 2020 12 14 - 23 12 30 16](https://user-images.githubusercontent.com/76021478/102159867-2518d180-3e63-11eb-9009-b5801b985de9.png)

**Comment by ArtpokeBr** [comment]
Tenta jogar o Modpack pra MultiMC pra ver se continua o Problema, a Curse pode estar um pouco zuada pra baixar...
