### ISSUE TITLE
Erro no Modpack

### ISSUE THREAD

**Issue by CVPL1** [ArtpokeBr/Minecraft-Ultimato#235]
Olá, está dando erro no download do Modpack, Poderia me ajudar?
![Screenshot_6](https://user-images.githubusercontent.com/76024683/102163381-bf7c1380-3e69-11eb-91ff-4806ab21387e.png)
 irei mandar uma foto

**Comment by ArtpokeBr** [comment]
A Curse ainda está em beta e na verdade não conseguir baixar pelo launcher é meio que um problema deles e não meu... então não tenho como fazer nada... se o erro persistir tenta reportar no Discord deles (obviamente em inglês) ou baixar diretamente a File do update no site da curse e importar no MultiMC.
