### ISSUE TITLE
Remoção do Optifine

### ISSUE THREAD

**Issue by RafaelBizzo** [ArtpokeBr/Minecraft-Ultimato#237]
Ryzen 5 2600, GeForce GTX 1060 6GB, 16G de RAM, Versão 1.0.4

Jogava na versão 1.0.2 então fui atualizar por causa do TechGuns e agora meu jogo conegela por 5 segudos e dps volta a funcionar isso acontece toda vez em um intervalo de 2 min.

Esse erro não é exclusivo dessa versão, acontecia também nas anteriores, só que consegui resolver adicionando esses argumentos: `-XX:+UseG1GC -Xmx6G -Xms6G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`  Acho que o problema seja a remoção do Optifine, não sei se estou ficando louco porém parece que ele não vem nessa versão.

Para o problema acontecer preciso fazer movimentos rápidos ou carregar muitas chunks em pouco tempo (Como indo entre dimensões)

https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5698273/latest.log

Obrigado pelo Trabalho!

**Comment by ArtpokeBr** [comment]
Sim, o Optifine nunca veio na verdade. já que tem Copright então não existe autorização para redistribuição dele.

**Comment by RafaelBizzo** [comment]
Ué como eu usava ele intão? Que loucura
Posso instalar o da versão 1.12.2 por minha conta?

**Comment by ArtpokeBr** [comment]
sim.

**Comment by RafaelBizzo** [comment]
Obrigado Art, instalei ele aqui e voltou a funcionar suave. Manda Salve!
