### ISSUE TITLE
Por favor conserte rápido o bug não consigo jogar!! Deep Dark e o cachorro que te mata no escuro bugado!

### ISSUE THREAD

**Issue by ruan12354** [ArtpokeBr/Minecraft-Ultimato#240]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
Minecraft Ultimato-1.0.4.zip

**Descrição:**
Eu estava na minha base na lua e construi um portal para a deep dark até ai tudo ok quando eu voltei da dimensão voltei para o overworld e logo em seguida fui para o nether e percebi que estava bugado cheguei numa parte em que o nether estava escuro e do nada o jogo falou que se eu não iluminasse o gulber( o cachorro acho que é esse o nome) iria me matar sendo que eu não estava na deep dark!! E agora ele fica la me esperando.
**Sugestão de Solução:**
Substitua este texto por uma possível solução que você acha que possa ser feita para o seu problema! isto ajuda pois muitas vezes sua sugestão pode ser boa e pode ser implementada e resolvida rápidamente! 

**Passo a Passo para chegar no Problema (Opcional):**
Eu estava na minha base na lua e construi um portal para a deep dark até ai tudo ok quando eu voltei da dimensão voltei para o overworld e logo em seguida fui para o nether e percebi que estava bugado cheguei numa parte em que o nether estava escuro e do nada o jogo falou que se eu não iluminasse o gulber( o cachorro acho que é esse o nome) iria me matar sendo que eu não estava na deep dark!! E agora ele fica la me esperando.

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5698607/latest.log)

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
Como assim bugado? é só iluminar que tu n morre lá kkk

**Comment by ruan12354** [comment]
Não é na deep Dark agora o cachorro ta no overworld tabemmm

**Comment by ruan12354** [comment]
Eu usei o advanced charged portal para voltar para casa e não voltei pelo bloco do portal ai o cachorro veio comigo. E quando eu entro no nether em algum local escuro ele vem e me mata também no overworld

**Comment by ArtpokeBr** [comment]
Não fique no escuro.

**Comment by ruan12354** [comment]
![image](https://user-images.githubusercontent.com/75855177/102273957-e84fe780-3f01-11eb-8ab9-a15b4217a1b2.png)

**Comment by ruan12354** [comment]
o problema é que eu não estou no escuro estou no nether o lugar é cheio de lava!!! 
![image](https://user-images.githubusercontent.com/75855177/102274136-23eab180-3f02-11eb-9802-fdb900d3b45f.png)

**Comment by ruan12354** [comment]
Fica essa mensagem e depois o cachorro vem e me mata to tendo que jogar no peacefull ou eu morro

**Comment by ruan12354** [comment]
Entendeu o bug?

**Comment by ruan12354** [comment]
tipo fica de noite la fora e eu saio de casa e vem o cachorro e me mata

**Comment by ruan12354** [comment]
Eu crio outro ticket ja que você encerrou este?Porque realmente é um bug

**Comment by Robson1337** [comment]
verdade, não da nem para ir no the end que ja morre
