### ISSUE TITLE
Bug do cachorro do mundo do Deep Dark

### ISSUE THREAD

**Issue by ruan12354** [ArtpokeBr/Minecraft-Ultimato#241]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
Minecraft Ultimato-1.0.4.zip

**Descrição:**
Fiz um portal pra deep dark para minerar drakonic após eu terminar para eu voltar para casa eu usei o advanced charged porter que é do mod do rftools e após eu usar voltei para a minha base o problema foi que o cachorro que te mata naquela dimensão por conta do escuro por algum bug ele agora também ta no mundo sem ser da deep dark ele ta na lua, no nether e também no overworld e o ruim disso que sempre que vou para o nether ele me mata falando que ta escuro mas pela print que eu enviei para você não esta escuro! E também quando ta de noite no overworld eu morro ou seja não estou conseguindo jogar o modpack:( Por favor tente resolver se vc precisar de mais um detalhe me manda uma mensagem que explico o melhor detalhado possível que conseguir. 

**Sugestão de Solução:**
Você acha que se eu excluir o mod da deep dark e depois colocar o bug sai? 
**Passo a Passo para chegar no Problema (Opcional):**
Fiz um portal pra deep dark para minerar drakonic após eu terminar para eu voltar para casa eu usei o advanced charged porter que é do mod do rftools e após eu usar voltei para a minha base o problema foi que o cachorro que te mata naquela dimensão por conta do escuro por algum bug ele agora também ta no mundo sem ser da deep dark ele ta na lua, no nether e também no overworld e o ruim disso que sempre que vou para o nether ele me mata falando que ta escuro mas pela print que eu enviei para você não esta escuro! E também quando ta de noite no overworld eu morro ou seja não estou conseguindo jogar o modpack:( Por favor tente resolver se vc precisar de mais um detalhe me manda uma mensagem que explico o melhor detalhado possível que conseguir. 
**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5698803/latest.log)

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.
![image](https://user-images.githubusercontent.com/75855177/102275680-8cd32900-3f04-11eb-9f9c-6d335951ea6b.png)

**Comment by Felipemm21** [comment]
percebi isso tambem, pra mim ta impossivel jogar pq to usando o ocelot pet entao n ilumino nenhum lugar e esse grue aparece toda hora
