### ISSUE TITLE
Conflito de craft com a iron ladder do quark 

### ISSUE THREAD

**Issue by Rafaelcore** [ArtpokeBr/Minecraft-Ultimato#245]
Versão do Modpack:1.0.4

Descrição:Quando você tenta fazer a iron ladder do quark ela dá conflito com a Steel Bars Do Zoo and wild animals

Sugestão de Solução:Mudar o craft de um dos dois
 
[Screenshots:]
https://prnt.sc/w3jl97
https://prnt.sc/w3jlen

**Comment by Rafaelcore** [comment]
haha tive que mandar a imagem por link pq a imagem não tava funcionando no site

**Comment by ArtpokeBr** [comment]
Usando o Lightshot é só dar cntrl C após marcar a print e dar cntrl V aqui que funciona, mas enfim. obrigado pelo Report.

**Comment by Rafaelcore** [comment]
> Usando o Lightshot é só dar cntrl C após marcar a print e dar cntrl V aqui que funciona, mas enfim. obrigado pelo Report.

foi exatamente isso que eu fiz só que o site tava bugando no upload kkkk
