### ISSUE TITLE
Receitas "Iguais"

### ISSUE THREAD

**Issue by RegisCoelho** [ArtpokeBr/Minecraft-Ultimato#246]
Eu vi que existem algumas receitas iguais (Ex: Wool Collar - Doggy Talents e  String Cord - Yoyos, Car Chassis - Jurassic Craft e Iron Ring - Aether, etc.) Em algumas lives ( BruninhoNeets e Nofaxu ) percebi que existem meios para retirar essa redundância, por favor disponibilize esse patch, ou pelo menos esse mod para quem está jogando o modpack. Vou procurar pelo mod que retira a redundância por mim mesmo [ stimmedcow : NoMoreRecipeConflict ], mas existem pessoas que não sabem como fazer isso, e podem ficar sem o crafting de alguma coisa importante...

Bom, seria apenas uma melhoria pra quem tá tentando jogar junto, nada roubado, acredito.

**Comment by ArtpokeBr** [comment]
Atualize o Modpack para a versão mais recente, e encontrando outros Conflitos, Reporte com imagens dos Crafts em questão, isso ajuda muito. vou fechar.

**Comment by RegisCoelho** [comment]
Estou com a versão 1.0.4, posso tentar procurar por todas as receitas iguais, porém, apenas a adição do mod já resolve. Mas, vou procurar as receitas...
