### ISSUE TITLE
Sugestões de mods

### ISSUE THREAD

**Issue by Nicolas-Plays** [ArtpokeBr/Minecraft-Ultimato#25]
Você podia acrescentar mais mods espaciais além do extra planets. Há 2 mods de exploração espacial muito bons que seriam interessantes ver nessa série:
1. More Planets: mod acrescenta um sistema solar novo, com bosses e novos itens, além disso o mod adiciona máquinas novas e mobs únicos. Só vi esse mod no Galacticraft X e nunca mais vi ele no YouTube
2. Zollern Galaxy: esse mod adiciona 3 sistemas solares, mobs novos e também tecnologias novas, ele é um mod muito bom e sem muitos bugs, que nunca vi ser gravado por brasileiros, seria interessante vê-lo no YouTube pela primeira vez.

Todos os mods que eu citei vc encontra no CurseForge e encontra na versão 1.12.2

**Comment by ArtpokeBr** [comment]
A ideia do Modpack não é ser focado em Exploração espacial, O More planets não tem não? jurava que tinha colocado, mas enfim, oq tem no Modpack é apenas uma palhinha, assim como a maioria dos outros "Grupos" de Mods. como me pediram pra ter o máximo de conteúdo variável, é impossível eu detalhar demais todos eles sem pesar muito kkk

**Comment by Nicolas-Plays** [comment]
Já que a série não é de exploração espacial, é melhor não colocar mais mods do tema, porque esses mods são muito extensos e também há poucos deles nas versões novas, é melhor usa-los só em séries espaciais. O modpack do Ultimato tá ficando daora, tem vários mods legais aí, mods que fazia tempo q eu não via tipo o aether, to até pensando em baixar alguns no meu modpack.

**Comment by ArtpokeBr** [comment]
kkkk ok, fechado este issue então :)
