### ISSUE TITLE
Habilitar craftings do Mekanism

### ISSUE THREAD

**Issue by Skuldafn** [ArtpokeBr/Minecraft-Ultimato#250]
Olá, gostaria de saber como faço para habilitar o craftings das maquinas do mekanism, mesmo que nos itens tenha a descrição não consegui ativar o crafting.
E o golden lasso também não esta craftando, por mais que coloque os itens na ordem certa o crafting não da em nada. obrigado desde já.

**Comment by ArtpokeBr** [comment]
o Golden Lasso possui uma receita que gasta XP, então é necessário ter o XP adequado e recomendo usar uma Crafting table vanilla pra garantir que vá. Sem falar que nas máquinas do Meka está falando exatamente o que precisa ser feito na tooltip, Com a máquina no chão use o Installer nela para dar upgrade (só clicar com o botão direito nela).

**Comment by ArtpokeBr** [comment]
Vou fechar.
