### ISSUE TITLE
Não responde 

### ISSUE THREAD

**Issue by Danivain123** [ArtpokeBr/Minecraft-Ultimato#251]
Eu havia baixado a versão antiga e abria normalmente, porém após a nova atualização o mod dava (não respondendo) e raramente abria, ai fui reinstalar a versão antiga porém continuava aparecendo que não respondia, oque posso fazer para arrumar isso?

**Comment by Danivain123** [comment]
OBS: o meu pc é um note da Acer com i5 de nona geração, Nvidia geforce 1650, com giga de RAM. adorei seu canal me ajudou muito!<3 discord: DaniVain#9749

**Comment by Danivain123** [comment]
outra obs, ele sempre fica sem responder nunca em 6/7 do mod!

**Comment by ArtpokeBr** [comment]
Quanto de RAM está alocada para o Modpack?
