### ISSUE TITLE
Spawn do mod de galinhas na geração topography

### ISSUE THREAD

**Issue by ghost** [ArtpokeBr/Minecraft-Ultimato#252]
**Versão do Modpack:**
1.0.4

**Descrição:**
Na geração de mundo topography (padão), o spawn de galinhas modificadas e praticamente inexistente, porem se mudar a geração para Default tudo volta ao normal.

**Comment by ArtpokeBr** [comment]
então você mesmo testou e na topography o Spawn está baixo? interessante. infelizmente não tem como passar a recomendar a Deault por conta justamente da Dimensão dos Dragões. devo talvez analisar a possibilidade de adicionar craftings para as galinhas então.

**Comment by ArtpokeBr** [comment]
Vou fechar mas obrigado pela informação.
