### ISSUE TITLE
Meu Ultimato Não abre

### ISSUE THREAD

**Issue by KaioMode** [ArtpokeBr/Minecraft-Ultimato#253]
Cara acabei de atualizar o Minecraft Ultimato e ele não abre não se e só comigo mas pfv me ajuda

**Comment by ArtpokeBr** [comment]
Faltando informação, como assim não abre? qual o Launcher? prints?

**Comment by KaioMode** [comment]
Ser desculpa fazer vc perde seu tempo mas era só bug do meu aqui mas cara
vlw aí por conserta o bug do cosmetic amor agr eu consigo ver minha skin

Em Qua, 16 de dez de 2020 01:08, ArtpokeBr <notifications@github.com>
escreveu:
