### ISSUE TITLE
Fui pegar um item e Crashou

### ISSUE THREAD

**Issue by Lwayox** [ArtpokeBr/Minecraft-Ultimato#254]
**Versão do Modpack:**
1.0.4

**Descrição:**
fui pegar um totem de imortalidade no emc e depois disso meu jogo crashou

**Crash Log:**
[crash-2020-12-16_02.05.47-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5700445/crash-2020-12-16_02.05.47-server.txt)

**Comment by ArtpokeBr** [comment]
Erro relacionado ao Quality Tools, não duplique o Totem da Imortalidade. provavelmente vou tirar o EMC dele então.

**Comment by Lwayox** [comment]
como eu faço pra entra no meu mundo agr, toda vem q entro nele, ta crashando eu perdi meu save entao

**Comment by Lwayox** [comment]
alias fiz um outro teste e abri um mundo no criativo e eu peguei o totem na mao e meu jogo crashou seria viavel tirar o quality tools?

**Comment by ArtpokeBr** [comment]
Tirar não, mas já disse, possivelmente tirar o EMC, o Crash só não aconteceu quando tu tirou ele do EMC lá? outra coisa, reverte um Backup do Mapa. no último update eu coloquei um Mod de Backups justamente pra isso.

**Comment by Nightmare58** [comment]
Resolvi esse problema indo em config\qualitytools\Quailities e clicando em trinkets e movendo o 
{
        "item": "minecraft:totem_of_undying"
      }
      
      para a parte de blacklist, tirando a qualidade dele e fazendo o jogo abri.

**Comment by Lwayox** [comment]
vlw obg

**Comment by ArtpokeBr** [comment]
Já corrigi no último patch.
