### ISSUE TITLE
chunk loader 

### ISSUE THREAD

**Issue by bmloco** [ArtpokeBr/Minecraft-Ultimato#255]
Bom é já que o mod e para solo player poderia habilitar a chunk loader para uso ?

**Comment by ArtpokeBr** [comment]
Se quiser habilitar uma Chunkloader não tem como sem mexer em configs. então meu conselho é instalar o FTB Utilities e usar o Chunk load dele.

**Comment by JoelCSF** [comment]
Acabei de colocar um 'issue' sobre isso. Alguém poderia me informar como posso estar fazendo essa manobra? Um chunkloader seria muito bom.

**Comment by ArtpokeBr** [comment]
tá escrito ali, instala o FTB Utilities. pelo menos é minha recomendação.
