### ISSUE TITLE
Armadura do Construct Armory faltando textura.

### ISSUE THREAD

**Issue by lhpmarcos** [ArtpokeBr/Minecraft-Ultimato#256]
Boa tarde, montei uma armadura do construct armory usando os seguintes materiais.

Armor Plates : Steel
Core : Demon Metal
Trim : Knighslime

![armor bugada 2](https://user-images.githubusercontent.com/75625691/102364134-e71bca80-3f94-11eb-82dc-5cfc145e6198.png)
![armor bugada](https://user-images.githubusercontent.com/75625691/102364142-e84cf780-3f94-11eb-99c9-dbacb15c4b80.png)

Como pode ver está faltando algumas texturas na armadura.

**Comment by ArtpokeBr** [comment]
qual versão do Modpack? e POR QUE DIABOS NÃO USOU A TEMPLATE DE REPORT!?

**Comment by lhpmarcos** [comment]
Perdão kkk nao sei usar muito essa página. Cara acredito q esteja usando a ultima atualizaçao, uso o multiMC

**Comment by ArtpokeBr** [comment]
Confira para mim. o Modpack atualmente está na 1.0.4 e nela respectivamente eu já desativei os Modelos do Emoticons, que era oq estava causando BO's de Render.
