### ISSUE TITLE
Sugestão de Texturas

### ISSUE THREAD

**Issue by zMigueel** [ArtpokeBr/Minecraft-Ultimato#257]
Assim como fez no ArtPack, alterar as texturas do Refined porém no estilo do Ultimato, caso não seja extremamente trabalhoso.

**Comment by ArtpokeBr** [comment]
Poderia colocar sim, a questão é que optei por não por conta dos Participantes as vezes não gostarem kkk

**Comment by zMigueel** [comment]
Ficaria bem bonito, na minha opinião.
