### ISSUE TITLE
Eu não estou conseguindo abaixar a nova versão do minecraft ultimato

### ISSUE THREAD

**Issue by titanjunior54** [ArtpokeBr/Minecraft-Ultimato#258]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.4
**Descrição:**
não consigo instalar a nova versão 1.0.4

**Sugestão de Solução:** Não faço ideia do que fazer.

**Passo a Passo para chegar no Problema (Opcional):**
Eu apenas tento instalar a nova versão e aparece um erro.

**Crash Log:**
Não tem nenhum.

**Screenshots:**
![Captura de Tela (29)](https://user-images.githubusercontent.com/75854531/102394396-7686a500-3fb8-11eb-9c14-f4123d6a9d89.png)

**Comment by titanjunior54** [comment]
E eu tb n sei oq fazer com aqule arquivo UltimatoServerFiles.

**Comment by ArtpokeBr** [comment]
as Server files são só pra quem quiser server ué. e leia oq está escrito. o erro está bem ali! você tem outros Modpacks instalados? pois justamente não há um local de instalação especificado ali pros Modpacks. vá nas configs e ajeite isso.

**Comment by titanjunior54** [comment]
blz, vlw cara eu consegui
