### ISSUE TITLE
Ajudar para entrar

### ISSUE THREAD

**Issue by TutuiCardoso2007** [ArtpokeBr/Minecraft-Ultimato#259]
**Versão do Modpack:**
1.0.4

**Descrição:**
Meu amigo está tentando entrar no meu server (pelo Radmin) porem aparece um erro

**Passo a Passo para chegar no Problema (Opcional):**
Entrar no multiplayer e clicar em entrar no meu mundo
**Crash Log:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/75325329/102402988-5eb51e00-3fc4-11eb-9e4c-0b308b7de13e.png)

**Comment by ArtpokeBr** [comment]
Tá Escrito o Erro. não é algo que eu possa resolver na verdade.
