### ISSUE TITLE
Melhoria no dowlond

### ISSUE THREAD

**Issue by nija00** [ArtpokeBr/Minecraft-Ultimato#26]
Fazer tipo um dowlond completo com todos os mods seria uma boa (pelo site do curse forge) além de poupar tempo seria bem mais fácil

**Comment by ArtpokeBr** [comment]
Mas já o Modpack por completo já está disponível... o Arquivo que está na curse pode ser usado para importar o Modpack em launchers fora da curse, e o própio launcher da curse já baixa direto... não sei qual o problema que você está achando que tem kkk
