### ISSUE TITLE
Problema com o Mod Grue em locais não escuros

### ISSUE THREAD

**Issue by wjwolf7551** [ArtpokeBr/Minecraft-Ultimato#260]
Estou tendo um pequeno problema, ao usar o Helicóptero do JurassiCraft o mod Grue reconhece como local escuro e acaba invocando o bicho e dando insta-kill dentro do Helicóptero

**Comment by ArtpokeBr** [comment]
Atualize o Modpack. já corrigi os Spawns do Grue para apenas da Deep Dark.
