### ISSUE TITLE
Ice and fire Dimension

### ISSUE THREAD

**Issue by DekimJonhy** [ArtpokeBr/Minecraft-Ultimato#265]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

Versão: 1.0.5

Desde que mudei para a nova versão , a dimensão do Ice and fire deixou de fazer spawn de zombies e outros mobs. Não sei o motivo ou se só acontece a mim.

**Comment by DekimJonhy** [comment]
Eu criei um novo mundo e aparencem mobs la...acho que é problema do mapa talvez

**Comment by ArtpokeBr** [comment]
Hmm estranho, eu não mexi em nenhuma config de Spawn não.

**Comment by DekimJonhy** [comment]
Outra coisa estranha é que os chunks não estão a fazer load ...existe forma de dar reset ? apenas ao fire and ice? secalhar se me deres o id da dimensão eu consiga resolver

**Comment by ArtpokeBr** [comment]
oq se pode fazer é na pasta do Save, deletar os arquivos da DIM 43 pra resetar a dimensão dos Drags.

**Comment by DekimJonhy** [comment]
não funciona, quando entro no portal aparece aquela plantaforma de terracotta , posso ter feito errado tamém...

**Comment by ArtpokeBr** [comment]
Então você criou o Mapa de forma errada. o mapa DEVE ser criado usando o Topography.

**Comment by DekimJonhy** [comment]
mas eu criei com topography, ele dantes aparecia xD so agora é que na oesta a fazer load aos chunks xD
