### ISSUE TITLE
Problema de animação dos players, MC Ultimato 1.12.2

### ISSUE THREAD

**Issue by BielKarl** [ArtpokeBr/Minecraft-Ultimato#267]
Olá ArtpokeBr, eu queria saber o qual é o mod das animações, para eu poder retiralo, pois não está deixando eu ver a minha armadura, aoinvés de eu ver ela com meio que um relevo, parece que eu troquei de skin e fica com uma cor diferente, e gostaria de saber qual é o mod das danças tb. E queria falar outra coisa, quando a gente bebe uma poção de velocidade, ou faz algo pra ganhar velocidade, o FOV que era pra aumentar, ele diminui, e se vc estiver rapido, parece que você esta devagar, e assim vice-versa. ou seja o FOV está invertido.
Certo: Rapido = FOV Alto Devagar = FOV baixo
Como está no modpack Rapido = FOV baixo Devagar = FOV alto

Obrigado por ter feito essa mod, é um mod muito legal mesmo, Parabens!!!
sei que to sendo chato falando isso, mas é que me incomoda um pouco.
Aguardo a sua resposta!!!

**Minecraft oreiginal, Versão 1.12.2**

**Comment by ArtpokeBr** [comment]
Primeiro, a versão do Minecraft não importa... oq importa é a versão do Modpack pois Justamente na versão mais atualizada do Modpack a 1.0.5 já está corrigido este problema. atualize seu Pack.

**Comment by BielKarl** [comment]
okk desculpa e obrigado
