### ISSUE TITLE
Problemas de Perfomance

### ISSUE THREAD

**Issue by zMigueel** [ArtpokeBr/Minecraft-Ultimato#27]
há algum jeito de melhorar a performance do modpack? já coloquei optifine, mas ainda possuo alguns crashes rolando mesmo com 6gb de ram alocados.
CPU: I3 4130
8 de ram.

**Comment by zMigueel** [comment]
+
Sempre é em momentos de gameplay que ocorre crashes.

**Comment by ArtpokeBr** [comment]
Hmm, consegue me mandar o Log mais recente de quando tu crasha? (preferencialmente coloque no PasteBin pra ficar mais fácil de ler pelo navegador) Além disso, eu não tenho certeza, mas talvez sua CPU seja um pouco desatualizada.

**Comment by zMigueel** [comment]
bom, formatei meu pc e infelizmente estou sem as logs, vou novamente baixar o modpack e jogar, caso ocorra os crashes, retorno aqui com as logs no pastebin

**Comment by ArtpokeBr** [comment]
ok.

**Comment by zMigueel** [comment]
Opa! Retornei aqui e tive o crash. https://ghostbin.com/paste/vwLBa
Só consegui mandar pelo ghostbin. Hastebin e pastebin possuem limites de envio.

**Comment by ArtpokeBr** [comment]
Q isso doido, se mandou só o Crash? pq normalmente o Pastebin consegue de boas kk

**Comment by zMigueel** [comment]
Mandei log toda, sabia não kk.

**Comment by ArtpokeBr** [comment]
vai na Crash reports, e copia e cola o txt mais recente, esse arquivo foca só no motivo do Crash.

**Comment by zMigueel** [comment]
Ok

**Comment by zMigueel** [comment]
Consegui resolver o problema (não sei como, mas só parou de congelar ou crashar) e estou conseguindo jogar novamente. Irei fechar a issue, obrigado pela atenção.

**Comment by ArtpokeBr** [comment]
Opa tranquilo, aproveite o Modpack :)
