### ISSUE TITLE
Mana Infused Ingot sem EMC

### ISSUE THREAD

**Issue by diamondcraft434** [ArtpokeBr/Minecraft-Ultimato#270]
**Versão do Modpack:**
1.0.4

**Descrição:**
Mana Infused Ingot sem EMC, oque torna a singularidade sem EMC, tranformando a singularidade ultimate sem EMC também, transformando o infinty catalyst sem EMC e deixando o infinty ingot junto com a armadura do avarita sem EMC. Fiz uma farm de EMC bolada e n adianta de nada. Tenho que ir minerar mana infused.

**Sugestão de Solução:**
Adicionar EMC no ingot e nos items posteriores

**Screenshots:**
https://user-images.githubusercontent.com/76217900/102629969-ae155e80-412a-11eb-884b-326e7362e89f.png
https://user-images.githubusercontent.com/76217900/102630733-abffcf80-412b-11eb-915b-3b4c427e54d6.png

**Comment by ArtpokeBr** [comment]
Atualize o Modpack. na versão 1.0.5 isso foi revertido acredito eu. e na verdade... meio triste que tu dependa de EMC tanto assim né....
