### ISSUE TITLE
Erro em servidor 

### ISSUE THREAD

**Issue by linezada** [ArtpokeBr/Minecraft-Ultimato#271]
**Versão do Modpack:**
1.0.6 server e cliente 

**Descrição:**
Servidor apresentando erro na recipe do between lands ( testei a versao 1.0.5 do modpack ta funcionando normalmente)

**Passo a Passo para chegar no Problema (Opcional):**
Fiz a atualização do servidor para a versão 1.0.6 pra garantir que eu tivesse instalado errado fiz a instalação 2 vezes e instalação limpa do server 

**Screenshots:**
![image](https://user-images.githubusercontent.com/75906200/102655062-6a355000-4150-11eb-9cf2-63df11792035.png)
novo erro tbm 
![image](https://user-images.githubusercontent.com/75906200/102655691-7f5eae80-4151-11eb-8092-f952ce35940b.png)

**Comment by FilipeFerrary** [comment]
Também estou com esse mesmo erro! Na versão 1.0.6

**Comment by linezada** [comment]
e na 1.0.5 parece estar com problemas da geraçao de mundo e a dimensão dos dragoes n ta indo eu tava testando hj vo te q jogar na 1.0.4

**Comment by ArtpokeBr** [comment]
Não era para haver nenhum problema de geração de mundo viu. antes de reclamar confira se a configuração de geração de Mapa do seu Server está correta.

**Comment by linezada** [comment]
eu usei a versao 1.0.5 do server pack eu ate tentei fazer outro mundo mas a dimensao dos dragoes n foi gerada so tinha os ninhos dos dragoes pelo void

**Comment by ArtpokeBr** [comment]
o Código de Geração de Mundo estava como? certinho né? pois justamente não sou eu que mantenho as Server files kkkk

**Comment by linezada** [comment]
![image](https://user-images.githubusercontent.com/75906200/102702088-74814800-423d-11eb-95ad-307578624ef8.png)
ta ai na 1.0.4 eu tava de boa so nessa ta dando isso

**Comment by linezada** [comment]
eu achava q o grue tava bugado entao qnd eu mudei pra 1.0.5 eu fiz um mapa novo

**Comment by ArtpokeBr** [comment]
Então, estou vendo justamente, o Problema está ali nas Generator Settings =/  {"Topography-Preset":"overworld"} coloca só isso que deve resolver.

**Comment by linezada** [comment]
a entendi vlw entao

**Comment by willmb** [comment]
Conseguiu arrumar o erro das Screenshots? Estou com o mesmo erro aqui.

**Comment by ArtpokeBr** [comment]
Só deixando claro gente 
![image](https://user-images.githubusercontent.com/44851727/102719242-b5c03900-42cb-11eb-95e6-1ff34d2a35d5.png) Já upei a versão corrigida dos arquivos de Server, que no caso é só as Generator Settings que nem eu falei ali.

**Comment by linezada** [comment]
alguem conseguiu resolver o erro dos prints la em cima ?
