### ISSUE TITLE
[Dúvida] Geração de estruturas

### ISSUE THREAD

**Issue by RelryPeSan** [ArtpokeBr/Minecraft-Ultimato#274]
Opa, queria apenas tirar uma duvida quanto ao modpack amigo ai dps pode fechar essa issue. eu consigo reativar a geração das estruturas como as vilas atraves das configurações? tentei dar uma fuçada nos arquivos, mas ainda não tive muito sucesso kkkk

**Comment by ArtpokeBr** [comment]
Nope, vilas são devastadas pelo Thanos ent elas n geram n.
