### ISSUE TITLE
Modepack crash ao entrar

### ISSUE THREAD

**Issue by batroffdan** [ArtpokeBr/Minecraft-Ultimato#276]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
versão ultimato

**Descrição:**
modpack trava ao entrar e aparce um erro do topograph

**Crash Log:**
crash-2020-12-19_00.54.07-server.txt

**Screenshots:**

![e6764566-6f2e-45aa-8c04-75d735fa1d10](https://user-images.githubusercontent.com/76253383/102690785-98fe0580-41e6-11eb-936f-920a18b95a35.jpg)

**Comment by ArtpokeBr** [comment]
Mande o Crash.

**Comment by batroffdan** [comment]
Ele não tá gerando

**Comment by batroffdan** [comment]
![Uploading 16084359539231334693270484775889.jpg…]()

**Comment by ArtpokeBr** [comment]
Como que ele não tá gerando? se apareceu na tela ali quer dizer que gerou kkk

**Comment by batroffdan** [comment]
me expresse mal, não consigo abrir o link ta dando erro e nao ta gerando pra abrir, mais pode deixar eu começei outro, quria saber so como ativa o chunk loading do flux networks
