### ISSUE TITLE
Metal Press - TechGuns - Não tem

### ISSUE THREAD

**Issue by MastergamesT00** [ArtpokeBr/Minecraft-Ultimato#277]
No modpack o mod do techguns não tem a máquina Metal Press! Eu não estou a jogar mas o SoldierBr, está a jogar e para mexer com a armadura de Power do Techguns necessita-se da Metal Press do techguns porque ela é a única com a recipe que o Soldier precisa.

Obrigado pela atenção Art.

**Comment by ArtpokeBr** [comment]
Já foi corrigido, atualize o Modpack no seu caso. mas em específico do caso do S0ldier é só pelo fato de que demora um poquito pra entrar no Server oficial, mas esse problema já foi corrigido. vou fechar.
