### ISSUE TITLE
meu modpack esta sem o balde de lava.

### ISSUE THREAD

**Issue by Inffamous** [ArtpokeBr/Minecraft-Ultimato#279]
**Versão do Modpack:**
Minecraft Ultimato-1.0.6

**Descrição:**
O meu modpack esta sem o item lava bucket

**Passo a Passo para chegar no Problema (Opcional):**
Estava construindo uma fornalha do tinkers porem quando fui pegar a lava com um balde eu notei que não estava funcionando então tentei pesquisar o item no JEI notei que não tinha ele lá. Tentei recriando o mundo e reinstalando o modpack mas o problema persistiu.

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5720237/latest.log)

**Screenshots:**
![bug mine](https://user-images.githubusercontent.com/76267640/102701163-e2744200-4232-11eb-83ba-4d658c335d5f.PNG)

**Comment by ArtpokeBr** [comment]
Simplesmente não faz sentido você não conseguir pegar um balde de lava, o Balde está escondido do JEI Apenas, por motivos de Optimização, na print você está no Survival, entao é só achar uma poça de lava para pegar ou fazer os métodos normais para se conseguir lava ué .

**Comment by Inffamous** [comment]
> Simplesmente não faz sentido você não conseguir pegar um balde de lava, o Balde está escondido do JEI Apenas, por motivos de Optimização, na print você está no Survival, entao é só achar uma poça de lava para pegar ou fazer os métodos normais para se conseguir lava ué .

Mas eu fiz um balde e tentei pegar porém a lava some e o balde continua vazio.

**Comment by ArtpokeBr** [comment]
Tem certeza que isto está acontecendo? por que não mandou um Vídeo? isso pode até ser problemas de Lag de TPS no seu mapa, por que isso é simplesmente bizarro kk

**Comment by Inffamous** [comment]
> Tem certeza que isto está acontecendo? por que não mandou um Vídeo? isso pode até ser problemas de Lag de TPS no seu mapa, por que isso é simplesmente bizarro kk

Apaguei todos os arquivos do Minecraft que tinha no meu PC e reinstalei e agora está normal.

**Comment by ArtpokeBr** [comment]
Então foi algo bizarro da sua instalação kkkk ai ai viu vou fechar ent.
