### ISSUE TITLE
Simple Powered Furnace e Simple Alloy Smelter não funcionam

### ISSUE THREAD

**Issue by joserobjr** [ArtpokeBr/Minecraft-Ultimato#28]
Não está dando para colocar itens nos slots de cima do Simple Powered Furnace e do Simple Alloy Smelter, tentei vários tipos de dusts, comidas, ores e nenhum foi.

O Alloy Smelter normal funciona

**Comment by ArtpokeBr** [comment]
Depois preciso dar uma Olhada no Github do EnderIO ou coisa parecida, por isso me parece Bug do Mod em si! então assim que possível irei solucionar!
