### ISSUE TITLE
Dimensão dos Dragões no void

### ISSUE THREAD

**Issue by ArthurRigotti** [ArtpokeBr/Minecraft-Ultimato#280]
Eu e meus amigos estamos jogando em um server nosso, até que nos deparamos com a dimensão dos dragões bugada, ela esta no void, tirando o spawn e os ninhos dos dragões (que estão flutuando em pleno void), tentamos apagar a data e region do dim 43 (que achamos que esta a dimensão problemática), mas não resolveu o problema, se conseguir nos ajudar ficaríamos muito agradecidos!

**Comment by ArthurRigotti** [comment]
Acho que já sei o problema de fato, no qual seria que o servidor não gerou o mundo no estilo ''Topography'' e sim no modo padrão do Minecraft, sendo assim bugando a dimensão

**Comment by FelipeAlafy** [comment]
> Acho que já sei o problema de fato, no qual seria que o servidor não gerou o mundo no estilo ''Topography'' e sim no modo padrão do Minecraft, sendo assim bugando a dimensão
> 

É necessário que o mundo seja gerado com o _Topography_, isso pois o mundo dos dragões se baseia em um mundo void, e usa o _topography_ para fazer o terreno.

**Comment by ArtpokeBr** [comment]
As Server Propeties fornecidas estavam com problemas, estou já dando Upload na versão mais atualizada, mas basicamente nas generator settings de seu servidor você precisar ter {"Topography-Preset":"overworld"} .
