### ISSUE TITLE
botania flores

### ISSUE THREAD

**Issue by higorguii** [ArtpokeBr/Minecraft-Ultimato#281]
não acho nenhuma flor do botania no mundo

**Comment by FelipeAlafy** [comment]
As flores do botânia estão desativadas, para evitar lag por geração de mapa e particulas. Entretanto você pode usar o
_floral fertilizer_ para gera-las.

**Comment by FelipeAlafy** [comment]
> As flores do botânia estão desativadas, para evitar lag por geração de mapa e particulas. Entretanto você pode usar o
> _floral fertilizer_ para gera-las.

**Comment by FelipeAlafy** [comment]
> não acho nenhuma flor do botania no mundo 

As flores do botânia estão desativadas, para evitar lag por geração de mapa e particulas. Entretanto você pode usar o
floral fertilizer para gera-las.
