### ISSUE TITLE
Bug - Mob Crusher(Industrial Foregoing)

### ISSUE THREAD

**Issue by Steaal** [ArtpokeBr/Minecraft-Ultimato#282]
Versão: A mais recente ( 20/12 não sei como ver.)

O Mob Crusher do Industrial Foregoing  quando mata esta dopando 50 cabeças quando mata um mob.

https://user-images.githubusercontent.com/76391012/102711772-f5226180-429a-11eb-911d-2ec85a21f5a2.mp4

**Comment by ArtpokeBr** [comment]
Definitivamente você não está na mais recente. Este é um bug que já foi corrigido na Atual Versão 1.0.6 do Modpack. atualize-se.
