### ISSUE TITLE
O modpack aparece com a versão errada no curse launcher

### ISSUE THREAD

**Issue by Nicolas-Plays** [ArtpokeBr/Minecraft-Ultimato#283]
**Versão do Modpack:**
versão 1.0.6

**Descrição:**
O erro é apenas estético, eu estou na versão 1.0.6 mas no launcher está escrito na capa do pack q é 1.0.4, sendo que na aba view  profile ele é 1.0.6

**Sugestão de Solução:**
Lembre de colocar a versão certa lá no manifest, eu sei q é trabalhoso de fazer, mas sempre que terminar de criar uma nova versão coloque o número da versão certo porque as pessoas podem confundir as versões.

Screenshot
![Design sem nome (14)](https://user-images.githubusercontent.com/75183967/102714890-86e89980-42b0-11eb-905b-aebf95a52eb6.jpg)

Espero que isso te ajude no desenvolvimento do modpack

**Comment by ArtpokeBr** [comment]
Eu não troquei no Manifest? vixe bem que eu tava achando estranho isso kkkk mas faz sentido! vou certificar-me de trocar o número no Manifest.
