### ISSUE TITLE
Meu MC Ultimato dá crash

### ISSUE THREAD

**Issue by R4P0N1KT** [ArtpokeBr/Minecraft-Ultimato#284]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
MC Ultimato 1.0.2

**Descrição**
Estou usando o MultMC, quando inicializo o ultimato aparece um "Minecraft Failed to start" depois um texto do crash, mas o crash não abre, vou anexar a imagem.

**Screenshots:**

![imagem_2020-12-20_132959](https://user-images.githubusercontent.com/76401730/102718542-74c62580-42c7-11eb-9c98-0f15da888ccc.png)

**Comment by ArtpokeBr** [comment]
Falta de Memória alocada, aloque mais. além de que, tem certeza que vai querer jogar na 1.0.2? atualize para a mais recente pls.
