### ISSUE TITLE
Erro ao tentar se juntar ao servidor

### ISSUE THREAD

**Issue by willmb** [ArtpokeBr/Minecraft-Ultimato#285]
1.0.6

Está dando o seguinte erro quando eu tento me juntar ao servidor recém criado assim que eu abro o jogo:

![Sem título](https://user-images.githubusercontent.com/63399435/102719677-13ee1b80-42ce-11eb-9310-512e71c2bd85.png)
![2](https://user-images.githubusercontent.com/63399435/102719687-29fbdc00-42ce-11eb-820c-65f184fb0a66.png)

Depois desse se eu tentar me juntar novamente da isso:

![3](https://user-images.githubusercontent.com/63399435/102719707-4bf55e80-42ce-11eb-962a-688d6a237c9b.png)

As mensagens do console do server são as mesmas da tentativa anterior, e pelo console do server estou usando 249 mods.

Crash report: 
[crash-2020-12-20_14.20.41-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5721248/crash-2020-12-20_14.20.41-client.txt)

Log: 
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5721251/latest.log)

**Comment by ArtpokeBr** [comment]
Betweenlands deu um bugzinho, tentou reinstalar o Pack? ou tentou talvez manualmente reinstalar o Mod da Betweenlands? (sem deletar as configs claro).;

**Comment by willmb** [comment]
Testei em outro PC, e tentei reinstalar o mod manualmente, ambas sem sucesso. Agora vou tentar reinstalar o pack.

**Comment by ArtpokeBr** [comment]
Ok, não é um problema novo, lembro de ter visto outros Reports, mas sinceramente n sei resolver.

**Comment by yMoririn45** [comment]
Boa tarde tou com o mesmo problema

**Comment by FilipeFerrary** [comment]
Também estou com o mesmo problema e por vezes fica "A iniciar sessão..." e muito tempo depois diz que "Tempo limite excedido"
![Client](https://user-images.githubusercontent.com/76233657/102723068-7579ae80-42fd-11eb-9601-76f426c6ff89.png)
![Server](https://user-images.githubusercontent.com/76233657/102723078-875b5180-42fd-11eb-8a6b-f43773d33e24.png)

**Comment by thiagoship** [comment]
Também estou com o mesmo problema, não sei o que fazer... já reinstalei umas 4x quanto o server quanto o jogo...

**Comment by yMoririn45** [comment]
resolvi o problema
 
 vai no serverstart.bat clicas com botão direito e depois clicas em editar e colocas:
 
 @ECHO OFF
java -Xms<ramminima>M -Xmx<rammaxima>M -jar forge-1.12.2-14.23.5.2854.jar nogui
pause


oque esta dentro de <> é so editar e colocar a ram

**Comment by smurfvegetariano** [comment]
alterei o serverstart.bat mas o problema continua

**Comment by yMoririn45** [comment]
@smurfvegetariano 
"
@echo OFF
java -Xms1024M -Xmx2048M -jar forge-1.12.2-14.23.5.2854.jar nogui
pause
"
coloque assim
se o seu pc tiver muita ram so aumentar a ram
é so copiar e colar no codigo em cima
1gb /   -Xmx1024M -Xms1024M
2gb /   -Xmx2048M -Xms2048M
3gb /   -Xmx3072M -Xms3072M
4gb /   -Xmx4096M -Xms4096M
5gb /   -Xmx5120M -Xms5120M
6gb /   -Xmx6144M -Xms6144M
7gb /   -Xmx7168M -Xms7168M
8gb /   -Xmx8192M -Xms8192M
9gb /   -Xmx9216M -Xms9216M
10gb / -Xmx10240M -Xms10240M
11gb / -Xmx11264M -Xms11264M
12gb / -Xmx12288M -Xms12288M
13gb / -Xmx13312M -Xms13312M
14gb / -Xmx14336M -Xms14336M
15gb / -Xmx15360M -Xms15360M
16gb / -Xmx16384M -Xms16384M

**Comment by thiagoship** [comment]
> @smurfvegetariano
> 
> @echo OFF
> java -Xms1024M -Xmx2048M -jar forge-1.12.2-14.23.5.2854.jar nogui
> pause
> 
> coloque assim
> se o seu pc tiver muita ram so aumentar a ram
> é so copiar e colar no codigo em cima
> 1gb / -Xmx1024M -Xms1024M
> 2gb / -Xmx2048M -Xms2048M
> 3gb / -Xmx3072M -Xms3072M
> 4gb / -Xmx4096M -Xms4096M
> 5gb / -Xmx5120M -Xms5120M
> 6gb / -Xmx6144M -Xms6144M
> 7gb / -Xmx7168M -Xms7168M
> 8gb / -Xmx8192M -Xms8192M
> 9gb / -Xmx9216M -Xms9216M
> 10gb / -Xmx10240M -Xms10240M
> 11gb / -Xmx11264M -Xms11264M
> 12gb / -Xmx12288M -Xms12288M
> 13gb / -Xmx13312M -Xms13312M
> 14gb / -Xmx14336M -Xms14336M
> 15gb / -Xmx15360M -Xms15360M
> 16gb / -Xmx16384M -Xms16384M

Jovem, vc está abrindo servidor local no caso? Eu uso o PurpleHost, ele já muda automaticamente...

**Comment by smurfvegetariano** [comment]
sim, é servidor local, será por isso? a configuração do serverstart.bat estava correta, estou disponibilizando 4gb dos 16 do pc...

**Comment by smurfvegetariano** [comment]
não sei se ajuda, mas quando crio um mundo local aparece a seguinte mensagem: 
![Captura de tela 2020-12-22 105459](https://user-images.githubusercontent.com/70596733/102895907-55a0d280-4444-11eb-980b-ce1374810ca6.png)

**Comment by thiagoship** [comment]
> sim, é servidor local, será por isso? a configuração do serverstart.bat estava correta, estou disponibilizando 4gb dos 16 do pc...
> 
> (notei que antes de me desconectar, o servidor dá a seguinte mensagem: "Skipping config sync, No mods have registered a syncable config.")

Acho que sim, eu n consegui de jeito nenhum... Eu consegui upando a versão 1.0.4, melhor do que ficar fazendo nada

**Comment by Christtiann** [comment]
Solução...
O modpack de vcs e o server nao estao com a mesma config...
Baixe a versao atual do modpack, pegue a pasta config e coloque no server :/

**Comment by smurfvegetariano** [comment]
> > sim, é servidor local, será por isso? a configuração do serverstart.bat estava correta, estou disponibilizando 4gb dos 16 do pc...
> > (notei que antes de me desconectar, o servidor dá a seguinte mensagem: "Skipping config sync, No mods have registered a syncable config.")
> 
> Acho que sim, eu n consegui de jeito nenhum... Eu consegui upando a versão 1.0.4, melhor do que ficar fazendo nada

a 1.0.4 funcionou aqui!

**Comment by smurfvegetariano** [comment]
> Solução...
> O modpack de vcs e o server nao estao com a mesma config...
> Baixe a versao atual do modpack, pegue a pasta config e coloque no server :/

tentei aqui mas não rolou, deu o mesmo erro...
