### ISSUE TITLE
Erro ao entrar no servidor

### ISSUE THREAD

**Issue by yMoririn45** [ArtpokeBr/Minecraft-Ultimato#287]
**Nota**: ERRO

**Versão do Modpack:**
1.0.6

**Descrição:**
Dá um erro quando se entra no servidor ja reinstalei varias vezes o pack e nada!

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5721392/latest.log)

**Screenshots:**
![1](https://user-images.githubusercontent.com/76406330/102722616-3564fc80-42fa-11eb-97bc-fff2a2c75305.png)
![download](https://user-images.githubusercontent.com/76406330/102722617-35fd9300-42fa-11eb-8450-6c875d79dee2.png)

**Comment by smurfvegetariano** [comment]
mesma versão, mesmo erro idêntico, tb já reinstalei e nada...

**Comment by pedrosodre** [comment]
O mesmo aqui, somente pra comentar na _issue_ correta :)

**Comment by Christtiann** [comment]
Solução...
O modpack de vcs e o server nao estao com a mesma config...
Baixe a versao atual do modpack, pegue a pasta config e coloque no server :/

**Comment by pedrosodre** [comment]
@Christtiann não resolve o problema. Testei baixar o modpack 1.0.6 e a versão de servidor 1.0.6, depois usar os mods e config do servidor no cliente e vice-versa. O erro é o mesmo: "Fatally missing registry entries".

**Comment by Christtiann** [comment]
@pedrosodre vc esta fazendo alguma coisa errada, pois erro de "Fatally missing registry entries" é por causa da pasta config nao esta sincronizada com o do client

**Comment by pedrosodre** [comment]
@Christtiann não sei se tem muito jeito de errar isso, pelo o que você tá falando é não usar a _config_ do .zip do server, mas sim a do cliente.

**Comment by Christtiann** [comment]
@pedrosodre é para isso mesmo, nao use o do server

**Comment by pedrosodre** [comment]
@Christtiann foi o que fiz, infelizmente não funcionou.

**Comment by emmanoel1** [comment]
exatamente o mesmo erro do meu mano
