### ISSUE TITLE
APARENTEMENTE BUG COM O INDUSTRIALCRAFT2

### ISSUE THREAD

**Issue by StroiterS2** [ArtpokeBr/Minecraft-Ultimato#289]
**Versão do Modpack:**
1.0.6

**Descrição:**
SEMPRE QUE EU INICIO O MODPACK FICA DANDO ERRO COM O INDUSTRIAL CRAFT 2

**Passo a Passo para chegar no Problema (Opcional):**
Eu baixei tudo certinho de acordo com o video quando termino de baixar os mods carregando apareceu a tela que eu mandei ali embaixo da screenshots

**Screenshots:**
![unknown](https://user-images.githubusercontent.com/76408839/102724374-eadd8300-42ed-11eb-92bc-d24cdbd08f24.png)

**Comment by ArtpokeBr** [comment]
Aloque mais RAM, esse tipo de problema ocorre por falta dela.
