### ISSUE TITLE
Vila não-gerada

### ISSUE THREAD

**Issue by C3sarB1ts** [ArtpokeBr/Minecraft-Ultimato#29]
Olha eu aqui de novo, hehe. No mundo "topography", pelo visto sempre nascemos ao lado de um meteoro e de algo que deveria ser uma vila. Mas só tem as estradas, nenhuma estrutura kkkkkkkk. É normal?

**Comment by ArtpokeBr** [comment]
Vilas não estarem gerando infelizmente é um probleminha com o Topography mesmo, então para contornar isso os Ovos de Spawn de villagers são craftáveis.

**Comment by ArtpokeBr** [comment]
Vou fechar ent pois é algo já infelizmente pensado kk
