### ISSUE TITLE
Crash Report Vindicator

### ISSUE THREAD

**Issue by klaustoy** [ArtpokeBr/Minecraft-Ultimato#290]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.12.2

**Descrição:**
Eu estava simplesmente jogando o modpack, quando do nada eu mato um Vindicador e meu minecraft da crash. O que posso fazer para arrumar, por favor me ajude. Quando estava ledo o Crash Log, estava dizendo algo sobre (Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP) GcEntityPlayerMP. Não sei se tem algo a ver, mas tento ajudar. Quando deu Crash, apareceu que havia dois mods suspeitos. Suspected Mods: Quality Tools (qualitytools), LagGoggles (laggoggles)  Quando puder me retornar, agradeço!. Bom dia.

**Sugestão de Solução:**

**Passo a Passo para chegar no Problema (Opcional):**

**Crash Log:**
[crash-2020-12-20_20.03.18-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5721581/crash-2020-12-20_20.03.18-server.txt)

**Screenshots:**

**Comment by ArtpokeBr** [comment]
Está em qual versão do Modpack? eu corrigi recentemente um problema que era basicamente um Crash ao pegar um Totem of Undying na mão. então certifique-se de atualizar o Modpack para a versão mais recente.

**Comment by klaustoy** [comment]
eu estou jogando na 1.12.2

**Comment by ArtpokeBr** [comment]
Versão do Modpack, não versão do Mine. para atualizar estando na curse é só clicar no botão update ué kkk estando no MultiMC, baixe na página do Modpack a versão mais recente.

**Comment by klaustoy** [comment]
![image](https://user-images.githubusercontent.com/76183845/102726680-89beab00-42ff-11eb-86f0-6ca40f85de56.png)

**Comment by klaustoy** [comment]
Acho que já está atualizado o modpack

**Comment by ArtpokeBr** [comment]
Leia o que está escrito. você está com a versão atual na 1.0.4 seleciona a 1.0.6 e atualize para ela. (Tá escrito ali poxa, Current significaria oq? kkkk) mas só uma dica, certifique-se de fazer Backup do seu mapa para não correr riscos de perde-lo durante o Update.

**Comment by klaustoy** [comment]
Paguei de bobo kkkk, valeu irmão! Só uma coisa, no estilo de criação de mapa, eu criei como REALISTIC e quando fui há dimensão dos Dragões, era um void com apenas os blocos do ninho do dragão e os dragões. Quando fui criar em um outro modo sem ser o REALSITIC, estava normal. Continuando no REALISTIC, todas as vilas de Villares, só haviam as estradas, nada mais. Casas e os próprios Villares não estavam lá.  (não sei se precisa criar outro issue, mas só para perguntar)
