### ISSUE TITLE
Socorro me ajuda

### ISSUE THREAD

**Issue by PleaseSendHelps** [ArtpokeBr/Minecraft-Ultimato#294]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.5

**Descrição:**
Então meu caro, o problema é que quando eu tento mudar a memória ram mínima e máxima, o multi mc dá problemas e não me permite passar de 1280 mb. Eu já tentei mudar pra gb, e logo percebi que não dava, então eu tentei mudar pra 4096 mb (o prefixo mínimo de 4 gb lá), e deu erro e eu não consegui iniciar o modpack nessa versão, assim como na versão 1.0.2, que deu o mesmo problema de eu ter sido impossibilitado de mudar a memória ram que eu queria usar no mc ultimato e não conseguir iniciar o modpack. Eu sinceramente acredito que isso seja algo do multi mc, sei lá, mas bom, obrigado pela compreensão e pela atenção.

**Sugestão de Solução:**
Substitua este texto por uma possível solução que você acha que possa ser feita para o seu problema! isto ajuda pois muitas vezes sua sugestão pode ser boa e pode ser implementada e resolvida rápidamente! 

**Passo a Passo para chegar no Problema (Opcional):**
Nas opções de memória ram mínima e máxima da versão atual do mc ultimato, eu tento mudar para a memória recomendada, o que dá problema e me impossibilita de iniciar o modpack na memória ram recomendada, e claro, mesmo que o launcher inicie na memória de 1280 mb, ele começa e logo fecha automaticamente por falta de memória.

**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest".

**Screenshots:**
![image](https://user-images.githubusercontent.com/76417498/102737385-0a909d80-4326-11eb-9a87-cf94323a59ae.png)
![image](https://user-images.githubusercontent.com/76417498/102737403-15e3c900-4326-11eb-9391-f7ed8ccd011d.png)

**Comment by ArtpokeBr** [comment]
Quanto de RAM você tem no PC? provavelmente o MultiMC não deixa você alocar mais RAM por conta do total no PC ou até mesmo pelo Java estar desatualizado.

**Comment by PleaseSendHelps** [comment]
> Quanto de RAM você tem no PC? provavelmente o MultiMC não deixa você alocar mais RAM por conta do total no PC ou até mesmo pelo Java estar desatualizado.

Opa, tudo certo? Então, o meu pc tem 8 gb de ram, e eu consegui consertar o erro, foi só desinstalar o java e reinstalar ele pra que a pasta do java fosse completamente reconhecida pelo multimc. Valeu aí cara, agora dá pra jogar mine com mods, obrigado pela atenção e pela ajuda!!!
