### ISSUE TITLE
Spongeforge

### ISSUE THREAD

**Issue by L1ttleSenpa1** [ArtpokeBr/Minecraft-Ultimato#295]
**Versão do Modpack:**
Ultima

**Descrição:**
Queria adicionar plugins ao meu servidor e gostaria de saber qual versão do spongeforge usar, pois já experimentei varias e tá sempre a dar crash. 

**Sugestão de Solução:**
Colocar o spongeforge nos server files.

**Comment by ArtpokeBr** [comment]
Ih rapaiz, eu manjo 0 de servidores. acredito que as server files venham com um tal de Magma, se n vem, acho que recomendaria por que o server oficial usa o Magma pra n ter lag e etc.

**Comment by Christtiann** [comment]
@L1ttleSenpa1 não é compatível com o sponge, nem adianta tentar

**Comment by Focamacho** [comment]
@L1ttleSenpa1 Eu utilizo sponge normalmente, porém para usar você tem que desativar uma config do HammerCore.
Ela fica em uma pasta chamada "asm" (não é dentro da pasta configs, é dentro da própria pasta principal do servidor)
É só editar o arquivo dentro dessa pasta, alterando o "World.ITickable.Override" de true para false.
