### ISSUE TITLE
mundo dos dragões

### ISSUE THREAD

**Issue by AnonimoPlayer** [ArtpokeBr/Minecraft-Ultimato#296]
**Descrição:** quando abra o mundo dos dragões fica somente um void

**Comment by ArtpokeBr** [comment]
Gerou o Mapa com qual preset? o correto é usar o Topography. está em servidor? se estiver confira se lá está com as opções de geração corretas e etc.

**Comment by titanjunior54** [comment]
sim, para mim tb da isso, eu estou na configuração normal do topography

**Comment by Hirothewolf** [comment]
> Gerou o Mapa com qual preset? o correto é usar o Topography. está em servidor? se estiver confira se lá está com as opções de geração corretas e etc.

curiosamente com o void islands o mapa dos dragões não spawna

**Comment by ArtpokeBr** [comment]
"Curiosamente na Void Islands" kkkk gente, sem o Topography rodando direito a dim de drags não existe mesmo, afinal, ele é o controlador da geração.

**Comment by ArtpokeBr** [comment]
> sim, para mim tb da isso, eu estou na configuração normal do topography

Está em Servidor?

**Comment by titanjunior54** [comment]
não estou

**Comment by ArtpokeBr** [comment]
> não estou

Manda uma Print então da configuração que está no seu Topography. só entrar na pasta configs e procurar por outra pasta chamada Topography, lá vai ter um txt com o mesmo nome, abra-o e me manda uma print do que está escrito.

**Comment by titanjunior54** [comment]
[
![Captura de Tela (30)](https://user-images.githubusercontent.com/75854531/102995013-ed62f700-44fe-11eb-810f-4137e2d6620c.png)
](url)

**Comment by ArtpokeBr** [comment]
Bom, não parece que você tenha mexido em nada, então sinceramente... não sei oq deu no teu jogo. criando um Mapa com a geração do Topography e entrando no Portal dos Dragões deveria funcionar.

**Comment by XpGameOfi** [comment]
![image](https://user-images.githubusercontent.com/75840249/103169520-1e9f3800-481b-11eb-8a32-776c1e7eb86d.png)
o meu mundo esta assim

se eu apaga a pasta dim43 , não gera outro mundo e fica um mundo void

e foda e que ja estou tao avançado no meu mundo :(
