### ISSUE TITLE
Erro de inicialização no CurseForge.

### ISSUE THREAD

**Issue by ImReturn** [ArtpokeBr/Minecraft-Ultimato#297]
**Versão do Modpack:**
1.12.2

**Descrição:**
Basicamente eu fui instalar e jogar o Modpack, porém simplesmente o mesmo não quis inicializar com o CurseForge, não sei outro "programa" que eu possa tentar. Já reinstalei, fiz de tudo porém o problema permanece!

**Sugestão de Solução:**
Para mim, seria bom haver um launcher oficial de vossa autoria, sei que é complicado, mais é uma possível solução do problema.

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5724609/latest.log)

**Screenshots:**
https://prnt.sc/w76ib9
https://prnt.sc/w76ivl

**Comment by ArtpokeBr** [comment]
A Mensagem ali do Launcher oficial da Mojang é só ignorar primeiramente, e segundo que, provavelmente oq está acontecendo é só falta de Alocação de RAM. quanto você alocou pro Modpack?

**Comment by ImReturn** [comment]
4069M, quanto recomenda?

**Comment by ArtpokeBr** [comment]
4 é pouco, o recomendável pro Modpack é entre 5 e 6GB.

**Comment by ImReturn** [comment]
Certo, aloquei 5,5GB e permanece sempre o mesmo erro, alguma recomendação?

**Comment by ArtpokeBr** [comment]
Java tá Atualizado?

**Comment by ImReturn** [comment]
Sim.
