### ISSUE TITLE
Error Download TheBetweenlands

### ISSUE THREAD

**Issue by Daniel-code15** [ArtpokeBr/Minecraft-Ultimato#298]
**Versão do Modpack:**
12/18/2020 - Minecraft Ultimato-1.0.6.zip

**Descrição:**
Eu estou tentando baixar o modpack há dias, mas nunca consigo, sempre que estou baixando ele fica demorando baixar o mod TheBetweenlands, e logo após ele da um erro dizendo "Timeout attemping to download: https://media.forgecdn.net/files/3099/119/TheBetweenlands-3.7.1-universal.jar"

**Sugestão de Solução:**
Não tenho uma solução, procurei na internet e parece que muitos com internet fraca tem problemas com esse mod ao baixar

**Passo a Passo para chegar no Problema (Opcional):**
Abra a pagina do modpack no CurseForge, e coloque para baixar. quando entre os mods 190 e 200 ele irá dar o erro

**Crash Log:**
Nenhum crash gerado

**Screenshots:**
![image](https://user-images.githubusercontent.com/46878004/102839577-e7dbb300-4411-11eb-92bd-08eb9ffe7a31.png)

**Comment by ArtpokeBr** [comment]
Olha, infelizmente não posso fazer nada. esse é o tipo de problema que eu sugiro a você abrir um Ticket de Suporte ou reportar para a Curse. isso é coisa do Launcher e não do Modpack :T sinto muito.
