### ISSUE TITLE
Erro ao abrir no CurseForge

### ISSUE THREAD

**Issue by Crazy71U** [ArtpokeBr/Minecraft-Ultimato#299]
Descrição:
Não consigo baixar o modpack, sempre que eu tento baixar chega no mod TheBetweenlands 3.7.1 o download para e aparece tal mensagem 

https://prnt.sc/w823ob

**Comment by ArtpokeBr** [comment]
Infelizmente problemas do Beta da Curse talvez? não sei como resolver e sinceramente está fora do meu campo de resolução :T, recomendo baixar o RAR bruto no site da curse importar pro MultiMC.
