### ISSUE TITLE
Mob Masher Dropa Muitas Cabeças

### ISSUE THREAD

**Issue by Vienna943** [ArtpokeBr/Minecraft-Ultimato#3]
O item ''Mob Masher'' do mod ''mob grinding utils'' esta com upgrades meio quebrados, o upgrade ''beheading'' que era pra droppar mais cabeça nao aumenta a chance de drop de cabeça, POREM sem upgrade NENHUM vc ja dropa  50 cabeças de qualquer mob do vanilla(e é sempre essa quantidade), sendo assim: zombie,skeleton,creeper,enderman e nao sei se tem mais pq n testei, e se vc por 10upgrades de LOOTING esse numero sobe pra exatamente 300 cabeças SEMPRE e como as cabeças tem em torno de 20-30k(e 65k a de enderman) de emc isso faz com q esse item faça vc juntar quantidades MONSTRUOSAS de emc em um early game mt facilmente, sem contar q 300cabeças pra **CADA** mob é 4packs e 44 de itens e isso pode impactar bastante em mobtraps e inclusive na serie ja q vai ter muitos participantes

**Comment by Christtiann** [comment]
Reportando o mesmo bug tbm @ArtpokeBr 
![image](https://user-images.githubusercontent.com/54782518/100492097-f7fcbd00-3107-11eb-97a7-204a765ec196.png)
