### ISSUE TITLE
Server error java.lang.illegalStateException

### ISSUE THREAD

**Issue by rconstrutor** [ArtpokeBr/Minecraft-Ultimato#300]
**Versão do Modpack:**
1.0.4

**Descrição:**
Abri um servidor para jogar com os amigos e ninguem consegue entrar

![image](https://user-images.githubusercontent.com/76498131/102936658-50b14280-4487-11eb-935d-11490a45cdff.png)

**Comment by pedrosodre** [comment]
@rconstrutor remover o mod "FastWorkbench" resolveu com esse erro no meu cliente, mas passou a dar outro problema: "Fatally missing registry entries".

**Comment by ArtpokeBr** [comment]
E outra coisa grave, atualize o Modpack né... eu não tenho condições de ficar dando Suporte pra gente com Modpack desatualizado :T

**Comment by pedrosodre** [comment]
@ArtpokeBr meus testes foram no 1.0.6

**Comment by ArtpokeBr** [comment]
> @ArtpokeBr meus testes foram no 1.0.6

kkkk no seu caso pode ter sido, mas o cara que reportou tá desatualizado né.

**Comment by pedrosodre** [comment]
@ArtpokeBr sim, haha. Mas de todo modo, tem ideia sobre o problema que comentei? Ou prefere que eu abra outra issue?

**Comment by Christtiann** [comment]
Solução...
O modpack de vcs e o server nao estao com a mesma config...
Baixe a versao atual do modpack, pegue a pasta config e coloque no server :/

**Comment by emmanoel1** [comment]
@ArtpokeBr Estou tendo o mesmo problema, estou na versão 1.0.6 e o server files também ta na 1.0.6 Dando o mesmo erro
