### ISSUE TITLE
Como atualizar meu server para a versão mais recente ?

### ISSUE THREAD

**Issue by padilhozo** [ArtpokeBr/Minecraft-Ultimato#301]
Olá, eu gostaria de saber como atualizar meu server. Estou curtindo muito o modpack!

**Comment by ArtpokeBr** [comment]
no caso de atualizar um Servidor, primeiro recomendo fazer Backup do Mapa para não ter nenhum risco, depois só deletar todas as pastas que viriam normalmente no Update, ou seja, Mods, Configs, Scripts, Resources e respectivamente colocar as versões mais recentes destas pastas.

**Comment by padilhozo** [comment]
VALEU!
