### ISSUE TITLE
Reinforced Stone sem craft 

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#303]
**Versão do Modpack:**
1.0.6
**Descrição:**
Reinforced Stone sem craft 
![image](https://user-images.githubusercontent.com/54782518/102967933-bb876b80-44d1-11eb-856b-860359873760.png)

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
Reinforced Stone tem craft sim, a questão é que o IC2 novo você faz ela de uma forma diferente. precisa fazer um CF Sprayer, preencher ele com um líquido específico lá e usar ele num scaffold do IC2, isso vai gerar uma Reinforced Stone.

**Comment by Christtiann** [comment]
Nao sabia :'(
