### ISSUE TITLE
Quantum compressor não está internalizando itens

### ISSUE THREAD

**Issue by Mataiziu** [ArtpokeBr/Minecraft-Ultimato#304]
**Versão do Modpack:**
1.0.6

**Descrição:**
Fiz o quantum compressor, coloquei o ultimate catalyst na esquerda, coloquei o máximo de energia, quando coloco os itens (no caso coloquei carvão) dentro da maquina ele não entra, só fica como se fosse um item no baú.

**Sugestão de Solução:**
Não tenho certeza, mas pode ser um erro na config da maquina.

**Screenshots:**
https://imgur.com/Ei9zsOu

**Comment by ArtpokeBr** [comment]
Tenta quebrar e Colocar dnv ou no caso talvez você tenha clicado no Cadeado ali e travado? mas no geral já aconteceu com outros então tenta só quebrar e colocar dnv que as vezes resolve.
