### ISSUE TITLE
Versão do Modpack

### ISSUE THREAD

**Issue by Luuscaa** [ArtpokeBr/Minecraft-Ultimato#305]
**Versão do Modpack:**
1.0.6 ou 1.0.4

**Descrição:**
Olá! Meu "problema" pode ser só algo estético ou algo parecido, em relação a versão do Modpack, pois como disse acima, não sei se a versão do mesmo é 1.0.6 (última) ou 1.0.4 (como mostra na capa do Modpack), como mostra na print 1 e 2.

**Sugestão de Solução:**
- -

**Passo a Passo para chegar no Problema (Opcional):**
Basicamente, aparece na capa do Modpack que a versão do jogo é 1.0.4, mas na "atual" mostra que e a 1.0.6. Mando esse questionamento pois fiquei preocupado e não ter todo o conteúdo atualizado para poder jogar o jogo sem nenhum erro.

**Crash Log:**
- -

**Screenshots:**
Print 1: https://prnt.sc/w8nol6
Print 2: https://prnt.sc/w8novc
Print 3: https://prnt.sc/w8np35

**Comment by ArtpokeBr** [comment]
Ah sim, isso foi só um Problema que aconteceu quando eu Upei a versão mais recente, no Arquivo interno esqueci de atualizar o Número. mas fica tranquilo que é só Estético ali no Launcher. o Número verdadeiro sempre fica na hora lá de ver ao atualizar ;p
