### ISSUE TITLE
ñ conigo baixar o mod MC Ultimato

### ISSUE THREAD

**Issue by gustagamer33** [ArtpokeBr/Minecraft-Ultimato#306]
](url)
![image](https://user-images.githubusercontent.com/76534807/103030238-23719c80-453a-11eb-945d-15f2c29f203c.png)

**Comment by ArtpokeBr** [comment]
Problema na Curse, não meu :T não posso fazer nada. qualquer coisa se o Erro persistir, baixe o RAR na página do Modpack e importa pro Launcher manualmente.
