### ISSUE TITLE
Abrir o Modpack

### ISSUE THREAD

**Issue by Luuscaa** [ArtpokeBr/Minecraft-Ultimato#307]
**Versão do Modpack:**
1.0.6

**Descrição:**
Olá novamente! Antes de tudo, agradeço a resposta rápida da minha última dúvida.
A questão de agora, pra simplificar, é que pra eu conseguir jogar o Modpack, logo depois que aperto qualquer um dos botões de "Play" indicados nas prints 1 e 2, precisava finalizar a tarefa em segundo plano do "Minecraft Launcher", para assim o Modpack começar a carregar pra entrar no jogo.
Fui tentar abrir hoje, e quando cliquei em "Jogar" no launcher, apareceu um aviso dizendo que "Uma sessão já foi iniciada com esse usuário", como mostra na print 3. Clico em "Iniciar mesmo assim", o launcher fecha e ele nem aparece mais em segundo plano, e como consequência, o jogo nem carrega.

**Sugestão de Solução:**
Acho que pode ser resolvido reinstalando o Modpack, deslogando e logando novamente na minha conta, mas por via das dúvidas e pra informar meu problema, achei melhor perguntar aqui.

**Passo a Passo para chegar no Problema (Opcional):**
- -

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5736853/latest.log)

**Screenshots:**
Print 1: https://prnt.sc/w8o14h
Print 2: https://prnt.sc/w8o1jz
Print 3: https://prnt.sc/w8o2qp

**Comment by ArtpokeBr** [comment]
Hmm, deve ser alguma coisa relacionada ao seu Mine, tenta reparar a Instância nas configurações ela.

**Comment by Luuscaa** [comment]
> Hmm, deve ser alguma coisa relacionada ao seu Mine, tenta reparar a Instância nas configurações ela.

Descobri que o erro era mais profundo do que eu imaginava, acabei de formatar o Notebook e tá tudo certo, obrigado mais uma vez o/
