### ISSUE TITLE
Queda de FPS

### ISSUE THREAD

**Issue by PagaiME7142** [ArtpokeBr/Minecraft-Ultimato#309]
Eu baixei ontem o modpack do Minecraft Ultimato e o meu PC roda-o normalmente a 60FPS, mas do nada trava por uns segundos e volta ao normal, repetidamente. Por exemplo, estou normalmente a andar, ou a partir algum bloco e trava por uns segundos, depois volta ao normal. Não importa quanto baixe os gráficos ou reinicie o PC e o Minecraft, o problema continua...

Meu PC:
Processador: AMD Ryzen 5 4600H - 3.00GHz
Placa de Vídeo: NVIDIA Geforce GTX 1650
RAM: 8GB

**Comment by ArtpokeBr** [comment]
Quanto de RAM Alocada pro Modpack?

**Comment by PagaiME7142** [comment]
Como se vê isso?

**Comment by ArtpokeBr** [comment]
Ué, quando você abre o jogo mesmo, nunca reparou na barra de loading de memória acima? quanto está alocado? dá pra ver pelas configurações da Instância tbm.

**Comment by PagaiME7142** [comment]
3641 MB

**Comment by ArtpokeBr** [comment]
> 3641 MB

Muito Pouco, sobre pra 5 e poco.

**Comment by PagaiME7142** [comment]
Problema resolvido, obrigado!
