### ISSUE TITLE
Mine nao abrindo depois de iniciar uma vez.

### ISSUE THREAD

**Issue by vaperemoji** [ArtpokeBr/Minecraft-Ultimato#310]
Versão do Modpack:
1.0.6

Descrição:
Seguinte, eu abri o modpack pela primeira vez no curseforge normalmente, fechei o launcher e fui fazer outra coisa, na próxima vez que fui entrar, aparecia que a mesma instancia já estava aberta. Foi aí que eu descobri que dá primeira vez que você abre o modpack ele meio que salva um processo de Java, e só procurar nos processos vai estar em último, quando você exclui aquele processo, você pode jogar normalmente o modpack
Sugestão de Solução:
talvez seja algum problema no launcher da curseforge mesmo, pois quando rodo no multimc ele roda mais ou menos direitinho

Só queria falar que antes eu jogava uma numa versão "paralela" no technic launcher que dizia rodar a 1.0.5 rodava a mais  100 frames, já no curseforge e no multi MC com a render no 2 e os gráficos no mínimo ele rodava a menos de 30, oscilando pra 10 as vezes, e nos dois eu deixei 10gb de ram alocado. também deve ser algum problema de launcher (mas com o tanto de coisa faltado tbm '-')

**Comment by ArtpokeBr** [comment]
Não existe "versão paralela" então fico feliz que tenha abandonado os Piratas, mas enfim, provavelmente problemas com a CurseForge nesse quesito de manter o Launcher do Mine aberto :T n tenho muito o que fazer.
