### ISSUE TITLE
Chunkloader

### ISSUE THREAD

**Issue by Togzz** [ArtpokeBr/Minecraft-Ultimato#312]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.6
**Descrição:**
Eu não jogo em servidor e tals, então não há sentido o chunkloader estar desabilitado para mim... queria saber como alterar isso

**Comment by ArtpokeBr** [comment]
Minha recomendação é Instalar o FTB Utilities por fora, ele vai lhe prover um sistema simples de ChunkLoading. Habilitar seria complicado de Explicar para um Leigo, mas na verdade existem 2 Chunk Loaders que n foram desabilitadas kkk, uma do OpenComputers e outra que é o Ritual Anchor do Astral Sorcery.
