### ISSUE TITLE
erro ao abrir modpack

### ISSUE THREAD

**Issue by Gamer-spec** [ArtpokeBr/Minecraft-Ultimato#313]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
a mais recente

**Descrição:**
toda vez que vou abrir o jogo ele da erro de crash
[crash-2020-12-25_14.04.35-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5742209/crash-2020-12-25_14.04.35-client.txt)

**Crash Log:**

c.

**Comment by ArtpokeBr** [comment]
Primeiro de tudo, não escreva "A Mais recente" não tenho como saber por exemplo se você acha que é a mais recente mas na verdade não é, peço que neste aspecto seja mais informativo. Outra coisa, Quanto de RAM Alocada?

**Comment by Gamer-spec** [comment]
5 gb

**Comment by ArtpokeBr** [comment]
Bom, tente subir um pouco mais a alocação de Memória, se não funcionar.... Reinstale o Modpack.
