### ISSUE TITLE
O jogo parou de funcionar, codigo de saida 0

### ISSUE THREAD

**Issue by Markito64** [ArtpokeBr/Minecraft-Ultimato#315]
A versão: 1.0.4

Eu possuo dois computadores, um na casa do meu pai e um no da minha mãe. O mod funcionou perfeitamente em uma das casas e na outra tem dado esse erro. Eu baixei e abri outros mods e eles estão funcionando normalmente, o unico que da erro é o ultimato. (Estou usando o curse forge)

**Comment by ArtpokeBr** [comment]
Por favor, use a Template fornecida corretamente, em qual versão do Modpack você está? o Erro é ao Abrir correto? quanto de RAM você alocou?

**Comment by Markito64** [comment]
9 ram
O erro é ao abrir
Onde eu consigo a versão? é no curseforge ou no launcher do mine?

**Comment by Markito64** [comment]
https://www.youtube.com/watch?v=NJVY9u_GDHI

um video do erro

**Comment by ArtpokeBr** [comment]
9 GB de RAM alocada? isso é demais. nenhum Modpack usa tanto RAM assim. se quiser alocar bastante no máximo 6gb é recomendado.

**Comment by Markito64** [comment]
ok

**Comment by Markito64** [comment]
continua dando erro, eu achava que quanto mais colocasse melhor ksksksk

**Comment by ArtpokeBr** [comment]
Continua dando o Erro? tenta reinstalar o Mine em si.

**Comment by Markito64** [comment]
Eu vou tentar, mas o estranho é que so o ultimato da erro, os outros funcionam normalmente

**Comment by ArtpokeBr** [comment]
Se for só o Ultimato, reinstala o Modpack então.

**Comment by Markito64** [comment]
está instalando de novo, tem como descobrir se o problema não é a minha cpu? pq eu vi que tem varias pessoas que não estão conseguindo abrir por conta da cpu.

OBS: eu jogo em um notebook :)
