### ISSUE TITLE
Pergunta

### ISSUE THREAD

**Issue by XxSlaDoidoxX** [ArtpokeBr/Minecraft-Ultimato#316]
É só uma perguntinha nada demais, se eu remover alguns mods manualmente do modpack vai acontecer alguma coisa por exemplo sla um crash? Se você não souber só coloca erro de usuário ou qualquer coisa que vc quiser eu não sei direito o que é isso.

**Comment by ArtpokeBr** [comment]
Remover Mods da lista, ou adicionar Mods na lista original só vai fazer com que eu não tenha mais o "Poder" de ajudar você com os Problemas. visto que Modificar o Original você estaria indo por sua própia conta e risco kkk não necessáriamente daria um Crash, mas se acontecesse, nem adiantaria reportar aqui.

**Comment by XxSlaDoidoxX** [comment]
como assim pondo a minha conta em risco? eu não entendi eu sou burro ¯\_(ツ)_/¯

**Comment by ArtpokeBr** [comment]
Por conta própia, ou seja, por você mesmo.
