### ISSUE TITLE
bug na abertura do mine

### ISSUE THREAD

**Issue by Hiquezin** [ArtpokeBr/Minecraft-Ultimato#32]
to tendo um bug, que sempre que eu tento entrar aparece isso https://ibb.co/2cRd8z2

**Comment by ArtpokeBr** [comment]
E você acha que com uma print escrito "Unknow"eu seria um deus oniciente capaz de saber oq é? manda pelo menos o último crash report...

**Comment by Hiquezin** [comment]
ele n da crash report, por isso vim falar com vc opoha

**Comment by ArtpokeBr** [comment]
Ele não gera Crash report? manda um Log então, acho que só assim vai dar pra ver kkk

**Comment by Hiquezin** [comment]
onde eu pego o log?

**Comment by ArtpokeBr** [comment]
tem uma pasta chamada Logs, lá dentro vai ter um arquivo txt chamado "Latest" esse é o log mais recente. só me mandar ele após o erro acontecer cntg.
