### ISSUE TITLE
Mapa crashando

### ISSUE THREAD

**Issue by KRAZYYUltimato** [ArtpokeBr/Minecraft-Ultimato#320]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.4

**Descrição:**
Eu havia saido do jogo normalmente, e no outro dia quando fui entrar no mapa começou a apresentar esse erro

**Sugestão de Solução:**
Mandei o crash report, pelo que entendi o mods que estão aprentando problema é o laggogles e o FastWorkbench

**Crash Log:**
[crash-2020-12-27_14.40.47-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5744822/crash-2020-12-27_14.40.47-server.txt)

**Screenshots:**
![2020-12-27_14 59 30](https://user-images.githubusercontent.com/75383884/103175838-ce8c9980-484b-11eb-808d-1f8bd388424f.png)

**Comment by ArtpokeBr** [comment]
é algum erro de Chunk, talvez você estivesse carregando Chunks demais? ou estivesse usando o LagGoggles e assim carregou Chunks demais? e na verdade, o erro já começa pelo fato de que você está na versão 1.0.4 então sinceramente complica pra ajudar né...
