### ISSUE TITLE
Erro ao abrir/entrar em servidor

### ISSUE THREAD

**Issue by Luuscaa** [ArtpokeBr/Minecraft-Ultimato#321]
**Versão do Modpack:**
1.0.6

**Descrição:**
Boa tarde! Estou tendo problemas quanto a abertura de um servidor. Tá bem complicado de achar uma solução pra isso, eu e um amigo ainda encontramos problemas parecidos aqui no fórum e tentamos usar as sugestões para ver se resolvia, mas sem sucesso. O problema é bem simples: Aparece o erro da Print 1 sempre que alguém tenta entrar no servidor e as vezes um outro com um texto de erro maior.

**Passo a Passo para chegar no Problema (Opcional):**
Nós basicamente instalamos o modpack na última versão, baixamos o arquivo do servidor, executamos tudo como deve ser e deu o erro. 

**Screenshots:**
Print 1: https://prnt.sc/waxcsp

**Comment by ArtpokeBr** [comment]
Esse problema está acontecendo e ainda não há um Fix garantido eu diria, as Server Files são meio que não são feitas por mim justamente por não manjar muito de Servidores, mas o "Fix" que pode funcionar é tentar Syncar as Configs do Server com a de vocês tentando entrar, ou seja, dele a pasta de Configs do Server e jogue a do Client pro Server. talvez funcione.
