### ISSUE TITLE
Bug de blocos não droparem ao serem quebrados

### ISSUE THREAD

**Issue by Sguisato** [ArtpokeBr/Minecraft-Ultimato#322]
Versão do Modpack:
1.0.6

Descrição:
Ao tentar quebrar um bloco, ele não é dropado no chao, isso acontece com todos os blocos, o resto do jogo funciona normalmente, este mesmo bug acontece em momentos aleatorios, sendo nescessario fechar e reiniciar o jogo

**Comment by Sguisato** [comment]
Versão do Modpack:
1.0.6

Descrição:
Ao tentar quebrar um bloco, ele não é dropado no chao, isso acontece com todos os blocos, o resto do jogo funciona normalmente, este mesmo bug acontece em momentos aleatorios, sendo nescessario fechar e reiniciar o jogo

**Comment by Sguisato** [comment]
Observação do que pode estar ocasionando o erro:
Por mais que o WubHammer esteja desativado na versao 1.0.6, eu já o possuia de versoes anteriores, ao utilizar o mesmo junto da tecla "aspas" ao quebrar um bloco, está ocasionando este erro, pode ser coincidencia, ou pode ser este a raiz do problema

**Comment by ArtpokeBr** [comment]
o Martelo de Wub foi desativado por conta desse problema... então meio que ele é sim a causa do problema kkk
