### ISSUE TITLE
Bug que fez eu perder todos os meus mapas

### ISSUE THREAD

**Issue by Skuldafn** [ArtpokeBr/Minecraft-Ultimato#324]
**Versão do Modpack:**
1.0.6

**Descrição:**
Infelizmente na hora de abrir o modpack ele deu um aviso sobre o mod Quark, quando cliquei em voltar para o menu principal do jogo ele abriu o modpack só que sem a luva do thanos no menu, quando fechei e tentei reabrir o modpack perdi todos os meus saves, sei que é um problema que não tem como resolver visto que você não tem acesso aos meus saves, mas seria legal que resolvesse se desse para que ninguem mais tenha esse problema e perca seu mapa.

**Sugestão de Solução:**
Correção do Mod Quark (possível causador do problema)

**Crash Log:**
[latest.log](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5747458/latest.log)

**Comment by ArtpokeBr** [comment]
WTF? olha, você instalou corretamente o Modpack? o Quark dar um erro assim é bizarro, ainda mais você perder suas coisas sem ter atualizado ou coisa do tipo...

**Comment by Skuldafn** [comment]
Na verdade o mod já estava instalado tudo certinho, não tentei baixar alguma atualização nem nada, simplesmente cliquei em play e enquanto ele abria deu uma aviso do mod Quark, daí quando fechei e abri dnovo eu já tinha perdido todos os meus saves

**Comment by ArtpokeBr** [comment]
bom, continua estranho, nunca ouvi falar de tal problema kk

**Comment by Skuldafn** [comment]
NN tranquilo kkkkkkkkkkkk, sei que não tem como resolver o meu problema pq já foi excluído, só reportei pra avisar sobre o problema pq se caso você tivesse alguma ideia do que podia ser poderia consertar pra ninguém mais perder o mapa, mas muito obrigado pela atenção
