### ISSUE TITLE
problemas com o servidor

### ISSUE THREAD

**Issue by NicolaasGC** [ArtpokeBr/Minecraft-Ultimato#327]
video falando sobre o meu problema. https://youtu.be/5AsbXPtzBTA

**Comment by ArtpokeBr** [comment]
Dá uma olhada, que eu pus na página do Modpack um link pro Mediafire, com umas modificaçõeszinhas nas Server files que possivelmente podem ajudar. boa sorte.

**Comment by NicolaasGC** [comment]
opa ja me ajudou mt obg.
