### ISSUE TITLE
Erro ao entrar num servidor recém criado 

### ISSUE THREAD

**Issue by L4ST23** [ArtpokeBr/Minecraft-Ultimato#328]
![problema](https://user-images.githubusercontent.com/75741562/103313133-0267ea80-4a17-11eb-81c2-ff7eccff215c.png)

Da me este problema ao tentar entrar num servidor que criei a partir daqui.

**Comment by L4ST23** [comment]
![Problema mc](https://user-images.githubusercontent.com/75741562/103313296-90dc6c00-4a17-11eb-877c-f3b655f7ce2c.png)

Da isto no comando do servidor

**Comment by ArtpokeBr** [comment]
Tenta ver as Server files mais recentes, e na verdade isso ai tá bem na cara que os Mods que estão no seu Client e no Server estão faltando/são de versões diferentes talvez. certifique-se se baixar as server files mais recentes (que estão num linkzinho na página do Modpack) e de estar na versão mais recente do Modpack.

**Comment by Christtiann** [comment]
@L4ST23 vc nao esta usando a versao nova do modpack...
