### ISSUE TITLE
Problemas de conflito entre receitas

### ISSUE THREAD

**Issue by Benites031407** [ArtpokeBr/Minecraft-Ultimato#329]
Criei meu servidor pelo arquivo que foi disponibilizado com as pastas de servidor, quando tento entrar da isso na tela 

![image](https://user-images.githubusercontent.com/76753917/103316724-207a1e80-4a08-11eb-9165-54139a989100.png)

**Comment by ArtpokeBr** [comment]
pega os arquivos de server mais atualizados, tem um link na página do Modpack que leva pro Mediafire pra baixar.

**Comment by Benites031407** [comment]
no link do forge?

**Comment by ArtpokeBr** [comment]
A Página do Modpack é na CurseForge né kk
