### ISSUE TITLE
Não estou encontrando lulas 

### ISSUE THREAD

**Issue by EmanuelMine** [ArtpokeBr/Minecraft-Ultimato#33]
Não sei se foi o meu mapa,ou azar mas eu não estou conseguindo achar lulas,procurei por cerca de meia hora mas mesmo assim eu não achei

**Comment by ArtpokeBr** [comment]
Olha, eu não mexi em na relacionado.... provavelmente é azar o seu...

**Comment by EmanuelMine** [comment]
sim,tive q pegar no criativo infelizmente...fiquei mais de 1 hora procurando nmrl,mas eu já fiz a armadura do avaríta,o ultimate ingot eh trabalhoso dms kk

**Comment by ArtpokeBr** [comment]
kkkkkk

**Comment by ArtpokeBr** [comment]
Vou fechar ent

**Comment by gupoiatti** [comment]
eu tinha esse mesmo tipo de problema em outra modpack, o mod do wild and zoo zoa todos os spawns do vanilla, ou tu desabilita o mod antes de entrar ou fica horas procurando.
