### ISSUE TITLE
the twilight forest

### ISSUE THREAD

**Issue by m4cedo** [ArtpokeBr/Minecraft-Ultimato#331]
**Descrição:**
Então a progressão da the twilight forest foi desativada, mas tipo quando eu tento pegar um baú, ou matar um mob aparece um bloqueio amarelo, e isso está me atrapalhando em pegar a steeleaf ;-;.

**Comment by ArtpokeBr** [comment]
Falta de Informação. qual versão do Modpack você está?

**Comment by m4cedo** [comment]
Última versão do modpack a 1.0.6.

**Comment by ArtpokeBr** [comment]
Olha, eu tenho certeza que desabilitei a progressão, mas talvez ela só seja relacionada aos Bosses? então talvez tu tenha que matar ainda um Boss específico pra poder pegar steelleaf.

**Comment by m4cedo** [comment]
Provavelmente é o minotauro, mas quando procuro pelo mapa só aparece o 4 boss, e lá se eu bato em um mob ele recupera vida, e na versão do server o Jazz matou a hidra antes de ir na naga, algo está errado ae.

**Comment by ArtpokeBr** [comment]
hmm confira as configs do Mod, mas até aonde me lembre, era pra estar certinho isso.

**Comment by m4cedo** [comment]
https://docs.google.com/document/d/1M7kbSswWT3sb1AmY_QvAa8Tm5K_kcdT9Bw76tz9tpIY/edit?usp=sharing

então art, dá uma olhada nesses prints ae.
