### ISSUE TITLE
Geração do mundo de dragões 

### ISSUE THREAD

**Issue by TRAPGamer07** [ArtpokeBr/Minecraft-Ultimato#332]
**Nota** Problema com a geracao do mundo dps dragoes

**Versão do Modpack:**
1.0.4

**Descrição:**
Criei o meu mundo normalmente, no tipo "Topography". Fui avançando no modpack até que fui para a Terra dos Dragoes. O mundo foi criado normalmente mas parou de gerar as chunks. Podem me ajudar?

**Comment by TRAPGamer07** [comment]
Minha versão é 1.0.6**

**Comment by ArtpokeBr** [comment]
Bug esquisito, parou de gerar chunks? talvez seja lag de TPS? pior que não sei :T

**Comment by TRAPGamer07** [comment]
Quer que mande print?
