### ISSUE TITLE
Minecraft Ultimato 1.0.6 Lag 

### ISSUE THREAD

**Issue by ozedalinguica** [ArtpokeBr/Minecraft-Ultimato#333]
Olá! estou com um **problema sobre crash**, o jogo não fecha, porém **a cada 2 segundos ou menos, ele congela minha tela dentro desses 2 segundos, e depois volta, e assim em diante.**
Provavelmente não é o meu computador, porque já deixei tudo no mínimo, na pior resolução e nada.
Aqui está minha config do PC:

**Geforce GTX 1650
Intel Core i5
16 GB RAM
1920x1080, 60Hz**

Aqui está um vídeo sobre o problema:

https://user-images.githubusercontent.com/76819424/103418899-71585700-4b6f-11eb-8bb5-de62024fb25e.mp4

**Comment by ArtpokeBr** [comment]
Quanto de RAM Alocada?

**Comment by ozedalinguica** [comment]
> Quanto de RAM Alocada?

Minha RAM normal é 16 GB.
Porém, vi no gerenciador de tarefas, que fica 10 GB RAM Disponível

**Comment by ArtpokeBr** [comment]
Quanto de RAM você alocou na instância? o recomendado seria 6GB.

**Comment by ozedalinguica** [comment]
> Quanto de RAM você alocou na instância? o recomendado seria 6GB.

A placa de vídeo? 6GB Mesmo.

**Comment by ozedalinguica** [comment]
Isso aqui está na própria NVIDIA Geforce Experience:
![Screenshot_1](https://user-images.githubusercontent.com/76819424/103440298-0f592980-4c23-11eb-9011-72deb1a96453.png)

**Comment by ArtpokeBr** [comment]
Meu deus, não tem nada haver com placa de vídeo! no mine não adianta você só ter a memória no PC, você precisa definir o quanto ele vai usar, pois geralmente o mínimo que ele usa não é suficiente kkk, é uma das primeiras vezes que tu tá jogando Minecraft? 
![image](https://user-images.githubusercontent.com/44851727/103441515-53512c00-4c2d-11eb-8452-6a90f3872f40.png)

**Comment by ozedalinguica** [comment]
> Meu deus, não tem nada haver com placa de vídeo! no mine não adianta você só ter a memória no PC, você precisa definir o quanto ele vai usar, pois geralmente o mínimo que ele usa não é suficiente kkk, é uma das primeiras vezes que tu tá jogando Minecraft?
> ![image](https://user-images.githubusercontent.com/44851727/103441515-53512c00-4c2d-11eb-8452-6a90f3872f40.png)

Não KKKKKKKKKKKKKKKKKKK, não sabia disso a

**Comment by ozedalinguica** [comment]
> Meu deus, não tem nada haver com placa de vídeo! no mine não adianta você só ter a memória no PC, você precisa definir o quanto ele vai usar, pois geralmente o mínimo que ele usa não é suficiente kkk, é uma das primeiras vezes que tu tá jogando Minecraft?
> ![image](https://user-images.githubusercontent.com/44851727/103441515-53512c00-4c2d-11eb-8452-6a90f3872f40.png)

eu jogo mine desde 2013 e n sabia dissoKKKKKKKKKKKKKKKKK
