### ISSUE TITLE
Conflito de teclas

### ISSUE THREAD

**Issue by Shown20** [ArtpokeBr/Minecraft-Ultimato#335]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2
**Descrição:**
Neste caso o meu minecraft não crasha mas quando eu vou aos _"Controls"_ , pois ha muito conflito de teclas eu não consigo ler do que se trata cada tecla. Resumindo a função de _"Controls"_  esta deporpocional ao ecra"

**Sugestão de Solução:**
A minha primeira solução foi mudar as proporções mas não resoltou.
**Passo a Passo para chegar no Problema (Opcional):**
Dar "esc"->"options"->"controls"
**Crash Log:**
--

**Screenshots:**
![Screenshot_9](https://user-images.githubusercontent.com/76853458/103447501-08aece80-4c84-11eb-90f5-889a4ba0e93e.png)

**Comment by ArtpokeBr** [comment]
Isto não é algo que eu possa resolver, se a tela está grande demais, cabe ao jogador reduzir a escala para trocar os controles, e quanto aos conflitos de keybinds, é outra coisa que não cabe a mim, e sim ao player decidir suas respectivas preferências. :)
