### ISSUE TITLE
Geração da dimensao dos dragões.

### ISSUE THREAD

**Issue by lhpmarcos** [ArtpokeBr/Minecraft-Ultimato#339]
Versão do Modpack:
1.0.6

Descrição:
Criei o bloco Portal Para a Terra de Dragões!, segudo a descrição no modpack, essa dimensão é idêntica ao overworld porem com estruturas do Ice and Fire, mas ao entrar na dimensão, ela é um mundo de void. As estruturas do Ice and Fire geram, e até vejo Cyclops caindo no void á distancia.

Sugestão de Solução:
Acredito que tenha a ver com o mod do SimpleVoidWorld, verificar se está tudo ok.

Passo a Passo para chegar no Problema (Opcional):
Se nao entrou na dimensão ainda, ela irá gerar um mundo de void. Caso já entrou, gere novos chunks.

Crash Log:
Não há.

Screenshots:
![void dragão](https://user-images.githubusercontent.com/75625691/103450260-41ee3b00-4c92-11eb-9f48-c3d921784388.png)

PS : Não encontrei onde eu coloco label de bug aqui.. Ou não sei mecher, se puder dar uma luz.

**Comment by BrunoTotoli** [comment]
Estou exatamente com o mesmo problema, nao esta gerando o mundo com dragoes.

**Comment by smurfvegetariano** [comment]
mesmo problema aqui, mas na 1.0.4
