### ISSUE TITLE
Erro ao abrir o mundo para lan

### ISSUE THREAD

**Issue by LukinhasPlayHD** [ArtpokeBr/Minecraft-Ultimato#34]
Opa meu bom, seguinte, quando eu abro meu mundo para lan, alguns dos meus amigos simplismente não conseguem entrar, alguns mostram uma caixinha de erro no canto superior direito, e outros apenas nao entram, e o mine crasha, algums dos meus amigos conseguem entrar normal, vc tem alguma ideia do que pode ser?

**Comment by ArtpokeBr** [comment]
Preciso de informações, só falar que crasha não ainda nada, preciso do Crash log de algum que tentou entrar e supostamente crashou e etc.
