### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Shuuunnn** [ArtpokeBr/Minecraft-Ultimato#340]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
1.0.2
**Descrição:**
Não abre. segue imagem do erro

**Sugestão de Solução:**
:/

**Passo a Passo para chegar no Problema (Opcional):**
Eu abro o jogo e acontece isso
**Crash Log:**
Nao tem
**Screenshots:**
![image](https://user-images.githubusercontent.com/76876830/103460906-f02ccb80-4cf8-11eb-8955-950ad3a4fe50.png)

**Comment by Shuuunnn** [comment]
Tentarei abrir na versão mais recente, caso consiga removerei o post

**Comment by Shuuunnn** [comment]
Não funciona em nenhuma versão Multimc/Curseforge

**Comment by ArtpokeBr** [comment]
1.0.2? primeiro de tudo, você está em uma versão MUITO desatualizada, e segundo, esse erro do IC2 é só por falta de memória mesmo. aloque um pouco mais.

**Comment by Shuuunnn** [comment]
testei em todas já

**Comment by Shuuunnn** [comment]
Consegui! O provlema era em espaco mesmo
