### ISSUE TITLE
Chunk loading- ajuda

### ISSUE THREAD

**Issue by alucardXD455** [ArtpokeBr/Minecraft-Ultimato#341]
olá ArtpokeBr, tudo bom?
gostaria de uma ajuda para ativar novamente os chunk loaders no mod pack, como só jogo single player não me afeta tanto. poderia mostrar qual é o arquivo que devo alterar?

**Comment by ArtpokeBr** [comment]
Recomendo Instalar é o FTB Utilities, ele vai lhe prover o necessário.
