### ISSUE TITLE
Pergunta(Eu sou chato eu sei)

### ISSUE THREAD

**Issue by XxSlaDoidoxX** [ArtpokeBr/Minecraft-Ultimato#343]
Eu provavelmente to sendo bem chato com essas perguntas mas se eu mexer nos scripts do crafttweaker vai acontecer algum problema? (Eu sei mexer relaxa eu aprendi)

**Comment by ArtpokeBr** [comment]
Não é recomendável que você mexa... vai alterar como o Modpack se comporta e respectivamente não irei prestar assistência á você.
