### ISSUE TITLE
problema da geraçao do ice and fire 

### ISSUE THREAD

**Issue by linezada** [ArtpokeBr/Minecraft-Ultimato#347]
**Versão do Modpack:**
1.0.6

**Descrição:**
no serverpack do mediafire a geraçao da dimensao n funciona sempre fica o void e eu ate cheguei a tentar puxar o código que esta na pasta do Topography e dps disso o servidor nem abre ai tenho q voltar a usar o codigo antigo pra ele abrir ,eu tbm tentei usar um mapa do single player mas parece q eles mesclam as dimensões (n sei se foi um bug do portal ou se as dimensoes bugaram)

**Crash Log:**
[crash-2021-01-03_14.37.55-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5776582/crash-2021-01-03_14.37.55-server.txt)

**Comment by smurfvegetariano** [comment]
mesmo problema aqui, mas na versão 1.0.4

**Comment by linezada** [comment]
alguem conseguiu alguma coisa ?
