### ISSUE TITLE
bug visual avaritia

### ISSUE THREAD

**Issue by gamerYToff** [ArtpokeBr/Minecraft-Ultimato#348]
versão do modpack 1.0.6

estou tendo um bug um pouco chato no mod avaritia não é anda demais mas me causa incomodo quando eu fico em 3 pessoa com a câmera para trás as asas do avaritia simplesmente some é um pouco chato isso e tira um pouco da beleza do mod
![2021-01-07_21 15 14](https://user-images.githubusercontent.com/75382609/103959173-c414ae80-512d-11eb-9f28-ad393e8146c1.png)
![2021-01-07_21 16 04](https://user-images.githubusercontent.com/75382609/103959196-d393f780-512d-11eb-964e-411722fec90d.png)

**Comment by ArtpokeBr** [comment]
kkkkk isso provavelmente é coisa do Mod rapaiz, não tenho como fazer nada :T
