### ISSUE TITLE
Diário do Thanos buga na transmutation table

### ISSUE THREAD

**Issue by noeneto** [ArtpokeBr/Minecraft-Ultimato#35]
**Para reproduzir:** colocar o Diário do Thanos numa transmutation table.

Livros no Patchouli usam nbt para se diferenciar, essa mesa do ProjectE não reconhece essa diferença e joga o livro padrão, que fica com uma textura magenta e preto.

**Sugestão:** Tirar EMC desse guia específico e todos os outros do Patchouli.

**Comment by ArtpokeBr** [comment]
o EMC deles vem automaticamente por conta dos itens usados para craftar, então nem fui eu que coloquei por padrão. mas irei remover então o EMC como uma qualidade de vida pro pessoa n perder os guias.
