### ISSUE TITLE
Impossível gerar Fluix Steel Ingot

### ISSUE THREAD

**Issue by marcodelaet** [ArtpokeBr/Minecraft-Ultimato#350]
Para criar o Ultimate Ingot, um dos minérios pedidos é o Fluix Steel Ingot, mas pra fazê-lo precisa de um Crystal de Fluix para gerar um pó deste cristal, e para conseguir esse Crystal, é necessário criar uma máquina (que precisa do mesmo material que ela fabrica). Desta forma entramos em um loop e não conseguimos criar nem a máquina, nem o material, e portanto não conseguimos criar o Fluix Steel Ingot, nem o Ultimate Ingot.

**Comment by ArtpokeBr** [comment]
Ué, e pó de Fluix é feito como? kkkkkkk Rapaiz, a receita padrão do Applied não foi desativada! só droppar ai na pocinha teu Cristal carregado de Certus, um quartzto do nether e redstone kkk

**Comment by marcodelaet** [comment]
Então o erro está na receita
Essa receita que vc citou não aparece no modpack
Em todas as receitas para criar o pó de Fluix é pedido para usar o Crystal de Fluix.
Mas vou tentar utilizar a receita que passou aqui.

**Comment by marcodelaet** [comment]
Valeu.. eu realmente não estava encontrando a receita.. hahaha
Só depois que você falou aqui eu vi que tinha essa informação no <i> 
Hahahaha

Sorry.. mas muuuiito obrigado pela dica preciosa
