### ISSUE TITLE
Geração do Mundo

### ISSUE THREAD

**Issue by XxUnderDarkxX** [ArtpokeBr/Minecraft-Ultimato#351]
Por Favor me ajudem porque quando vou iniciar o mundo, acaba nao respondendo o minecraft, e nao responde mais .
tenho 8 de Ram. Alocado 7

**Comment by ArtpokeBr** [comment]
Pra que alocar 7GB? primeiro que o Modpack não precisa de tanto assim, segundo que se seu PC tem 8GB, é necessário deixar 2GB vagos só para o Windows.
