### ISSUE TITLE
Não consigo entrar no meu mundo por crash do EnderStorage

### ISSUE THREAD

**Issue by YuriSylvan-ui** [ArtpokeBr/Minecraft-Ultimato#352]
**Versão do Modpack:**
Minecrat Ultimato 1.0.6

**Descrição:**
Um belo dia, estava jogando em meu mundo e a luz piscou e consequentemente meu computador desligou, eu ligo tento entrar em meu mundo e da um crash e fala que possivelmente é o EnderStorage, e ele nao me permite entrar no mundo, tenho que desinstalar o Ender Storage pra ele assim funcionar e conseguir entrar no meu mundo

**Sugestão de Solução:**
Ja tentei desinstalar o Ender Storage e colocar uma versão inferior porém não funciona de forma alguma o unico jeito de conseguir entrar no meu mundo e desinstalando o ender storage

**Passo a Passo para chegar no Problema (Opcional):**
Acho que não sera possivel replicar o problema ah não ser que vc desligue seu computador com o jogo aberto ai possivelmente pode chegar no erro

**Crash Log:**
[crash-2021-01-10_18.49.01-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5793299/crash-2021-01-10_18.49.01-server.txt)

**Screenshots:**
![crash](https://user-images.githubusercontent.com/77177932/104135142-e0eaf500-536c-11eb-9bf5-42f6d0b2c31b.png)

**Comment by ArtpokeBr** [comment]
Provavelmente seu Mapa corrompeu por não fechar corretamente, eu diria que só restaurando Backup...
