### ISSUE TITLE
Textura da armadura Draconic

### ISSUE THREAD

**Issue by GrapV** [ArtpokeBr/Minecraft-Ultimato#353]
![2021-01-11_15 25 06](https://user-images.githubusercontent.com/77292410/104216525-ef8ee600-5418-11eb-84cc-7535000736a8.png)

Essa não é a versão padrão da armadura né ?

**Comment by ArtpokeBr** [comment]
Efeito colateral do Emoticons, se quiser, desinstale-o que a textura deve deixar normal.

**Comment by GrapV** [comment]
Como faz para desinstalar eles ?

**Comment by ArtpokeBr** [comment]
só ir na pasta mods e deletar o mod do emoticons msm

**Comment by GrapV** [comment]
OK, vou tirar o mod do servidor e ver se não dá problema.

Muito obrigado Art
