### ISSUE TITLE
Alchemical Chest and Energy Condenser

### ISSUE THREAD

**Issue by Thiagorbm22222** [ArtpokeBr/Minecraft-Ultimato#354]
Bom dia!

Para fazer o Condensador de Energia, eu preciso do Alchemical Chest, porém, ao fazer o crafting, o item não é feito, já verifiquei se eu botei uma coisa errada, na ordem errada ou um bloco errado, mas está tudo certo. Já fechei o modpack e entrei de novo, testei em um novo mapa, mas nada. Então o crafting está bugado.

Obrigado!

![image](https://user-images.githubusercontent.com/77331760/104316354-1d2c6b80-54bb-11eb-8aef-e03a40dffd7a.png)

**Comment by ArtpokeBr** [comment]
Tente verificar as pedras que está usando, provavelmente a receita não deve estar identificando os OreDicts ali.

**Comment by Thiagorbm22222** [comment]
Ok, obrigado.

Em ter, 12 de jan de 2021 11:55, ArtpokeBr <notifications@github.com>
escreveu:
