### ISSUE TITLE
Modpack Carregando infinitamente

### ISSUE THREAD

**Issue by YunnkFire** [ArtpokeBr/Minecraft-Ultimato#355]
Quando dou play no Curse Forge abre o Minecraft Launcher... quando eu aperto no play o jogo fica carregando infinitamente sem abrir , eu abro o gerenciador de tarefas e esta o processo Java (só que o jogo não abre de jeito nenhum).

(OBS) 8GB de memória ram alocada.

**Comment by ArtpokeBr** [comment]
Mas carregando infinitamente no Launcher padrão? ou o jogo chega a abrir sua janela e fica no Forge Carregado? podia ter fornecido prints né...

**Comment by YunnkFire** [comment]
Eu abro o jogo só que nem aparece a janela.

**Comment by YunnkFire** [comment]
Por Exemplo , eu abro o mod pelo curse , depois abre o launcher padrão , o jogo baixa etc... só que quando aperto em Jogar , o launcher padrão fecha de lei né . só que fico esperando infinitamente a janela do forge aparecer e não aparece de jeito nenhum . O jogo simplismente nao abre
