### ISSUE TITLE
Ativar os itens como chunkloader e watch of flowing time

### ISSUE THREAD

**Issue by MonkeyPants32** [ArtpokeBr/Minecraft-Ultimato#356]
**Versão do Modpack:**
1.0.4

**Descrição:**
Eu queria saber como ativar os itens como o chunkloader do ic2, o watch of flowing time, e a acceleration wand.
(Eu estou jogando no singleplayer)

**Comment by ArtpokeBr** [comment]
para ativar chunk loading recomendo na verdade instalar o FTB Utilities. e o quanto á ativar itens desativados, não ativa... se estão desativados é por algum motivo kkk
