### ISSUE TITLE
Mods não funcionando

### ISSUE THREAD

**Issue by Felipox** [ArtpokeBr/Minecraft-Ultimato#357]
Meu modpack está apresentando problemas ao jogar. Quando vou em uma vila, por exemplo, ela permanece invisível sem nenhum villager e nenhuma construção. A geração de animais dos outros mods também são comprometidas, não dando spawn de nenhum mob do modpack. Fui ver na edição do modpack e havia essa mensagem:
![Screenshot_1](https://user-images.githubusercontent.com/77701420/105099283-340a2980-5a8a-11eb-8af6-78478fcb0c74.png)

**Comment by ArtpokeBr** [comment]
As vilas são relacionadas a um problema comum mesmo, o Thanos Limpou :P além disso, que versão do Modpack você está? os Mobs deveriam estar spawnando normalmente.... só os do Zawa que são desativados.

**Comment by Felipox** [comment]
eu estava na versão certa, la no curse forge. baixei pelo segundo método
(multi mc) e aí funcionou tudo normalmente, mas obrigado pela atenção
