### ISSUE TITLE
Problema com EMC no mod Avaritia

### ISSUE THREAD

**Issue by Afonso027** [ArtpokeBr/Minecraft-Ultimato#358]
**Versão do Modpack:**
1.0.6

**Descrição:**
Gostaria que você me esclarecer-se uma duvida, bom o mod da emc da para muitos itens, mas no video que voçê fez mostrou alguns craftings do avaritia para fazer a armadura, os singularitys, etc... e dão para multiplicar porque aparece lá quanto emc é preciso para mutiplicar. Bom quando eu fui tentar jogar o modpack, nao me aparecia lá quanto emc era preciso para poder multiplicar os itens do avaritia como por exemplo neutronium ingot , infinity ingot, a armadura. Voçê conseguem-me dizer o porquê de nao dar para multiplicar. É porque fica muito dificil para fazer o infinity ingot várias vez.

**Screenshots:**
![Captura de ecrã 2021-01-22 221805](https://user-images.githubusercontent.com/77861936/105554692-c5ce9c80-5cff-11eb-9f35-9337a70af657.png)
![Captura de ecrã 2021-01-22 221956](https://user-images.githubusercontent.com/77861936/105554832-0cbc9200-5d00-11eb-9a8c-d6e8e9a11da4.png)

**Comment by ArtpokeBr** [comment]
1- Qual versão do Modpack você está.
2- se bem me lembro, na última atualização, apenas o EMC do neutronium foi removido.

**Comment by Afonso027** [comment]
Ta na mensagem acima a versão do modpack, mas é a 1.0.6

**Comment by ArtpokeBr** [comment]
> Ta na mensagem acima a versão do modpack, mas é a 1.0.6

Perdão não tinha visto, mas olha, se eu n me engane, TODOS os itens do ingot em si e etc, então com EMC, então Automatizar você consegue...

**Comment by Afonso027** [comment]
![Captura de ecrã 2021-01-23 150404](https://user-images.githubusercontent.com/77861936/105598874-43d88500-5d8c-11eb-8189-e9c653271a08.png)

Agora hoje de manhã apareceu-me isto. E eu acho que perdi todo os meus saves do mod. Tá de sacanagem

**Comment by Afonso027** [comment]
> > Ta na mensagem acima a versão do modpack, mas é a 1.0.6
> 
> Perdão não tinha visto, mas olha, se eu n me engane, TODOS os itens do ingot em si e etc, então com EMC, então Automatizar você consegue...

Sim eu posso automatizar os itens nao tem problema, mas agora nao consigo porque me aparece isto aqui acima
