### ISSUE TITLE
Bugs Visuais

### ISSUE THREAD

**Issue by srmartan** [ArtpokeBr/Minecraft-Ultimato#36]
A armadura do avaritia fica bugada e não aparece toda 
Imagem - https://drive.google.com/file/d/1ATK57_U8XufpaVkuCP94wEcPfuw_Ys9b/view?usp=sharing

**Comment by ArtpokeBr** [comment]
Isso é relacionado ao Emoticons. para resolver é só tirar, mas por conta da série não posso tirar do Modpack não :T
