### ISSUE TITLE
Servidor pronto

### ISSUE THREAD

**Issue by jaozin321** [ArtpokeBr/Minecraft-Ultimato#360]
**Versão do Modpack:**
1.12.2

**Descrição:**
Criei um servidor (pela primeira vez) com o Modpack MC ULTIMATO, usei o servidor pronto de vocês, ele abriu, consegui entrar com meus amigos (hosteando pelo meu pc via hamachi), porém no servidor não gera os minérios do modpack, parece o minecraft vanilla, porém, olhando os itens, da para ver que os itens dos mods existem. Tentei apagar a .config e o mundo para gerar novamente, mas gerou sem minérios. Eu e meus amigos usamos minecraft original. Também, no começo da gameplay, começou a aparecer mensagens de conflitos de mods, pedindo para apertar Crtl l para me levar a um link externo.

**Passo a Passo para chegar no Problema (Opcional):**
Jogando algum tempo no servidor.

**Crash Log:**
[2021-01-31-3.log.gz](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5899231/2021-01-31-3.log.gz)

**Comment by jaozin321** [comment]
atualizando: usamos o app curse forge

**Comment by ArtpokeBr** [comment]
apenas por questão de conferir, qual o gerador que foi escolhido? você abriu á partir do SinglePlayer correto? seu mapa foi gerado com o Topography né?

**Comment by jaozin321** [comment]
Boa tarde. Foi gerado a partir do topography

**Comment by ArtpokeBr** [comment]
Olha, é bem estranho não ter gerador Ores, 
![image](https://user-images.githubusercontent.com/44851727/106396143-e1633280-63e4-11eb-9499-2f5e16234b33.png) você baixou as Server files por aqui?
