### ISSUE TITLE
Duvidas no projectE

### ISSUE THREAD

**Issue by StartZX1** [ArtpokeBr/Minecraft-Ultimato#362]
Opa, eu estou fazendo um survival no MC Ultimato V2.0 e estou no rumo para conseguir a Philosopher's Stone e preciso de uma alma de villager, estudei mais sobre o draconic e percebi que com a minha Sword of the wyvern e o meu reaper V tenho apenas 0.6% de chance de dropar a alma do villager, como vi que era extremamente dificil tentei crafta-la, mas eu preciso apenas dos seguintes itens 
(obs:o resto eu tenho) Alchemical Coal,Mobius Fuel e Aeternalis Fuel, tentei pega-los no energy collector mas sem sucesso,então  gostaria de saber como eu posso conseguir eles para eu conseguir craftar a alma de villager.
![imagem_2021-02-17_055947](https://user-images.githubusercontent.com/79193364/108180286-56bd4b80-70e5-11eb-90c3-078f163a8011.png)

**Comment by ArtpokeBr** [comment]
no Energy collector não está gerando? olhou todas as possibilidades?

**Comment by StartZX1** [comment]
O Energy collector só vai até a glowstone.
