### ISSUE TITLE
Onde encontro servidor

### ISSUE THREAD

**Issue by jeffjeffmaico** [ArtpokeBr/Minecraft-Ultimato#363]

**Comment by jeffjeffmaico** [comment]
gostaria de achar um servidor para este mc ultimato mas não acho

**Comment by ArtpokeBr** [comment]
Na versão 2.0 que é a atual, não há server files. mas olha, não é difícil fazer o Server funcionar, já que não há mais uma geração de mapa totalmente custom então monte o servidor normalmente e Apenas jogue as configs, scripts e etc :)
