### ISSUE TITLE
(Duvida) tem alguma forma de desativar o script de nerf do ProjectE ? 

### ISSUE THREAD

**Issue by linezada** [ArtpokeBr/Minecraft-Ultimato#365]
**Versão do Modpack:**
2.0

**Descrição:**
eu queria desativar o script de nerf do projectE no meu servidor alguns itens eu n consegui pegar de jeito nenhum como a alma de villager

**Comment by ArtpokeBr** [comment]
Eu apliquei os Nerfs pois justamente agora que a série terminou, finalmente posso balancear o Modpack de alguma forma :) minha recomendação é que você respeite a progressão do Pack, ao tirar o Nerf o modpack fica ridículamente fácil =/ a ideia era isso ser aplicado originalmente inclusive. se você depende demais do ProjectE complica né

**Comment by linezada** [comment]
eu sei eu ate gostei dos nerfs pq agr deixa mt mais interessante o modpack antigamente com 1 semana dava pra terminar ele mas n sei se é pq eu to em servidor alguns itens de drop sao impossíveis de pegar a alma do villager ja tem uns 2 dias q eu to jogando e nada por isso eu to qrnd desativar

**Comment by ArtpokeBr** [comment]
você está com o encantamento de Reaper na espada? usar um Staff do Draconic tbm ajuda a pegar.

**Comment by linezada** [comment]
sim ja tentei de tudo

**Comment by linezada** [comment]
fiz ate uma farm usando o mob duplicator mas nd

**Comment by ArtpokeBr** [comment]
Vixe, tu tá com um grande azar viu kkk

**Comment by linezada** [comment]
sim kkkkkkkkk ja ta eu e um amigo a uns 2 dias nessa

**Comment by ArtpokeBr** [comment]
Bom, se só está com problemas por causa deste item específico, e tentou de todas as formas possíveis, pegue-o no Cheat, assim n vai precisar desativar todas as modificações ;p
