### ISSUE TITLE
Quando tento entrar no minecraft Ultimato ele fala que ele foi modificado de uma forma que alguns jeitos de segurança são proibidos lá, e eu não consigo entrar.

### ISSUE THREAD

**Issue by ShadumMinecraft** [ArtpokeBr/Minecraft-Ultimato#366]
Aqui uma foto mostrando oque aconteceu
![image](https://user-images.githubusercontent.com/79873518/109555040-d0751200-7ab3-11eb-909c-a41b4e9b37c8.png)

**Comment by ArtpokeBr** [comment]
Isso é normal pra qualquer Modpack, uma das maluquices da Mojang.

**Comment by ShadumMinecraft** [comment]
@ArtpokeBr mais como eu arrumo esse problema?

**Comment by ArtpokeBr** [comment]
Ué,  você só abre kkk isso é só um aviso, e aliás, pela print dá pra ver que tu n tem o nem o jogo =/

**Comment by ShadumMinecraft** [comment]
Entendi, mais eu tenho o minecraft Pirata. Acho que o meu minecraft pirata
não vai e eu tenho mesmo que comprar o minecraft em. Mais obrigado por me
responder, me ajudou muito!
Aliás obrigado por me ensinar como baixar o ultimato! Agradeço de coração
cara :)


Em ter., 2 de mar. de 2021 às 11:45, ArtpokeBr <notifications@github.com>
escreveu:
