### ISSUE TITLE
Eu não consigo entrar no Minecraft Ultimato.

### ISSUE THREAD

**Issue by ShadumMinecraft** [ArtpokeBr/Minecraft-Ultimato#367]
@ArtpokeBr eu não consigo entrar no modpack, aqui uma foto do que está acontecendo porque eu não consigo explicar:
![image](https://user-images.githubusercontent.com/79873518/109660303-7160dd00-7b47-11eb-8eb1-f992a3c0e787.png)

**Comment by ArtpokeBr** [comment]
Não crie outra postagem por favor, tu já reportou algo, informe lá.
