### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by joaogamer007788** [ArtpokeBr/Minecraft-Ultimato#368]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
2.0

**Descrição:*
baixei o mod pack quando foi abrir o modpack aparece a seguinte frase
ERRO O JOGO PAROU DE FUNCIONAR. LAMENTAMOS. CODIGO DE SAIDA 0

**Sugestão de Solução:**
Substitua este texto por uma possível solução que você acha que possa ser feita para o seu problema! isto ajuda pois muitas vezes sua sugestão pode ser boa e pode ser implementada e resolvida rápidamente! 
nao tenho uma sujeitao ganhei o pc a 2 dias nao sou leigo

**Passo a Passo para chegar no Problema (Opcional):**
o problema acontece quando clico em jogar aparece um texto em uma barra de carregamento falando preparando ai abre uma janela e fala que parou de funcionar

**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest".   

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2021-03-03 12:54:41 BRT
Description: Initializing game

java.lang.RuntimeException
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1011823584 bytes (964 MB) / 1508376576 bytes (1438 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: 
  Loaded coremods (and transformers): BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.59.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.11.11_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      TickCentral (TickCentral-3.2.jar)
                                        com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer
                                        com.github.terminatornl.laggoggles.tickcentral.RenderManagerTransformer
                                        com.github.terminatornl.tickcentral.asm.BlockTransformer
                                        com.github.terminatornl.tickcentral.asm.ITickableTransformer
                                        com.github.terminatornl.tickcentral.asm.EntityTransformer
                                        com.github.terminatornl.tickcentral.asm.HubAPITransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      ratscore (rats-3.2.14-1.12.2.jar)
                                        com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
                                        techguns.core.TechgunsASMTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.26.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      FTBUltimineASM (ftb-ultimine-1202.3.5.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      AstralCore (astralsorcery-1.12.2-1.10.27.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_21.2.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4600'
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4531, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: ~~ERROR~~ NullPointerException: null
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.
nao sei como coloca foto

**Comment by ArtpokeBr** [comment]
Quanto de RAM Alocado pro Pack?

**Comment by ArtpokeBr** [comment]
Não respondeu dentro deu uma semana, fechando.
