### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Renatobr26** [ArtpokeBr/Minecraft-Ultimato#369]
toda vez que eu entro no minecraft ultimato, fica tudo d boa, aí eu jogo uns 10 minutos e do nada o jogo para de responder, sendo q meu pc é recente e eu coloquei 7/8 gb de ram alocada.

**Comment by ArtpokeBr** [comment]
Alocou provavelmente RAM demais, qual o Total no PC?

**Comment by ArtpokeBr** [comment]
Falta de Reposta além de uma semana, Fechando.
