### ISSUE TITLE
Cluckloder

### ISSUE THREAD

**Issue by garciaas** [ArtpokeBr/Minecraft-Ultimato#371]
alguém pode me ajudar a ativar o ftb utilites

**Comment by ArtpokeBr** [comment]
Mas já está ativo, a questão é que você não sabe usar?

**Comment by garciaas** [comment]
é mais gostaria de usar o chunk loader

**Comment by ArtpokeBr** [comment]
Já está ativo, que parte disso você não entendeu? KKKKK atualmente o FTB Utilities foi colocado até, basta carregar por ele.
