### ISSUE TITLE
Mods bugado no servidor 

### ISSUE THREAD

**Issue by linezada** [ArtpokeBr/Minecraft-Ultimato#372]
**Versão do Modpack:**
2.0 servidor e cliente 

**Descrição:**
problemas com alguns mods no servidor (parece q alma de village n dropa, grid power bugado fiz 3 dragon egg mill pra usar de grid power e ainda sim n consigo usar nada , xp obelisk n da pra colocar xp nele mais tirar o xp vai , e craft do terra steel do botania esta bugado  ( eu n mexi com botania mas um amg que joga no servidor comigo mexe e pelo oq ele me disse o craft esta muito diferente do que esta no livro e as vezes vai normal e outras nao)

(o unico q eu n testei no single player foi o botania mas o resto parece funcionar normal , estou usando as pastas config, mods, patchouli_books, resources e scripts do modpack q eu peguei dentro da .minecraft dele msm)

**Comment by ArtpokeBr** [comment]
Um tanto quanto estranho, provavelmente é coisa ai do Servidor estar errado, pois essa série de Bus citados não seriam coisas que eu possa ter feito ou possa fazer =/ se isso continuar ai, é Bug do Server. Se no Singleplayer não estiver funcionando, é mais estranho ainda, e possívelmente pode ser Bug dos Mods em si? sinceridade é a primeira vez que estão me reportando isso então é esquisito.
