### ISSUE TITLE
Meu curseforge n baixa T_T

### ISSUE THREAD

**Issue by bCmorato8** [ArtpokeBr/Minecraft-Ultimato#373]
![image](https://user-images.githubusercontent.com/80971906/111804777-2537cb80-88af-11eb-9297-e3b61b0be598.png)
Me ajude por favor!

**Comment by ArtpokeBr** [comment]
kkkkkk assim, isso ai pelo visto é problema da Overwolf, ai complica pra eu ajudar =/
