### ISSUE TITLE
Duvidas nos craftings

### ISSUE THREAD

**Issue by black5020** [ArtpokeBr/Minecraft-Ultimato#374]
Versão do Modpack:
MC Ultimato-2.0.zip

Descrição:
Os craftings do projecte quase todos estao diferentes, mais difíceis, por exemplo o alchemical chest, ele esta com um crafting mais dificil, o bau de obsidiana (do crafting do alchemical chest) era para ser um bau normal o low covalence esta com um crafing diferente tbm ao inves de usar pedra e um carvao vegetal agora é crushed emerald e alchemical coal. nao sei oque fazer.

Sugestão de Solução:
acho que deveriam colocar o craftings normais e mais faceis e tbm colocar o emc no klen star ein, alchemical coal e etc.

Screenshots:
![image](https://user-images.githubusercontent.com/81596773/112913118-745fd680-90cf-11eb-8f09-07d1a7024c82.png)

desculpe se isso for um problema bobo é minha primeira vez fazendo reclamaçao.

**Comment by ArtpokeBr** [comment]
o Nerf é proposital, isso ajuda no Balanceamento do Modpack.
