### ISSUE TITLE
Crafting impossivel da pedra filosofal (ProjectE)

### ISSUE THREAD

**Issue by Revecel** [ArtpokeBr/Minecraft-Ultimato#375]
**Versão do Modpack:**
Mais nova possivel

**Descrição:**
O crafting da pedra filosofal do ProjectE é impossivel, pois você precisa da pedra filosofal pra fazer a pedra filosofal

**Sugestão de Solução:**
Substitua este texto por uma possível solução que você acha que possa ser feita para o seu problema! isto ajuda pois muitas vezes sua sugestão pode ser boa e pode ser implementada e resolvida rápidamente! 
![image](https://user-images.githubusercontent.com/81625752/112983304-ec5fe800-9133-11eb-8032-27a82d637154.png)
![image](https://user-images.githubusercontent.com/81625752/112983333-f2ee5f80-9133-11eb-9000-33474e4eb1d8.png)
![image](https://user-images.githubusercontent.com/81625752/112983357-f97cd700-9133-11eb-9c8c-1a45a19c95b5.png)
Todos os pózinhos do PjctE precisam do Mobius Fuel, que atualmente so da pra fazer usando a pedra filosofal.
**Passo a Passo para chegar no Problema (Opcional):**
Fazer outra alternativa de craftar os pózinhos do ProjectE sem a pedra, pois atualmente é impossivel.

**Comment by ArtpokeBr** [comment]
já tentou fazer esse carvão naqueles collectors de Glowstone do Mod? e já viu TODAS as obções para se fazer estes coals? eu tenho quase certeza de que existem receitas alternativas ;p

**Comment by Revecel** [comment]
então pq o JEI nn mostra o crafting?
