### ISSUE TITLE
Problema com o mod ROOST

### ISSUE THREAD

**Issue by GabrielDG17** [ArtpokeBr/Minecraft-Ultimato#377]
As galinhas do modpack não estão botando ovos, elas apenas "botam" penas, eu testei tanto no minecraft pirata quanto no original, mas nada, eu ainda coloquei o mod roost sozinho para ver se não era problema com ele, mas não, é algum mod que está entrando em conflito e não deixa as galinhas porem seus ovos.

**Comment by JokerSpade** [comment]
> As galinhas do modpack não estão botando ovos, elas apenas "botam" penas, eu testei tanto no minecraft pirata quanto no original, mas nada, eu ainda coloquei o mod roost sozinho para ver se não era problema com ele, mas não, é algum mod que está entrando em conflito e não deixa as galinhas porem seus ovos.

Boa tarde Gabriel, não sei se já descobriu o motivo, caso não tenha, é bem simples.
As galinhas que colocam ovo no Roost são as Smart Chicken, galinhas normais que você aperta o botão direito com um livro e elas viram Smart, a qual da para fazer upgrades de 1/1/1 para 10/10/10.
As galinhas comuns do minecraft, no roost, colocam penas e não evoluem igual as outras...

Espero ter sanado esta dúvida.

**Comment by ArtpokeBr** [comment]
Obrigado por ter Respondido ele! :)
