### ISSUE TITLE
bau do projecte

### ISSUE THREAD

**Issue by Allan-LIma336** [ArtpokeBr/Minecraft-Ultimato#379]
Ola. Boa tarde. Estava jogando o mod e achei um bug. Estava no ultimato 2.0 quando completei o craft do energy condenser. Consegui fazer uma troca mas depois tudo bugou; Não consigo colocar bloco no chão, nenhum bloco. E muito menos usar o botão direito do mouse. O modpack é incrível mas com esse bug fica impossível de jogar. Por favor me ajuda arrumar esse bug.

**Comment by ArtpokeBr** [comment]
Oxi, isso é um Bug um tanto quanto incomum kkk, nunca ouvi disser sobre isso acontecer... dá uma checkada no seu TPS pois as vezes é Lag no Mapa. reabrindo o Mapa não resolve também não?

**Comment by Allan-LIma336** [comment]
Não. Criei um novo mapa pra ver. E achei outro bug. O EC ele só faz a
primeira troca e depois não troca nunca mais. O bug de não quebrar blocos é
quando vc muda de modo de jogo. Quando vou do criativo para o sobrevivência
ele para de quebrar blocos. Na vdd interagir blocos. Não quebra, não
coloca, não interage tipo arar a terra. Isso não aconteceu uma vez.
Aconteceu 3 vezes. Não sei se é só comigo mas dá um desanimo jogar. Ainda
mais esse modpack que ficou muito bom.

Em qua, 21 de abr de 2021 15:41, ArtpokeBr ***@***.***>
escreveu:

**Comment by ArtpokeBr** [comment]
Olha, pior que é a primeira pessoa me reportando isso em mêses, então minha sugestão seria reparar tudo que der ai no Jogo, talvez reinstalar o Mine e o Modpack caso haja algum arquivo zuado e talz.
