### ISSUE TITLE
Acerca do ModPack do Minecraft Ultimato, como se pode ativar itens ou outras coisas que estão desativadas?

### ISSUE THREAD

**Issue by iFury319** [ArtpokeBr/Minecraft-Ultimato#381]
Como o título diz, eu gostaria de ativar funções de mods que estão atualmente desativadas como por exemplo, o **"Watch of Flowing Time"** do **Mod ProjectE**!
Poder-me-ia ensinar a fazer isso, por favor? :)

**Comment by iFury319** [comment]
Não se precisam de se preocupar, porque eu aparento ter encontrado a solução! Não tenho a certeza absoluta se é isto mas vou enviar uma print para confirmar:
![image](https://user-images.githubusercontent.com/83165668/115991939-ed652780-a5c2-11eb-8d99-5006c4d1f40e.png)

**Comment by ArtpokeBr** [comment]
@iFury319 Está desativado por um Motivo, não recomendo ativar kkk pq na verdade na minha concepção é justamente o Player que está jogando, NÃO USAR kkk

**Comment by ArtpokeBr** [comment]
O Astral Oferece aceleração de Ticks mais balanceada e afins até kkkk, e no geral, muita gente fica usando essa porcaria e dps vem me reclamar de lag kk

**Comment by cleitin0646** [comment]
> O Astral Oferece aceleração de Ticks mais balanceada e afins até kkkk, e no geral, muita gente fica usando essa porcaria e dps vem me reclamar de lag kk

mas se eu realmente quiser ativar, testei do jeito que ele disse e não deu, consegue me ensinar?

**Comment by cleitin0646** [comment]
@ArtpokeBr

**Comment by eogrando** [comment]
Como ativa? eu realmente não consegui da forma que ele explicou!
@ArtpokeBr

**Comment by ArtpokeBr** [comment]
> Como ativa? eu realmente não consegui da forma que ele explicou! [@ArtpokeBr](https://github.com/ArtpokeBr)

Teoricamente só modificar na .cfg do ProjectE dentro da pasta configs do Modpack =)

**Comment by jojonescal** [comment]
pior que assim pra mim não foi @ArtpokeBr

**Comment by jojonescal** [comment]
vc que criou o modpack, como que vc desativou, pq aí é só fazer engenharia reversa

**Comment by ArtpokeBr** [comment]
Então, liberando pelas Configs basicamente só faz com que o Item seja utilizável provavelmente, por que pra conseguir ainda não vai ser possível já que está escondido do JEI e com sua receita removida por código.

Só pegar o ID do relógio usando um comando com ele na mão (/ct hand) e procurando nos scripts aonde eu removi certinho, não deve ser difícil.

Tô ensinando, mas honestamente, se vocês dependem do relógio pra fazer Farms, sinto que a Farm de vocês não é boa suficiente ou são muito impacientes kkkkk

**Comment by jojonescal** [comment]
tipo eu queria replicar de forma pessoal oq o jazz fez no MC imortal, e sinceramente eu n entendi nada doq vc falou sou mt leigo

**Comment by jojonescal** [comment]
consegui vlw @ArtpokeBr

**Comment by eogrando** [comment]
@ArtpokeBr Vlwww demais mano, consegui aqui, deus te abençoe paizão!

**Comment by eogrando** [comment]
@ArtpokeBr só pra confirmar, era pra mexer nos scripts do projecte né? só pra caso eu tenha feito alguma merda
(desculpa por encher o saco)

**Comment by reginaldopereirajunior2000-eng** [comment]
@jojonescal desculpa incomodar, mas você ainda lembra como arruma o relógio? Tô realmente querendo jogar com eles
