### ISSUE TITLE
Não Funciona no Linux

### ISSUE THREAD

**Issue by Hawk2811** [ArtpokeBr/Minecraft-Ultimato#383]
**Versão do Modpack:**
MC-Ultimato-2.0

**Descrição:**
Eu Tento Iniciar o Modpack com o MultiMC 5 e Não Abre

**Crash Log:**
[Crash_log.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/6408168/Crash_log.txt)

**Comment by ArtpokeBr** [comment]
Pior que analisando o Crash, recomendo jogar no Goggle o Erro do Java em questão, não sei se tem algo que eu possa fazer pra ter compatibilidade em Linux D: a Curse n funfa em Linux né?

**Comment by Hawk2811** [comment]
Acho que tem a ver com o MultiMC e Não com o Modpack Porque eu Tentei Rodar Outros Modpacks que Usam o Minecraft 1.12.2 e Nenhum funcionou
