### ISSUE TITLE
Mapa crash ao abrir

### ISSUE THREAD

**Issue by Joaovhh** [ArtpokeBr/Minecraft-Ultimato#384]
**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest".

Achei que fosse a farm que eu fiz mas o jogo da o mesmo crash depois de um tempo jogando no mundo
[crash-2021-05-06_22.40.17-server.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/6438587/crash-2021-05-06_22.40.17-server.txt)
![Screenshot_1](https://user-images.githubusercontent.com/66484978/117388085-73854600-aec0-11eb-9a46-6fae205fff69.jpg)

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/117393193-fbbc1900-aec9-11eb-824a-ad243f8ce00b.png)
 Tá escrito bem aqui, um Crafter seu está causando problemas de ticks, recomendo voltar um backup do Mapa.

**Comment by Joaovhh** [comment]
vlww, não entendo nd disso kkkkkk
