### ISSUE TITLE
Tinkers

### ISSUE THREAD

**Issue by garakr** [ArtpokeBr/Minecraft-Ultimato#385]
A forjq da tinkers não quer dispejar os  materiais derretidos nos moldes

**Comment by ArtpokeBr** [comment]
Prints? Explicação melhor? qual versão do Modpack? kkkk como se quer q eu te ajude se mal explica o ocorrido?

**Comment by ArtpokeBr** [comment]
kkkkk tranquilo, apenas passe o máximo de informação útil possível.

**Comment by garakr** [comment]
É a versão 2.0 do modpack, eu fiz a forja do tinkers mas a torneira que é  para despejar o metal derretido não está funcionando, eu clico com o botão direito e não despeja já até coloquei sinal de redstone para ver se funciona

**Comment by ArtpokeBr** [comment]
Qual o Líquido que está selecionado dentro da Smeltery? é algum que POSSA ser despejado?

**Comment by garakr** [comment]
Sim, é tem ferro derretido e ouro, mas nem na bacia que faz bloco do minério funciona

**Comment by ArtpokeBr** [comment]
Prints ajudariam.... pq estou achando que você mesmo que fez a saída da Smeltery de forma errada.

**Comment by ArtpokeBr** [comment]
o bloco de saída da Smeltery, está pro lado certo?

**Comment by garakr** [comment]
Sim, já coloquei de tudo que é jeito

**Comment by ArtpokeBr** [comment]
Olha, eu tenho quase 100% de certeza de que é um problema seu ai.... não diria que é algum problema com o Modpack em si... pelo menos até onde eu saiba, se foi a primeira pessoa que reportou isso inclusive kkk, então... vou fechar o problema. pesquise sobre o Mod pra tentar ver, ou apenas vá no meu Discord talvez perguntar pra alguém se há algo acontecendo.

**Comment by garakr** [comment]
Consegui resolver, tinha um plugin e acabou de crash o Pc
