### ISSUE TITLE
Items, Menus, etc do Industrial Craft 2 sem Nomes

### ISSUE THREAD

**Issue by Hawk2811** [ArtpokeBr/Minecraft-Ultimato#386]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
MC-Ultimato-2.0

**Descrição:**
Eu Instalei o Modpack mas eu Adicionei alguns outros Mods que Eu Gostaria que Tivesse já por Padrão no Modpack

Mods Instalados

CC Tweaked

Davincis Vessels Mod

**Crash Log:**
Sem Nenhum Crash Por enquanto

**Screenshots:**
![image](https://user-images.githubusercontent.com/55853571/119887654-c758dd00-bf0a-11eb-81c0-58723c88ff21.png)

**Comment by ArtpokeBr** [comment]
Eu já vi esse problema acontecer, mas não sei oq causa exatamente... tenta desinstalar a versão atual do IC2 ai e instalar a mais recente.

**Comment by Hawk2811** [comment]
Atualizei o IC2 e Deu Bug com o Advanced Solar Panels

![image](https://user-images.githubusercontent.com/55853571/120083643-71b63900-c0a0-11eb-80af-510ae948f550.png)

**Comment by ArtpokeBr** [comment]
Não é um bug, o Advanced Solar Panels depende do IC2, então provavelmente, você precisa atualizar o Advanced Solar Panels tbm :)

**Comment by Hawk2811** [comment]
Corrigi o Problema Removendo o Advanced Solar Panels e Atualizando o IC2

Eu Removi Por Causa que o Site da CurseForge ta Fora do ar e não consegui baixar uma versão mais nova do Advanced Solar Panels

**Comment by ArtpokeBr** [comment]
Ok, quando o Site retornar, se desejar, pode colocar de volta :)
