### ISSUE TITLE
Laga muito tento jogar mas ñ da. (Meus componentes em baixo)

### ISSUE THREAD

**Issue by Leozinnn7777** [ArtpokeBr/Minecraft-Ultimato#387]
COMPONENTES : 
Notebook Samsung books 

16 GB de RAM
INTEL CORE i7
Placa de vídeo nvidia GeForce mx 110

O QUE OCORREU:
Entrei no modpack muito feliz pois era a primeira vez no modpack e era um fã! O carregamento foi rápido e usou apenas 5GB de RAM tentava andar mas não dava apertava F3 e demorava para responder e quando respondia caia de 22 FPS para 1 FPS!!! Fiquei muito chateado e tive que jogar vanila :(   Se puderem diminuir a quantidade de Mods ou dar um jeito na queda de FPS e no lag seria muito bom

**Comment by ArtpokeBr** [comment]
Aloque um pouco mais de RAM, coloca uns 7 ou 8GB já que sei PC consegue, e deve rodar tranquilamente.

**Comment by Leozinnn7777** [comment]
> Aloque um pouco mais de RAM, coloca uns 7 ou 8GB já que sei PC consegue, e deve rodar tranquilamente.

Bem não sei como coloca mais GB de ram no modpack poderia me explicar?

**Comment by Leozinnn7777** [comment]
Eee poderia me explicar melhor como posso fazer para o modpack rodar mais rápido?

**Comment by ArtpokeBr** [comment]
> > Aloque um pouco mais de RAM, coloca uns 7 ou 8GB já que sei PC consegue, e deve rodar tranquilamente.
> 
> Bem não sei como coloca mais GB de ram no modpack poderia me explicar?

No launcher da Curse, apenas clique com o botão direito na instância, vá em opções de perfil, e vai ter uma caixinha pra marcar relacionada á memória, se desmarca ela e usa o Slider pra selecionar o quanto desejar.

**Comment by Leozinnn7777** [comment]
Ok obrigado

**Comment by Leozinnn7777** [comment]
Vou tentar se não funcionar contato novamente

**Comment by Leozinnn7777** [comment]
Funcionou obrigado pode marcar como resolvido
