### ISSUE TITLE
O servidor do ultimato não está funcionando

### ISSUE THREAD

**Issue by Leozinnn7777** [ArtpokeBr/Minecraft-Ultimato#389]
Meu sonho era ver as construções dos youtubers e quando o modpack finalmente da o servidor eu não consigo entrar fica aparecendo "unknow host" se puder resolver esse problema ficarei feliz

IP DO SERVIDOR COM PROBLEMA: ultimato.infinitycraft.com.br:25623

**Comment by ArtpokeBr** [comment]
Sendo bem sincero, EU não sou dono do Servidor kkk e este campo aqui no Github é destinado para Bugs relacionados ao Modpack, O Modpack não tem nenhuma ligação com o servidor kkk

**Comment by Leozinnn7777** [comment]
Você conhece o dono do server?

**Comment by Leozinnn7777** [comment]
Se conhecer reporta pra ele isso e vê se ele consegue corrigir

**Comment by ArtpokeBr** [comment]
Ué kkkk, mas é você que está com o problema, e o servidor não tem ligação com o Modpack D: então na verdade, eu recomendaria á você mesmo reportar para o dono já que está com esse problema em questão.

**Comment by Leozinnn7777** [comment]
Mas quem é o dono?
