### ISSUE TITLE
Problema com EMC

### ISSUE THREAD

**Issue by Pedr0oouu** [ArtpokeBr/Minecraft-Ultimato#390]
Fml comecei a jogar mas comecei a perceber que muitos item do proprio mod EMC não tem valor isso é normal ou bug, me ajuda ai fml 
![Screenshot_1](https://user-images.githubusercontent.com/88523137/128451628-e19069d9-ce08-4e23-9f11-bff9ce199c4d.png)
um exemplo

**Comment by ArtpokeBr** [comment]
Então kkk, se podia ler justamente a Tooltip, certos itens tiveram seus EMC's Removidos, este na sua mão em questão, com o propósito de incentivar automações e soluções criativas, não é Bug :)
