### ISSUE TITLE
Philosopher stone

### ISSUE THREAD

**Issue by Franklinbastos** [ArtpokeBr/Minecraft-Ultimato#391]
Quando clico na philosopher stone pelo JEI não aparece crafting nenhum. Simplesmente não abre nada, quando clico em outros itens aparece os craftings normalmente mas na philosopher não.

**Comment by ArtpokeBr** [comment]
prints? ela deveria ser feita no altar do Blood Magic.

**Comment by Franklinbastos** [comment]
Acho que tem algo a ver com o arquivo "ProjectERecipesAndFixes" da pasta "Scripts", pois tirei esse arquivo do modpack e o recipe dela voltou ao padrão do mod. tentei ver se tinha algo escrito errado ou algo assim mas não consegui indentificar :( kkkk.
Ja mando os prints

**Comment by Franklinbastos** [comment]
eu tirei alguns mods do modpack tambem pra deixar mais leve pq nao tava rodando direito no meu pc, pode ser por isso tambem. mas o blood magic eu nao tirei

**Comment by Franklinbastos** [comment]
![WhatsApp Image 2021-08-13 at 14 11 54](https://user-images.githubusercontent.com/88871486/129396165-1c80c6bc-b012-45e8-b631-573d0bae97ad.jpeg)
![WhatsApp Image 2021-08-13 at 14 11 54 (2)](https://user-images.githubusercontent.com/88871486/129396209-ad04e599-2307-4af4-a501-4d4decef2778.jpeg)
![WhatsApp Image 2021-08-13 at 14 11 54 (1)](https://user-images.githubusercontent.com/88871486/129396220-194ad520-e3e4-4b32-9c02-f9b98e2ecd76.jpeg)

**Comment by ArtpokeBr** [comment]
Assim, se você tirou certos Mods do Modpack, eu literalmente não consigo dar muito suporte.... se você tirou o Blood Magic, a receita não vai funcionar kkkk

**Comment by ArtpokeBr** [comment]
tu não notou que tirando mods dá altos erros (provavelmente) no chat ao abrir um mapa?

**Comment by ArtpokeBr** [comment]
Nossa e dá pra notar isso claramente ali, o Relógio foi desativado e no teu jogo ele aparece  kk
