### ISSUE TITLE
problema na istalacão

### ISSUE THREAD

**Issue by pedrinnfoda** [ArtpokeBr/Minecraft-Ultimato#392]
nn estou conseguindo estalar o ultimato esta dando erro mas nos outros mods estala normalmente tem como verificar  o modpack?

**Comment by ArtpokeBr** [comment]
isso é um problema que aparenta estar acontecendo no dia de hoje na CurseForge, eu diria pra tentar esperar até amanhã, ou tentar baixar o Pack pelo MultiMC.

**Comment by ArtpokeBr** [comment]
por que não é algo que eu possa resolver :T
