### ISSUE TITLE
MC Ultimato tem problema pra instalar

### ISSUE THREAD

**Issue by F4lt** [ArtpokeBr/Minecraft-Ultimato#395]
**Versão do Modpack:**
Teoricamente a 1.0.5

**Descrição:**
Jogo no modpack do Ultimato a um tempo porém esses dias houve um conflito entre mods durante a inicialização do modpack então decidi reinstalar a partir do CurseForge (já tinha sido usado para primeira instalação) porém quando chegava perto dos 100 a 110 mods ele parava a instalação e dizia que tinha ocorrido um erro (o código do erro era 3132583 se for ajudar) e a instalação falhava. por sorte tinha feito um backup da pasta antes de reinstalar e descobri que o conflito era do mod EnderIO Base com a nova versão do EnderIO.

**Sugestão de Solução:**
Pela quantidade de vezes que testei a instalação cheguei a conclusão que algum mod presente tanto nas versão atuais quanto nas antigas (Como a 1.0.5 e 1.0.4) foi privado pelo autor, quando o curseforge detecta que não pode baixar o mod ele cancela todo o download do modpack.

**Crash Log:**
Não houve um crash pois o problema não é in-game então nem a pasta de crash-reports foi criada.

**Comment by F4lt** [comment]
Só deixando claro que eu tentei baixar tanto a ultima versão como que eu jogo atualmente e o erro é o mesmo. Eu ainda consigo jogar depois de tirar o EnderIO Base mas as próximas pessoas que forem jogar provavelmente vão ter o mesmo problema na instalação.

**Comment by ArtpokeBr** [comment]
Rapaiz, infelizmente isso tá acontecendo com muita gente! :T não é a primeira vez que escuto essa semana dessa instabilidade, então a única coisa que posso te recomendar é esperar até que melhore, por que não é um Erro meu no caso, é apenas uma instabilidade nos servidores deles em que impossibilidade de baixar. o que se pode tentar fazer é abrir o arquivo de Manifest da última versão, e ver se o código "3132583" é o ID de algum Mod que não foi baixado mesmo, pois no Manifest todos os mods do Modpack são listados e possuem seu respectivo ID.

**Comment by ArtpokeBr** [comment]
Encontrando um Mod que possa estar causando esse Erro, eu ou você mesmo na hora pode entrar na página dele na Curse e ver se aconteceu algum tipo de privação ou coisa do tipo.
