### ISSUE TITLE
bug schematic

### ISSUE THREAD

**Issue by Babinhhex** [ArtpokeBr/Minecraft-Ultimato#396]
Toda vez que eu crio um mapa, infelizmente uma tela do schematic fica repetindo o tempo todo, e não me deixa jogar

**Comment by ArtpokeBr** [comment]
Vídeo ou print por favor?

**Comment by Babinhhex** [comment]
![44ec98bc-5e88-4d79-af4e-3a578ae9db50](https://user-images.githubusercontent.com/91135688/134237360-59c896ee-578a-4a11-8a8c-6c3dc8be138b.jpg)

**Comment by ArtpokeBr** [comment]
Só apertar a tecla certa no Keypad que deve remover, dá uma olhada pra ver se vc n colocou alguma tecla errada dentro das configs de controles, e na pior das hipóteses, só desativar o mod das Schematicas.

**Comment by Username211244367868** [comment]
Mano, posso falar um bug meu com outros modpacks?
