### ISSUE TITLE
Problema com modpack Ultimato no servidor

### ISSUE THREAD

**Issue by PedrinhoLXD** [ArtpokeBr/Minecraft-Ultimato#4]
#1
Oi! Eu e meus amigos adoramos o seu modpack do Ultimato e decidimos comprar um server na enxada para jogarmos. Já tinhamos jogado modpack nos servidores da enxada antes e nunca tinha acontecido este problema. O server abre normalmente com todos os mods, mas quando um player tenta entrar, aparece um erro dizendo:

**_"com.google.common.util.concurrent.UncheckedExecutionException:java.lang.IllegalStateException: Recipe minecraft:wheat (net.minecraft.item.crafting.ShapedRecipes@58ec8271) produces unregistered item minecraft:wheat (net.minecraft.item.Item@7e3ee128)"._**

Nunca tinha visto esse erro. Eu consigo criar um mundo normal e jogar, mas na hora q entro no servidor da esse erro. Já refiz o servidor duas vezes e msm assim não mudou nada. 

Se for melhor para ti conversar comigo, pode mandar DM no meu twitter: @pedrofochesatto. (te mando uma print do erro se precisar)

Queremos muito jogar seu modpack, mas esse erro não sabemos como resolver. 

 

Parabéns pelo seu trabalho. Não foi à toa que te escolheram.

Edit: **RESOLVIDO! COLOQUEI A PASTA CONFIG DO MEU CLIENT NO SERVIDOR!**

**Comment by ArtpokeBr** [comment]
Mas esse erro impede vocês de jogar?

**Comment by PedrinhoLXD** [comment]
> Mas esse erro impede vocês de jogar?

Sim, a gente gostaria de jogar juntos, mas quando tentamos entrar no server aparece esse erro. Mas quando vamos no singleplayer, conseguimos criar o mundo e jogar de boa. Posso estar colocando os mods de maneira errada para criar o server, mas eu fiz da mesma maneira que eu fiz nos outros servers e deu tudo certo neles.

**Comment by Christtiann** [comment]
@PedrinhoLXD
Eu consegui abrir para server, porem com algumas alterações na pasta config.
Vai na pasta de config do seu minecraft e do seu servidor e coloca o arquivo que esta dentro deste zip.
[fastbench.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5598517/fastbench.zip)
Talvez isso resolva...

**Comment by ArtpokeBr** [comment]
Obrigado pela ajuda @Christtiann, eu de longe não sou experiente com essas doideras de Server kkk

**Comment by PedrinhoLXD** [comment]
> @PedrinhoLXD
> Eu consegui abrir para server, porem com algumas alterações na pasta config.
> Vai na pasta de config do seu minecraft e do seu servidor e coloca o arquivo que esta dentro deste zip.
> [fastbench.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5598517/fastbench.zip)
> Talvez isso resolva...

Vlw pela ajuda, mas n mudou. Talvez eu tenha feita algo de errado na hora de criar o server. N sei mais oq pode ser.

**Comment by ArtpokeBr** [comment]
o Erro é bem claro, é algo relacionado ao jogo não registrando a recipe do Trigo, porém, isso é algo bizarro pois eu nem mexi nisso kkk preciso que tu me mande o report corretamente, manda o Log em si do server ou coisa parecida.

**Comment by PedrinhoLXD** [comment]
> o Erro é bem claro, é algo relacionado ao jogo não registrando a recipe do Trigo, porém, isso é algo bizarro pois eu nem mexi nisso kkk preciso que tu me mande o report corretamente, manda o Log em si do server ou coisa parecida.

O erro acontece após eu tentar entrar: Nick MrPedroL
[latest.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5598791/latest.zip)

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/100272858-96d3be80-2f3a-11eb-8c94-82faf6e9b48f.png)
No log não vejo nenhum erro, estranho... aparece algo na sua tela?

**Comment by PedrinhoLXD** [comment]
Primeiro aparece esse:
![Screenshot_1](https://user-images.githubusercontent.com/75032890/100274173-c08de500-2f3c-11eb-8737-e7267bd398e0.png)

Depois aparece o erro q eu disse antes:
![Uploading Screenshot_2.png…]()

**Comment by PedrinhoLXD** [comment]
Primeiro aparece esse:
![Screenshot_1](https://user-images.githubusercontent.com/75032890/100274228-d69ba580-2f3c-11eb-8072-34c944090cef.png)

Depois aparece esse:
![Screenshot_2](https://user-images.githubusercontent.com/75032890/100274250-dd2a1d00-2f3c-11eb-8da3-8756d80798dc.png)

**Comment by Christtiann** [comment]
"Fatally missing registry entries"
É erro de config... vc nao deve ter colocado a pasta config no server corretamente.
Faz assim...

**Comment by PedrinhoLXD** [comment]
Como q eu coloco essa pasta corretamente, pq ela é gerada automaticamente quando instalo o server.

**Comment by PedrinhoLXD** [comment]
**RESOLVIDO!

COLOQUEI A PASTA CONFIG DO MEU CLIENT NO SERVIDOR!**

vlw @Christtiann e @ArtpokeBr pela ajuda! TMJ

**Comment by ArtpokeBr** [comment]
AH resolveu? Muito bom :)
