### ISSUE TITLE
Spawner

### ISSUE THREAD

**Issue by Squila** [ArtpokeBr/Minecraft-Ultimato#404]
- estou tento problemas com os mobs spawners, nenhum esta funcionando corretamente, e os da twight não estão doprando os boss

**Comment by ArtpokeBr** [comment]
está no Update mais recente? falta informação.

**Comment by Squila** [comment]
estou jogando na versão 2.2, baixei ele ontem pelu curso, so fiz iniciar o modpack sem alterar nada

**Comment by Squila** [comment]
> * estou tento problemas com os mobs spawners, nenhum esta funcionando corretamente, e os da twight não estão doprando os boss
