### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Gu0704** [ArtpokeBr/Minecraft-Ultimato#405]
está ocorrendo erro com o java ao iniciar, tanto no curseforge quanto no tlaucher

**Comment by ArtpokeBr** [comment]
Ok, mas e mais informação? não tem? como que vou saber exatamente o erro sem prints, sem um log ou coisa parecida kkk

**Comment by tiorick1234** [comment]
man, está acontecendo um bug no mod @applied energy 2, que não dá pra colocar nada no sistema e nem mexer, tente criar um sistema de applied energy ai, apenas não funciona

**Comment by tiorick1234** [comment]
oq eu faço?

**Comment by ArtpokeBr** [comment]
como está o seu sistema atualmente? tentou ver primeiro se é uma falta de energia? eu estou pra lançar um hotfix pro Modpack apenas pelo fato de ter gente tendo uns pequenos crashes, mas isso é novidade kkk

**Comment by ArtpokeBr** [comment]
e um detalhe, abra um issue, pois isso não relacionado á este aqui, inclusive, vou fechar este aqui.
