### ISSUE TITLE
Bug do AE2

### ISSUE THREAD

**Issue by ReaperHimura** [ArtpokeBr/Minecraft-Ultimato#406]
Não fiz nada de mais, apenas coloquei os cabos do AE2 ligados a um baú para jogar meus itens no sistema, e o jogo simplesmente crashou, e por algum motivo ele também falha ao pegar o log de crash

Fiz a mesma coisa em um mundo de testes, e o resultado foi o mesmo, quando eu tenho que passar um item pelo ME ExportBus, o jogo crasha sem motivo 

Estou no começo e isso me impede de prosseguir, e como é um problema com o AE2, fica impossível continuar a jogar sem ele 

![Captura de tela 2022-03-28 143124](https://user-images.githubusercontent.com/75766184/160455478-8f09e90f-7160-46f3-946e-5cd5ade66af3.png)

**Comment by ArtpokeBr** [comment]
Tem como mandar o Crash Report? só essa tela n revela informações mais específicas.

- além disso, tentar atualizar manualmente o AE2 pra ver se corrige certinho.
essa versão do AE2 tem atualizado com frequência.

**Comment by ReaperHimura** [comment]
> Tem como mandar o Crash Report? só essa tela n revela informações mais específicas.
> 
> * além disso, você pode tentar atualizar manualmente o AE2 pra ver se corrige certinho.
>   essa versão do AE2 tem atualizado com frequência.

**Comment by ReaperHimura** [comment]
> Tem como mandar o Crash Report? só essa tela n revela informações mais específicas.
> 
> * além disso, você pode tentar atualizar manualmente o AE2 pra ver se corrige certinho.
>   essa versão do AE2 tem atualizado com frequência.

Consegui, eu mesmo atualizei como vc sugeriu

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/all?filter-game-version=2020709689%3A6756

o link do mod, pra quem quiser, é só pegar a versão que o mine tiver

**Comment by ArtpokeBr** [comment]
então kkk vc meio que não atualizou, por que o Applied que você inclusive pegou o link ai é a versão normal, que não é mais mantida pra 1.12! https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files o Modpack usa a versão extendida :)
