### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LUK3123** [ArtpokeBr/Minecraft-Ultimato#407]
o computador do applied nao abre

**Comment by ArtpokeBr** [comment]
eu precisa de mais informações.... um pequeno vídeo talvez mostrando... ou talvez só uma descrição melhor sobre como está o seu sistema kkk

**Comment by ArtpokeBr** [comment]
outra pessoa reportou recentemente algo parecido... eu precisaria de uma descrição melhor realmente, porém, eu devo preparar essa semana um hotfix pra atualizar o AE2 e possivelmente corrigir isso.

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/167275842-b05599fd-591c-4b22-9594-20b79463b796.png)
O Modpack acabou de atualizar, se o problema persistir, por favor comente neste issue. =)
