### ISSUE TITLE
erro na instalação

### ISSUE THREAD

**Issue by Luccao2** [ArtpokeBr/Minecraft-Ultimato#408]
opa tranquilo, estava vendo os vdos do minecraft ultimato e quiz baixar, fiz tudo direitinho coloquei alocação máxima entre 6 e 8 mil mb, mas não consegui entrar. Apareceu um erro falando qwue o id dos mods nãoo eram possíveis serem identificados e apareceu tb que algumas tarefas da resolução de IDs dos mods falharam. 
Gostaria que me ajudasse pois achei muito legal e ficaria bem triste se eu n conseguir jogar este mod
Obg pela atenção!

**Comment by ArtpokeBr** [comment]
Opa então.... se puder mandar o Crash Report (caso tenha crashado) e/ou o Log por favor. fica difícil diagnosticar o problema só por uma pequena descrição por texto ;p

**Comment by Luccao2** [comment]
por onde posso te mandar a foto ? Acho que por aqui n tem comko...

**Comment by ArtpokeBr** [comment]
> por onde posso te mandar a foto ? Acho que por aqui n tem comko...

Claro que tem! só tirar uma print da tela, ou no caso que nem eu pedi, abra a pasta do jogo, e verifique se foi gerado um crash report, ou se não tiver sido gerado, me mande o arquivo de latest, que é gerado na pasta logs, no caso, mande ele logo após você crashar ;p

**Comment by linzinho** [comment]
oi queria saber onde fica as pastas de beckup do modpack.

**Comment by ArtpokeBr** [comment]
Recomendo fazer peguntas e tirar dúvidas pelo Discord! =)

Mas se forem os Backups de seu mapa, existe uma pasta chamada "backups" nos arquivos do Modpack.

**Comment by linzinho** [comment]
obrigado.
