### ISSUE TITLE
Abertura de servidor

### ISSUE THREAD

**Issue by Duque202** [ArtpokeBr/Minecraft-Ultimato#41]
Abri um servidor com os ficheiros do Ultimato-1.0.2.zip, sem erro nenhum. Mas ao entrar no servidor aparece me este erro:

Sendo que no minecraft curseforge a versão é a mesma, será que existe alguma problema com os ficheiros do ender io?

![mine](https://user-images.githubusercontent.com/75282120/100675473-f24ce480-335e-11eb-82a2-089e5e18c5fc.png)

**Comment by ArtpokeBr** [comment]
olha, tá escrito ai, não sei oq tu fez mas muito provavelmente tu atualizou o EnderIO e isso gerou uma porrada de problemas, isso ai é o EnderIO estando diferente do no server.

**Comment by Duque202** [comment]
Eu não fiz nada. Não atualizei nada. Baixei a pasta Minecraft Ultimato-1.0.2.zip e abri o servidor
Abri o curseforge e abri o modpack com a versão 1.0.2.. e aparece essa mensagem. Já procurei e não encontrei a pasta desses mods na pasta que baixei para tentar colocar igual ao forge pode ajudar a localizar?

**Comment by ArtpokeBr** [comment]
pode ser problema da CurseForge, ela pode estar tendo uns probleminhas pra baixar a versão correta do EnderIO ou coisa do tipo, até ontem ela estava em manutenção então é compreensível. A Versão mais recente do EnderIO estava causando Crashes mesmo por isso não coloquei ela na versão mais recente do Modpack. então certifique-se de que tanto no server, tanto no seu client ai está com esta versão aqui do EnderIO: 
![image](https://user-images.githubusercontent.com/44851727/100793853-87052000-33fb-11eb-9274-0a7271e2189f.png)
