### ISSUE TITLE
Dúvidas em Relação ao Modpack

### ISSUE THREAD

**Issue by Luccao2** [ArtpokeBr/Minecraft-Ultimato#412]
opa tranquilo, consegui comprar o minecraft e agr estou jogando sem ser pirateado, normalçl. Mas acho q os mods n estão funcionando para mim. Um dersses eh o mod veim miner. Pelos videos que assisti no youtube, ele está incluso noi modpack, caso não esteja, vc sabe se tem como eu colo-calo

**Comment by ArtpokeBr** [comment]
Olha, o o VeinMiner sim está incluso.

**Comment by ArtpokeBr** [comment]
E Respondendo suas perguntas anteriores, sim, está tudo certo com o Modpack.

e o Mod que cuida da Excavation é o FTB Ultimine.
