### ISSUE TITLE
ender storage

### ISSUE THREAD

**Issue by Franklinbastos** [ArtpokeBr/Minecraft-Ultimato#417]
ola, estou jogando o modpack e ao decorrer do jogo me dei conta que o mod ender storage está no modpack mas não está habilitado dentro do game, alguma dica?

**Comment by ArtpokeBr** [comment]
Ué, como assim não está habilitado? Os itens não possuem receitas, é isso? Imagens por favor.

**Comment by Franklinbastos** [comment]
achei, na verdade foi erro meu, o modpack está traduzido e eu tava procurando em ingles hahahaha, desculpa. valeu pela prontidao.

**Comment by ArtpokeBr** [comment]
Ah tranquilo kkk
