### ISSUE TITLE
dúvida sobre o modpack

### ISSUE THREAD

**Issue by Japonesss** [ArtpokeBr/Minecraft-Ultimato#418]
estou jogando na versão 2.3 do modpack pelo curseforge, mas andei revendo a série ultimato pelo canal do nofaxu e creio que pode haver alguns mods que ele usa na série que não está incluido no modpack, como por exemplo o simple store network que é um mod muito bom e de grande ajuda no inicio do modpack e entre outros mods que são mostrados na série mas por acaso não contém no modpack que estou jogando atualmente

**Comment by ArtpokeBr** [comment]
Opa, então, desde o Update 2.0 o Modpack sofreu alguns ajustes, principalmente em relação a performance e balanceamento.

Por que o foco disso? bom, a ideia é que justamente pela série já ter terminado, finalmente poderia ser implementado ajustes e balanceamentos focados no Player.

Se bem me lembro, no exemplo do Simple, foi retirado por redundância. por que haver um Mod de Storage Early game se o Modpack já possui algumas opções? 

No geral alguns fatores foram levados em consideração, mas o principal ponto é que o Modpack em sua concepção foi feito para youtubers e depois adaptado para players.
