### ISSUE TITLE
Som indesejável no Magma Crucible (TE)

### ISSUE THREAD

**Issue by noeneto** [ArtpokeBr/Minecraft-Ultimato#42]
Ao colocar um pouco de Pyrotheum Dust no Magma Crucible para derreter, não pude deixar de notar o som de entrada do modpack sendo tocado em looping até que os ouvidos explodam.

**Comment by ArtpokeBr** [comment]
ih rapaiz kkkkk, Ok, achei que tinha colocado o Som pra n substituir nada, mas encontraram!
