### ISSUE TITLE
Crash causado pelo Refined Storage

### ISSUE THREAD

**Issue by Gpiovesana** [ArtpokeBr/Minecraft-Ultimato#420]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
Versão 2.3

**Descrição:**
O modpack crashou ao clicar em "Prioridade" dentro da unidade de disco. Eu estava na dimensão de void do mod SimpleVoidWorld.
**Sugestão de Solução:**
Não sei.

**Passo a Passo para chegar no Problema (Opcional):**
Estava no mundo de void, com um hd do refined de 64k na mao, e cliquei em prioridade. Não havia nenhum armazenamento externo conectado.

**Crash Log:**
Esta anexado
**Screenshots:**
Também está em anexo. 
![imagem_2022-09-08_215351237](https://user-images.githubusercontent.com/81973386/189250170-a1759651-be69-4e08-a857-4b3dbb252753.png)
![imagem_2022-09-08_215431227](https://user-images.githubusercontent.com/81973386/189250211-33892473-62e0-46f0-8bb2-57bb6f5b719c.png)

[crash-2022-09-08_21.42.06-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/9531454/crash-2022-09-08_21.42.06-client.txt)

**Comment by ArtpokeBr** [comment]
Faz um teste aleatório pra mim, está usando algum chapéu?
E outra coisa, se tem uma Mobtrap por ai correto? pelo menos é o que parece, dá uma olhada se n tá sobrando orbes de XP não coletados.

Por que pelo crash, pode ter sido uma lagada no servidor, ele foi relacionado ao Jogo não ter conseguido atualizar o menu ao clicar no botão.

**Comment by Gpiovesana** [comment]
Estava usando um chapéu, mas não tinha nada no chão. Vou fazer o teste sem o chapéu pra ver.

> Faz um teste aleatório pra mim, está usando algum chapéu? (se estiver, tenta tirar) E outra coisa, se tem uma Mobtrap por ai correto? pelo menos é o que parece, dá uma olhada se n tá sobrando orbes de XP não coletados.
> 
> Por que pelo crash, pode ter sido uma lagada no servidor, ele foi relacionado ao Jogo não ter conseguido atualizar o menu ao clicar no botão.
