### ISSUE TITLE
Bug do Draconic (Fusion Crafting Injector)

### ISSUE THREAD

**Issue by 1kovacs** [ArtpokeBr/Minecraft-Ultimato#422]
Versão do Modpack: 2.3

Descrição:
Bom, basicamente é isso, no mod do Draconic, as Fusion Crafting Injector, todas elas, nenhuma recebe energia, de nenhuma forma, testado todos os cabos, todas as formas de passar energia, em outros mundos criados, mas nada resolvido e não recebe a energia.

**Sugestão de Solução:**
Não faço a minima ideia de como resolver

**Passo a Passo para chegar no Problema (Opcional):**
-x-

**Crash Log:**
-x-

Screenshots:
https://imgur.com/4Xkwnmw

**Comment by ArtpokeBr** [comment]
A Energia só é necessária quando o Craft for iniciado, leve em consideração também, a altura dos Injectors em relação ao Core. isso pode também influenciar.
Testei aqui e segue normal, vou fechar.
