### ISSUE TITLE
Não consigo baixar o Modpack.

### ISSUE THREAD

**Issue by Rick2008** [ArtpokeBr/Minecraft-Ultimato#423]
Eu estava tentando colocar o modpack no multimc, e não foi disse que "o arquivo não tem modpack legivel". Desculpa se aqui não é o local ideal para reportar isso.

**Comment by ArtpokeBr** [comment]
Hmmm, sim não se preocupe, aqui é o local pra isso sim.
Só me mante um Print pra eu ver exatamente o Erro. o MultiMC n aceita mais arquivos da curse aliás.

**Comment by Rick2008** [comment]
![image](https://user-images.githubusercontent.com/119884661/205786273-c2d2482e-9b5b-45bb-905a-08129733aea6.png)

**Comment by Rick2008** [comment]
Ata n sabia que n aceitava mais, mas como eu resolvo isso?

**Comment by ArtpokeBr** [comment]
Olha, isso tem haver com algumas alterações na licença da Curse atualmente e tal... porém, se quer algo que funciona exatamente como o MMC, procura o Launcher chamado Prism. ele é um fork do MMC que consegue burlar essas restrições da curse e baixar Modpacks dela.

**Comment by Rick2008** [comment]
Ok obg:)
