### ISSUE TITLE
Versões mais antigas

### ISSUE THREAD

**Issue by DurazzN** [ArtpokeBr/Minecraft-Ultimato#424]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Descrição**: É possível jogar em versões mais antigas do modpack? Na curse só tem as versões de 2.0 pra frente, queria saber se tem como jogar as anteriores tipo a 1.03.

**Comment by ArtpokeBr** [comment]
Então, eu justamente arquivei essas versões por não ter um Motivo para usa-las. o update lançado essa semana por exemplo trouxe múltiplas correções e melhorias de performance =)

e acredite, tinha gente fazendo reports de problema jogando em versões mais antigas, então meio que arquivar facilitou minha vida kkk
