### ISSUE TITLE
Jogo trava ao tentar abrir o modpack

### ISSUE THREAD

**Issue by FHumenhuk** [ArtpokeBr/Minecraft-Ultimato#425]
Versão do Modpack:
2.4

Descrição:
Baixei o modpack usando o programa do CurseForge e, aparentemente, tudo estava certo pra poder usar o modpack. Porém quando tento entrar, o jogo sempre trava na mesma parte e o Mine para de responder. Vou deixar um print de como está a tela.

Screenshots:
![image](https://user-images.githubusercontent.com/120544861/207509609-bd1bf091-eeda-4296-b201-42df6e8d50d5.png)

Consegue me ajudar? Sou bem novo nessa parte de mods e realmente não sei como posso resolver. Obrigado!

**Comment by ArtpokeBr** [comment]
Ok, se é bem novo faz sentido o erro realmente bem comum em novatos.

Para Modpacks, você SEMPRE precisa prestar a atenção nas recomendações de alocação se memória.

Falando em termos simples, cada modpack vai ter um requerimento de Memória Alocada para rodar plenamente.

E no caso do Ultimato, recomendo que aloque pelo menos 6GB de Ram para o Modpack. 
![image](https://user-images.githubusercontent.com/44851727/207671035-12b4f6c9-fd16-4346-b2c4-8df2a3582d3c.png)
![image](https://user-images.githubusercontent.com/44851727/207671082-bfbc8d5f-87ea-464c-9ffd-f693d68e02a7.png)

**Comment by ArtpokeBr** [comment]
Nas imagens referenciadas acima, clique na instância do Modpack, abra as Profile Options, Desmarque a caixa de "Use System Memory Settings" e subsequencialmente utilize o Slider para alocar o quanto desejar. Se tiver 16GB no PC, aloque no máximo 8GB.

Se tiver só 8GB no PC, aloque no máximo 6GB.

**Comment by ArtpokeBr** [comment]
Fechando, não houve mais nenhuma atividade e acredito já ter sido resolvido o problema =)
