### ISSUE TITLE
Instalação trava no Mod MrCrayfishs Vehicle 

### ISSUE THREAD

**Issue by Cajuelson** [ArtpokeBr/Minecraft-Ultimato#427]
A Minha instalação não sai do Mod 106 que é o MrCrayfishs Vehicle

**Comment by ArtpokeBr** [comment]
Ele mantem a instalação infinitamente dizendo que está instalando o MrCrayfish? olha, pelo que parece seria um problema do Launcher, não algo que eu possa diretamente mexer...

Recomendação, tenta testar a instalação do Modpack em outro Launcher pra ver se continua assim =)
