### ISSUE TITLE
problema na hora de entrar no mapa

### ISSUE THREAD

**Issue by lopo0606** [ArtpokeBr/Minecraft-Ultimato#428]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!
Quando eu vou entrar no mapa da uma tela que diz que o problema é desconhecido, eu não sei dizer oque é mas veja.

![image](https://user-images.githubusercontent.com/128237249/226114318-bca304af-87c8-482a-b155-8f2f76e2b4e7.png)

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
tem como me mandar o Crash Report pls? só mandar o mais recente encontrado justamente na pasta Crash Reports.
