### ISSUE TITLE
O Jogo não deixa criar mundo no topography. Ai fica cheio de dragão e crasha ajuda pfvr

### ISSUE THREAD

**Issue by FoxOM1** [ArtpokeBr/Minecraft-Ultimato#429]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
2.4

**Descrição:**
O modpack não deixa criar mundo no topography. Então enche de dragões e crasha o jogo

**Sugestão de Solução:**
Faz um vídeo ou atualize pra voltar o menu de criação do mundo com o topography ! 

**Passo a Passo para chegar no Problema (Opcional):**
Um jogador-->criar mundo---> tipo de mundo cade o topography??

**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest".

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
Oxi, Bom, O Topography foi removido faz alguns Updates para justamente simplificar para os Players e evitar dificuldades na hora de se fazer um Servidor.

De fato, os Dragões agora retornaram pro Overworld normalmente, mas o que é estranho é isso de crashar para você.... poderia enviar um Vídeo alguma coisa? ou pelo menos o Crash Report? só falar não adianta muito...

**Comment by FoxOM1** [comment]
Mil desculpas não tirei print mas vou enviar achei que nem ia me responder kk. Eu pedi ajuda porque pqp mano você é incrível fez o melhor modpack que eu já vi   na vida obrigado por isso vou tentar tirar print amanhã assim que sair do trabalho. Não crasha assim que entro crasha ao chegar perto do ninho, eu ando aparece um ninho crasha. Mas crasha de voltar pro launcher e aparece código -1 ou 0 mas vou tirar capturas de tela e eu tentei a versão 2.1 ai foi ok mas crashou com a portal gun. Mas creio que é por conta do peso. Meu pc aguenta o modpack. Aloquei 10gb ram. Muito obrigado pela atenção vou enviar capturas de tela

**Comment by ArtpokeBr** [comment]
Ok, preciso principalmente do Crash Report mesmo, aliás, 10gb não é recomendável, aloque no máximo 8gb. isso pode ser um dos motivos também.
