### ISSUE TITLE
Bugs armaduras 

### ISSUE THREAD

**Issue by Killermaffia007** [ArtpokeBr/Minecraft-Ultimato#43]
Bug nas armaduras junto com o mod de movimentos

**Comment by noeneto** [comment]
As armaduras do botania nem aparecem praticamente quando equipadas nos personagens. Talvez por conta dos modelos, não sei.

**Comment by ArtpokeBr** [comment]
Isso é por conta do Emoticons, e como não posso tirar ele....

**Comment by Killermaffia007** [comment]
Como desativa ele tem como ?

Em 1 de dez. de 2020, à(s) 12:25 PM, ArtpokeBr <notifications@github.com> escreveu:

﻿

Isso é por conta do Emoticons, e como não posso tirar ele....

**Comment by ArtpokeBr** [comment]
se pode por conta própia remover o Mod da sua versão do Modpack, ele só afeta a estética mesmo.
