### ISSUE TITLE
Mods adicionais 

### ISSUE THREAD

**Issue by ReaperHimura** [ArtpokeBr/Minecraft-Ultimato#430]
**Nota**: Se você deseja suporte ao montar um servidor, que fique claro que eu, ArtpokeBr não sou o mais experiente com esses tipos de problemas!

**Versão do Modpack:**
a ultima versão 

**Descrição:**
Sempre quis explorar o mod das betwenlands, porem quando o adiciono, o jogo nçao fuiciona, e é só com ele, pois com outros eu add e tudo roda sem problemas

**Sugestão de Solução:**
Substitua este texto por uma possível solução que você acha que possa ser feita para o seu problema! isto ajuda pois muitas vezes sua sugestão pode ser boa e pode ser implementada e resolvida rápidamente! 

**Passo a Passo para chegar no Problema (Opcional):**
Eu apenas coloco o mod na pasta com oum mod normal

**Crash Log:**
Coloque aqui o Arquivo de Crash report mais recente se seu jogo crashou! ou se ele não crashou, mande o Log mais recente! os Crashes podem ser encontrados numa pasta chamada "Crash Reports" dentro do diretório do Modpack, e os Logs da mesma forma só que numa pasta chamada "Logs" e em específico sobre os logs, quando for me mandar, mande o que está com o nome "latest".

**Screenshots:**
Se for possível, mande uma print do problema! isso ajuda MUITO em casos de receitas com conflito, problemas com EMC e etc.

**Comment by ArtpokeBr** [comment]
Complicado... eu removi a BetweenLands justamente por problemas de Performance...

Porém, respondendo seu Issue em si, gostaria de lembrar que se você está adicionando um Mod ao Pack meio que não é responsabilidade minha garantir que vá funcionar né kkkkk no caso, impossível eu garantir a funcionalidade com qualquer Mod da Curse Forge, então nesse tipo de situação, você está sob sua conta e risco.
