### ISSUE TITLE
Não consigui colocar o modpack no enxada host

### ISSUE THREAD

**Issue by borutogamer** [ArtpokeBr/Minecraft-Ultimato#431]
Toda vez que coloco o  modpack na pasta mods do enxada host não consigo iniciar, vi tutoriais e aparece que precisa de sever files do modpack, mas quando vou no curseforge e tento achar esse '' sever files'' eu não acho de jeito nenhum

**Comment by ArtpokeBr** [comment]
Recomendo que peça ajuda mais detalhada lá no Nosso Server do Discord.

Mas de forma bem simples seria:

1. Certifique-se de Instalar a mesma versão do Forge do Modpack no Servidor
2. Certifique-se mover a pasta Mods do Client pro Servidor, assim como as Configs e Scripts também.

**Comment by ArtpokeBr** [comment]
Ou, outra forma seria utilizar as Server Files de outro Modpack na 1.12 que utilize a mesma versão do Forge... no final só trocando essas 3 pastas necessárias e tal.
