### ISSUE TITLE
Não consigo dar KeepInventory

### ISSUE THREAD

**Issue by amirbarreto** [ArtpokeBr/Minecraft-Ultimato#432]
Ao criar um mundo geralmete aparece a opção de escolher as regras do mundo, porém nesse modpack não aparece, o que fazer?

**Comment by ArtpokeBr** [comment]
Então... ai isso já confusão sua kkkkkkk

O Botão de selecionar Game Rules antes de entrar é algo das versões 1.14+ isso é algo vanilla =)
Então meio que não tem essa opção desse jeito.
Se quiser uma forma fácil, ao abrir o inventário, clicando no símbolo de engrenagem no canto superior esquerdo, é possível acessar as configs do mapa e lá você pode mexer nas gamerules ;)

**Comment by ArtpokeBr** [comment]
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/44851727/5e5057ad-ff72-4ca9-88f5-00b17d257cdc)
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/44851727/5603f9ee-8bd4-4842-8b7f-f8feef6d8c56)
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/44851727/d3725b2b-9ab8-4cb6-8c62-a6be37d5c672)

**Comment by amirbarreto** [comment]
Muito obrigado, eu estou acostumado a jogar versões mais recentes e não me lembrava que na 1.12.2 ainda não tinha isso kkkkk.
Só mais uma perguntinha, ainda é possível baixar a versão do modpack que foi utilizada na série? Queria jogar com uns  amigos porém não temos muito tempo, então ter o projectE sem crafting extendido e coisas do tipo seria melhor pra conseguir evoluir sem ocupar muito tempo. Se não tiver como tá suave tbm, excelente modpack.

**Comment by ArtpokeBr** [comment]
Infelizmente, pra n haver confusões e ser mais tranquilo de manter, eu arquivei as versões mais antigas =)

então é... só nos updates mais recentes que dá pra jogar mesmo kkkk
