### ISSUE TITLE
Meu mine nao esta abrindo, ele crasha na finishing up 6/7

### ISSUE THREAD

**Issue by Caiocraft0602** [ArtpokeBr/Minecraft-Ultimato#433]
**Nota**

**Versão do Modpack:**
Versão 2.4 

**Descrição:**
eu estava jogando no modpack normalmente, eu sai do mundo e fechei o minecraft, logo depois fui entrar dnv no jogo, porem carregava os mods e travava na finishing up 6/7 e logo fechava com o codigo de saida-1

**Sugestão de Solução:**
ja aconteceu comigo, porem foi vannila, eu simplesmente atualizei o java(esta pendende) e reinstalei a versao, ai consegui entrar

**Passo a Passo para chegar no Problema (Opcional):**
eu nao sei oque pode ter acontecido, pq quando eu fui fechar o jogo eu sai do mundo e dei um altF4 no menu, e quando fui entrar, o jogo começou a fechar na finishing up

**Crash Log:**
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/138892408/6818d260-5a24-45c5-8537-bf669fad0cc7)

**Screenshots:**
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/138892408/a0d164ef-ece8-4f35-a6cb-d0f165c7d6d2)
logo depois dessa tela o jogo fecha

**Comment by ArtpokeBr** [comment]
Opa então, preciso que você realmente me mande um Crash Log kkkk

Se tiver dúvidas está localizado na pasta do Modpack.

**Comment by Caiocraft0602** [comment]
os craft nao estão o mesmo '-' estao mais faceis. como eu arrumo??

**Comment by Caiocraft0602** [comment]
vou mandar o crash
[crash-2023-07-07_11.50.20-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/11985186/crash-2023-07-07_11.50.20-client.txt)

**Comment by Caiocraft0602** [comment]
Não tô querendo apresar mas apresando… como é que tá indo aí? Kkk sou meio ansioso, se tiver alguma coisa q eu possa fazer me fala!!

**Comment by Caiocraft0602** [comment]
EU SOU INEVITAVEL
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/138892408/d26401cb-48b1-4518-80d7-0ceeabe6525d)
Obs: consegui, eu li o crash e troquei o had enough items pq estava dando problema, coloquei o Just enough item

**Comment by ArtpokeBr** [comment]
Bom, o problema foi de fato uma integração do IC2 com o HEI. você poderia ter tentado atualizar ele, mas se já solucionou kkk

Lembrando que o HEI é uma melhor escolha por questões de performance, mas no final o que importa é funcionar no seu jogo.

Apenas lembre-se também, eu não consigo dar suporte total para versões muito alteradas do Modpack, então peço para que não saia mexendo demais nas coisas kkkkk.

**Comment by ArtpokeBr** [comment]
Só me confirma então, seu problema foi solucionado? pra que eu possa estar fechando e tal kkkk

Ah e outra coisa, lembre-se que o Modpack possui um chat lá no meu Discord. é bom pra tirar dúvidas e conversar com o pessoal sobre o Modpack.

**Comment by Caiocraft0602** [comment]
blz, valeu ai kkk, eu so troquei o mod HEI para o JEI, e n fiz mais nada. Vou entrar la do dc, Valeu ai!! 
Pode fechar ai dBoa
