### ISSUE TITLE
Craft Issues

### ISSUE THREAD

**Issue by Maindanikraft** [ArtpokeBr/Minecraft-Ultimato#437]
The modpack crafts when I download them directly from Curseforge are completely confusing. For example, the transmutation table from the "projecte" mod is asking for absurd crafting with the avaritia crafting table using completely non-standard items such as the philosopher's stone, neutron plates, and diamond and emerald dust, as well as various other materials that are difficult to obtain even with the project. And this isn't just at the transmutation table, it also happens with Avaritia, extra planets, mekanism, and MANY other mods that shouldn't have this absurd amount of items to manufacture. I also tried downloading using other launcher and mod pack base sources such as multi mc and technich.

**Comment by Maindanikraft** [comment]
Minecraft version:1.12.2
Modpack version:2.4
Java version: Java 8 Update 381
operational system: Windows 10
IMPORTANT: when I played this before, the problem was draconic evolution, but I didn't want to play without draconic evolution. Try to download another version of draconic evolution.

**Comment by Maindanikraft** [comment]
![Uploading image_2023-10-14_160541465.png…]()

**Comment by Maindanikraft** [comment]
![image](https://github.com/ArtpokeBr/Minecraft-Ultimato/assets/144092326/79defb54-3b16-4dc8-9c66-9ff3cf47fe23)

**Comment by ArtpokeBr** [comment]
This is Intended, this is the balancing of the Modpack =)

**Comment by Maindanikraft** [comment]
Update: when I removed draconic evolution, the crafts started working again, so the problem is actually draconic evolution.

**Comment by Maindanikraft** [comment]
> This is Intended, this is the balancing of the Modpack =)
> 
> * You're not supposed to get access to ProjectE and more advanced Items without playing at least for a bit.

Are you serious?!
this makes no sense, the crafts they are asking for are completely ridiculous, "play at least for a bit", makes no sense!
A normal person would probably take hours and hours of game to have access to projecte.

**Comment by ArtpokeBr** [comment]
"A normal person would probably take hours and hours of game to have access to projecte."
But thats exactly the point! ProjectE is a mod that makes you skip a bunch of Gameplay aspects, it is an OP Mod, I want players to enjoy the pack, not rush for an OP Mod and finish the pack in 2 days.

**Comment by Maindanikraft** [comment]
> "A normal person would probably take hours and hours of game to have access to projecte." But thats exactly the point! ProjectE is a mod that makes you skip a bunch of Gameplay aspects, it is an OP Mod, I want players to enjoy the pack, not rush for an OP Mod and finish the pack in 2 days.
> 
> It is a bit weird that you're impressed by this, nowadays even Kitchen Sink packs don't allow ProjectE to be acessible early...
> 
> Honestly it sounds that you don't want to spend time actually playing the Modpack haha

well, you have a point, but don't you think avaritia things and draconic evolution craft are too much?  know Projecte is OP but does it need to be that much? And in my last world, I spent more than 100 hours on the game, so idk exactly what you mean by "It sounds like you don't want to spend time actually playing the Modpack", because even with projecte and other people normally spend a lot of hours playing your modpack. If you still want the crafts to be harder than normal it's okay, but don't exaggerate, make the crafts a little simpler at least.

**Comment by Maindanikraft** [comment]
The problem is not the difficulty of the game, but what you want to do inside the game. But if something is EXAGGERATEDLY HARD, instead of becoming adventurous and fun to play, it will start being boring and kind of take your motivation to play out.

**Comment by ArtpokeBr** [comment]
I think you're not getting the point here, the idea is for you to develop your base without considering ProjectE in the first place.

Build, Explore and most importantly automate your journey, then you'll not even bother with the recipes related to it, as it is truly inteded to be a late game mod, you are supposed to only touch it when you're already progressed through other mods.

Many Mods have neat features that are overshadowed by other OP Mods, be creative with the tools that you're given.
