### ISSUE TITLE
iron gear bug

### ISSUE THREAD

**Issue by gloomyangel** [ArtpokeBr/Minecraft-Ultimato#44]
a receita do iron gear (thermal) esta dando conflito com o iron ring(aether)
![image](https://user-images.githubusercontent.com/75285287/100683164-88304180-3356-11eb-8fc0-787bf66e2090.png)
![image](https://user-images.githubusercontent.com/75285287/100683175-8d8d8c00-3356-11eb-84f9-2d4e6ebc9200.png)

**Comment by ArtpokeBr** [comment]
Ok, será corrigido assim que for possível!
