### ISSUE TITLE
como habilito o relogio do tempo do project e e se possivel como desabilitar a auto regeneraçao de arquivos

### ISSUE THREAD

**Issue by LUCY-NOVACRONO** [ArtpokeBr/Minecraft-Ultimato#441]
**Versão do Modpack:**
mc ultimato 1.12.2

**Descrição:**
voce desabilitou o relogio do tempo do project e XD ,  ao modificar os arquivos do modpack ele se regeneram ao entrar no jogo , so consigo editar se eu pegar apenas os mods do modpack em uma profile criada por mim , mas nessa altura nao posso fazer isso ja que nao consigo entrar no meu mundo apos trocar . peço por favor por uma possivel soluçao.

obs : sei que o relogio causa lag e é op kk , mas tambem quero dar uma mechida a mais nos arquivos , eu consigo editar alguns em algumas config , mas ao tentar modificar o relogio por ex os arquivos se regeneram :(

**Comment by ArtpokeBr** [comment]
Olha, se quiser auxilio com Modpack Dev tem gente lá no Discord do canal que pode ajudar com algumas coisinhas, mas no geral, aqui é um campo para problemas relacionados ao Modpack, ao modificar a instância, não posso mais dar suporte por aqui =/
