### ISSUE TITLE
Erro ao tentar mostrar o crafting do Ultimate Ingot no JEI

### ISSUE THREAD

**Issue by Huelber588** [ArtpokeBr/Minecraft-Ultimato#442]
Erro ao tentar exibir a receita do Ultimate Ingot no JEI: Ao tentar visualizar o crafting do Ultimate Ingot, o JEI (Just Enough Items) não consegue carregar a receita corretamente, resultando em uma falha de exibição.

**Comment by Huelber588** [comment]
sim

**Comment by Huelber588** [comment]
![Captura de tela 2024-09-11 105805](https://github.com/user-attachments/assets/a588b5d5-43e2-4b02-a09e-8c4da77fe6ca)
![Captura de tela 2024-09-11 105805](https://github.com/user-attachments/assets/6d0452c0-29e2-4908-bb8d-8fc7b12c701f)

**Comment by Huelber588** [comment]
![imagem_2024-09-11_110113031](https://github.com/user-attachments/assets/32dd6ace-27cc-423f-8cc9-c2a99551cef6)
Tambem aparece isso mas nao sei se tem haver

**Comment by ArtpokeBr** [comment]
Você modificou alguma coisa no Modpack? Aonde baixou inclusive?

**Comment by ArtpokeBr** [comment]
Então, a versão lite não é feita por mim, então esse probleminha deve ser reportado ao autor da versão lite ;)

Mas tranquilo, vou fechar aqui, sem problemas =)
