### ISSUE TITLE
Crashando antes de entrar

### ISSUE THREAD

**Issue by TutuiCardoso2007** [ArtpokeBr/Minecraft-Ultimato#47]
![image](https://user-images.githubusercontent.com/75325329/100764491-26fb8300-33d5-11eb-9f53-726c34d363fe.png)

**Comment by ArtpokeBr** [comment]
Manda Crash ou Log nesses casos, mas olhando só pra isso, confere se tu alocou a RAM necessária pro Modpack rodar.
