### ISSUE TITLE
Erro ao abrir a instancia no MultiMC 5

### ISSUE THREAD

**Issue by excelencianoob** [ArtpokeBr/Minecraft-Ultimato#49]
Ola,

Ao tentar iniciar o modpack ocorre o seguinte erro em anexo:
[erro.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5623848/erro.txt)

Isso pode ser problema com o meu java ou pode estar faltando a configuração no multimc?

**Comment by ArtpokeBr** [comment]
n consegui identificar certinho oq ocorreu, tu alocou quanto de RAM pro Modpack?

**Comment by excelencianoob** [comment]
A alocação de memoria mínima esta com 1024 MB
A alocação de memoria máxima  esta com 8024 MB
e o PermGen esta com 128 MB

**Comment by excelencianoob** [comment]
A versão do Java que estou usando é o 8 update 271

**Comment by excelencianoob** [comment]
Problema encontrado, eu estava com jdk para desenvolvimento em java instalado junto com o java 8. 

Agora esta funcionando certinho.

Obrigado pela ajuda e atenção!

**Comment by ArtpokeBr** [comment]
ó, mas fica atento ai que se eu n me engane, é a memória mínima do MultiMC que precisa estar mais altinha viu kkk mas de qualquer forma, obrigado por ter reportado e aproveite o Pack :).

**Comment by Paulo2021a** [comment]
Ola,  


Estou com um problema do MultMC quando inicio ele da fica carregando o modpack depois quando fica na metade do processo de iniciar o Minecraft simplesmente fecha

**Comment by Paulo2021a** [comment]
Não consegui achar o crash no meu pc

**Comment by Paulo2021a** [comment]
E mais uma coisa quando fecha o MultMC diz o processo foi encerrado com o codigo -1

**Comment by Paulo2021a** [comment]
[crash-2022-03-11_15.29.06-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/8234558/crash-2022-03-11_15.29.06-client.txt)
[crash-2022-03-11_15.29.57-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/8234559/crash-2022-03-11_15.29.57-client.txt)
[crash-2022-03-11_15.32.49-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/8234560/crash-2022-03-11_15.32.49-client.txt)
[crash-2022-03-11_15.33.12-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/8234561/crash-2022-03-11_15.33.12-client.txt)
[crash-2022-03-11_15.39.09-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/8234562/crash-2022-03-11_15.39.09-client.txt)

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/157942702-03d5b62a-aadf-4aa1-9b71-41296ff0dba0.png)
Você alterou o Modpack?

**Comment by Paulo2021a** [comment]
Sim pq

**Comment by Paulo2021a** [comment]
Ficava Muito pesado para meu pc

**Comment by ArtpokeBr** [comment]
Então.... eu não quero soar Rude mas se você modificou o Modpack, este não é mais o Ultimato! o que eu posso te recomendar é talvez pedir ajuda lá no meu Discord.

Mas lembre-se, ao modificar um Modpack, assim como qualquer jogo até, a responsabilidade é totalmente sua.

já que todo o Ultimato foi feito, ajeitado e organizado de um jeito específico, então alterar isso e ter problemas, é algo que diretamente fica complicado para eu prestar suporte :)

por isso até que recomendo pedir ajuda no chat de dúvidas lá no meu discord, alguém deve conseguir te ajudar rapidinho.

**Comment by ArtpokeBr** [comment]
https://discord.com/invite/FprwvNQ no caso, aqui o Link para facilitar :)
