### ISSUE TITLE
Bug Carry on com IC2

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#5]
Bug com o mod emoticons 
Bug com o Carry on e tudo do ic2...

https://youtu.be/BvIPgf94uAA

Sugestão tirar o modpack kk

**Comment by ArtpokeBr** [comment]
Obrigado por ter um vídeo incluso kkk, vou provavelmente analisar a possibilidade de tira-lo ou remover tudo do IC2 dele, se acabar descobrindo outras Tile Entities de outros mods que possam ter conflitos, reporte também!

**Comment by Christtiann** [comment]
As tem o bug visual tbm com o emotions que eu acho q ficaria ruim na serie... imagina eles estao fazendo o video e vao pegar o negocio e nao aparece kkkk
