### ISSUE TITLE
Erro ao tentar entrar

### ISSUE THREAD

**Issue by BartolomeuFC** [ArtpokeBr/Minecraft-Ultimato#51]
Quando tento entrar dentro da instancia ela inicializa e no meio da inicialização ele diz que aconteceu um erro com um (mod já foram vários), e tenho que reabrir o minecraft. Obrigado pela atenção e por favor tente resolver

**Comment by ArtpokeBr** [comment]
tenta entrar na instância? você diz, abrir o Jogo? Prints ajudariam... por onde baixou o Modpack?

**Comment by BartolomeuFC** [comment]
Desculpe, não sei me espressar direito. E eu baixei pelo curse forge como você falou no video. Eu ultilizo o laucher do MultiMC.

**Comment by BartolomeuFC** [comment]
![carregando](https://user-images.githubusercontent.com/75327514/100781309-9d09e500-33e9-11eb-9a01-d72e7919f720.png)

**Comment by BartolomeuFC** [comment]
![erro](https://user-images.githubusercontent.com/75327514/100781397-bad74a00-33e9-11eb-802f-7eb9a072ef8e.png)

**Comment by BartolomeuFC** [comment]
Depois acontece isso

**Comment by ArtpokeBr** [comment]
o Erro está na primeira print. você só esta com 1GB Alocado pro Modpack, tenta alocar mais. no mínimo 4GB pro modpack rodar, se puder alocar mais, recomendo 6GB.

**Comment by ArtpokeBr** [comment]
já resolveu? como é algo que aconteceu só por causa de não ter alocado a memória suficiente, vou fechar :) qualquer problema me avise dnv.
