### ISSUE TITLE
Erro na hora de instalação

### ISSUE THREAD

**Issue by LuccKK** [ArtpokeBr/Minecraft-Ultimato#52]
quando eu começo a instalar esta falando "This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 300890" eu estou instalando diretamente pelo link oficial ( https://www.curseforge.com/minecraft/modpacks/minecraft-ultimato ) e pelo aplicativo para windows CurseForge e Overwolf

![Captura de tela 2020-12-01 142743](https://user-images.githubusercontent.com/75329478/100775038-7e075500-33e1-11eb-9b36-e3f0488086b2.png)

**Comment by ArtpokeBr** [comment]
hmmm, estranho isso, tá dito real qual o problema, vou precisar analisar pra ver oq exatamente está faltando ou q bugou na curse.. mas tenha em mente que literalmente até ontem a Curse estava em período de manutenção!

**Comment by ArtpokeBr** [comment]
Como a Curse está estabilizando ainda, aguarde um pouco. depois de uns dias caso ainda esteja acontecendo mesmo eu tendo lançado um update novo por exemplo, me reporte :)
