### ISSUE TITLE
preciso saber se e do meu computador

### ISSUE THREAD

**Issue by amigodetodos** [ArtpokeBr/Minecraft-Ultimato#54]
tenho uma CPU boa 16G de ram mas nao consigo jogar o mod pack 

print
![Captura de Tela (17)](https://user-images.githubusercontent.com/75332723/100783390-79946980-33ec-11eb-9d83-7b53776f614b.png)

**Comment by ArtpokeBr** [comment]
Alocou corretamente a RAM pro Modpack?

**Comment by amigodetodos** [comment]
Como faço para acolar a memoria ram certinho

Em ter, 1 de dez de 2020 3:50 PM, ArtpokeBr <notifications@github.com>
escreveu:

**Comment by ArtpokeBr** [comment]
tá na curse ou no MultiMC? ambos é só ir nas opções da Instância msm.

**Comment by amigodetodos** [comment]
![Captura de Tela (19)](https://user-images.githubusercontent.com/75332723/100786492-02150900-33f1-11eb-8ff5-e906ec589fc1.png)
 aqui que acola ?

**Comment by ArtpokeBr** [comment]
Leia meu deus kkkk, desça até o final e lá vai ter a alocação padrão de memória para todos os Modpacks.

**Comment by amigodetodos** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK desculpe por ser burro

**Comment by ArtpokeBr** [comment]
Tudo certo? posso fechar o Issue? veja pra mim ai se funcionou tudo. recomendo alocar de 6 á 8GB já que teu pc tem 16. por favor NADA MAIS DO QUE 8.

**Comment by amigodetodos** [comment]
deu tudo certo sim, obrigado pela a atençao
