### ISSUE TITLE
FPS alto ,porém a tela da umas congeladas que duram por volta de 5 segundos, em um intervalo de 2 segundos

### ISSUE THREAD

**Issue by Migueell2** [ArtpokeBr/Minecraft-Ultimato#55]
O titulo é bem alto explicativo e especifico, né ? kkkk
bem, eu quero saber se tem maneiras de resolver este problema, eu já tentei deixar os gráficos do jogo no mínimo, abaixar a render distance, instalar optifine, tirar animações, tirar sombras , e nada funcionou!!! (e meu PC tem tudo dos requisitos para rodar o Ultimato/ • Pelo menos 4GB - 6GB de RAM alocada ao Modpack.
• E uma CPU decente.) 
Tem algo que possa me ajudar tirar essas travadas?

**Comment by Migueell2** [comment]
Meu PC: (Processador: Intel Core i5-8400 CPU 2.80GHz 2.81GHz)
              (Memoria RAM: 16GB                                                     )

**Comment by ArtpokeBr** [comment]
LagSpikes?  estranho, se tu alocou certinho a quantidade de RAM n era pra ter muito isso...

**Comment by gupoiatti** [comment]
Nao seria uso de disco ? da uma boa olhada por que as vezes o sistema atualiza e instala atualizações sozinho, fazendo aumentar o uso de disco.

**Comment by Poseidon1220** [comment]
A mim tambem faz a mesma coisa eu acho que pode ser do uso da ram porque ao iniciar aquilo nunca passa do carregamento de ate 6mil/3mill depende de uso da ram e as specs do meu pc sao estas
processador amd ryzan7 2600x
placa de video(nao sei se faz diferenca mas vou meter) nvidia rtx2060 6gb
ram 16gb
![image](https://user-images.githubusercontent.com/75655570/101438661-ca372580-390a-11eb-9cac-9c62cd0dc68e.png)

**Comment by Poseidon1220** [comment]
Consegui resolver(no curse) e so ir nas configuracoes do minecraft
![image](https://user-images.githubusercontent.com/75655570/101439501-86ddb680-390c-11eb-80dd-54c832c075b7.png)
e depois meter este codigo no incio "-Xmx16384M -Xms16384M"
![image](https://user-images.githubusercontent.com/75655570/101439572-ad9bed00-390c-11eb-8817-095cc05d27d0.png)

**Comment by Poseidon1220** [comment]
denada @ArtpokeBr

**Comment by ArtpokeBr** [comment]
Isso ai pelo que parece vai alocar 16gb de ram no Modpack kkkkk mas ok, vai na fé.

**Comment by Poseidon1220** [comment]
pode meter menos mas tive de fazer assim me desculpa

**Comment by Migueell2** [comment]
vlw galera, ja resolvi o problema!!! :DDD

**Comment by ArtpokeBr** [comment]
Bom, vou fechar então :)
