### ISSUE TITLE
Textos não cabem na tela

### ISSUE THREAD

**Issue by DanielPitico** [ArtpokeBr/Minecraft-Ultimato#57]
Acabei de instalar o modpack pelo launcher do CurseForge, ao abrir o jogo fui alterar os comandos do teclado porque normalmente dão muitos conflitos por causa dos mods, então me deparei com a seguinte situação:

![image](https://user-images.githubusercontent.com/30831387/100814114-c0e81d80-341f-11eb-894e-34114da655b9.png)

Não consigo ler o que o comando faz, assim fica difícil decidir qual botão devo setar, meu jogo está rodando no modo janela com a resolução 1440x900, tentei colocar em tela cheia e reduzir a janela mas deu na mesma.

**Comment by ArtpokeBr** [comment]
Olha, problema esquisito esse, tem algo haver sua janela.. minha sugestão é diminuir o tamanho a GUI pra trocar as configs e depois quando tiver terminado, voltar  ao Normal.

**Comment by ArtpokeBr** [comment]
n é algo que preciso trabalhar pois tbm n tem como eu mexer específicamente na GUI dos controles, ent faça a gambiarra de trocar a scale pra mexer ai e dps volte ao normal. vou fechar.
