### ISSUE TITLE
Impossivel instalar no curseforge Mac

### ISSUE THREAD

**Issue by js240627** [ArtpokeBr/Minecraft-Ultimato#59]
Por alguma razao, ao instalar, trava ao 33% e nunca instala.

**Comment by ArtpokeBr** [comment]
Ih rapaiz, se tá no Mac? isso provavelmente é problema com a Curse mesmo.. n sei se consigo fazer algo kk

**Comment by js240627** [comment]
Só reparei agora que NENHUM mod pack funciona na curse forge. My bad ai, nao é uma issue do modpack e sim da propria curse. Mas fique atento porque acho ter tido o mesmo problema que o LuccKK. Força ai!

**Comment by js240627** [comment]
Nem no MultiMc esta funcionando.

<img width="1680" alt="Screen Shot 2020-12-02 at 1 32 02 PM" src="https://user-images.githubusercontent.com/46506335/100872956-e5390e00-34a2-11eb-8e59-7475cd00228f.png">

**Comment by ArtpokeBr** [comment]
Putz, vou fechar então, já que é coisa da Curse, o jeito é esperar :T
