### ISSUE TITLE
não to achando o ovo de villager pesquiso e não aparece nada

### ISSUE THREAD

**Issue by joel36236264264** [ArtpokeBr/Minecraft-Ultimato#62]

**Comment by ArtpokeBr** [comment]
os Spawns de Villager não tão aparencendo n? ativa o Modo de esconder do JEI e desesconde eles kk só isso, erro meu provavelmente.

**Comment by joel36236264264** [comment]
como ativa o modo esconder?

**Comment by ArtpokeBr** [comment]
no único botão que o JEI adiciona, vai abrir as Configs dele vai ter o Hide Mode.

**Comment by joel36236264264** [comment]
obrigado ajudou muito, e nossa quando eu ativei saiu de 419 paginas e foi pra 600
