### ISSUE TITLE
Crash ao Abrir com o IC2

### ISSUE THREAD

**Issue by Progamadormirim** [ArtpokeBr/Minecraft-Ultimato#63]
Congela quando vai inicializar o IC2

![Failed Minecraft IC2](https://user-images.githubusercontent.com/33735157/100895173-064a3080-349c-11eb-8084-61a929776c73.jpg)

Já tentei instalar várias subversões do IC2 1.12.2

**Comment by ArtpokeBr** [comment]
Primeiro de tudo, não tente mexer nas versões de Mods instalados sem informar o Erro. isso dificulta a correção. reinstala o Modpack pra volta tudo ao Padrão e me manda esse Crash pra eu ver a solução.

**Comment by ArtpokeBr** [comment]
Tá, Acabei de solucionar outro problema com uma pessoa e foi parecido, ALOCOU a quantidade correta de RAM? isso é provavelmente ocasionado por isso.

**Comment by Progamadormirim** [comment]
Sim eu acabei fazendo muita coisa errada quando tentei resolver o problema e deu ainda mais problema, e também não tinha alocado a quantidade correta de RAM(Não sabia mexer no MultiMC). Reinstalei o mod e deu certo.

**Comment by ArtpokeBr** [comment]
Tudo resolvido então? vou fechar :)
