### ISSUE TITLE
ovelhas

### ISSUE THREAD

**Issue by gamerYToff** [ArtpokeBr/Minecraft-Ultimato#65]
eu não sei se isso é um bug do modpack ou se é assim mesmo mas de qualquer maneira as ovelhas pararam de spawnar eu andei 7 mil blocos e não vir uma ovelha é uma coisa boba mas que incomoda principalmente ja que o modpack tem muitos mods e vc começa perdido a primeira coisa que vc pensar em fazer é uma cama mas não tem ovelha

**Comment by ArtpokeBr** [comment]
As Ovelhas estão atualmente com spawn reduzido por conta do Zawa dominar a geração de Mobs, no próximo patch o Zawa terá seus Mobs desativados, consecutivamente melhorando isso então, já foi corrigido!

**Comment by gamerYToff** [comment]
se desliga o spawn do zawa as ovelhas voltam a spawnar?

**Comment by ArtpokeBr** [comment]
Yup, 
[ZAWASpawnConfigurations.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5643733/ZAWASpawnConfigurations.zip) essa config aqui vai desativar o Spawn do Zawa, pode ser que dê uns bugzinhos em um mapa gerado, em um patch futuro isso vai ser implementado por padrão com uma forma de conseguir os animais e etc, mas no momento, testa só desativar eles aqui que já deve resolver!
