### ISSUE TITLE
Não consigo abrir o jogo 

### ISSUE THREAD

**Issue by acqbmn** [ArtpokeBr/Minecraft-Ultimato#69]
![image](https://user-images.githubusercontent.com/75390627/100919443-90a08d80-34b8-11eb-8f52-9527ee8ae72e.png)
ele fica nessa tela e as vezes para de responder.

**Comment by ArtpokeBr** [comment]
tu tá com menos de 4GB Alocado, aloca mais se seu PC permitir.

**Comment by acqbmn** [comment]
Como que aloca mais RAM?

**Comment by ArtpokeBr** [comment]
Se estiver na curse, abra as configurações da própia curse mesmo, e procure pela relacionada ao Mínimo de memória dos Modpacks e lá vc pode definir um padrão pra todo Modpack, sem ter que mexer manualmente, se seu PC tiver 8GB recomendo alocar no máximo 6GB.
