### ISSUE TITLE
Muitos mobs do Techguns

### ISSUE THREAD

**Issue by leofoda** [ArtpokeBr/Minecraft-Ultimato#7]
Indo direto ao ponto, os mobs do techguns são muito chatos. Pra cada 5 mobs agressivos gerados, 3 são zumbis com armas. Eu costumo jogar sem keepinventory, mas sinceramente eu coloco até de dia pq esse bichos dão muito dano mesmo com armadura e escudo, alem de dar um knockback muito alto. Até voce ter um boa armadura, voce vai morrer varias vezes por noite.
Bom, de outras reclamações nao tenho nenhuma, enfim o modpack está muito bem feito e bem optimizado, parabens pelo trabalho.

**Comment by ArtpokeBr** [comment]
Ok, vou anotar como melhoria, eu já tinha a idéia de talvez mexer nisso pois não consigo restringir as dimensões em que eles spawnam, mas o Spawnrate acho que posso mexer sim, por favor só me confirme se no nether os Pigmans/Demônios estão de boas!

**Comment by leofoda** [comment]
> Ok, vou anotar como melhoria, eu já tinha a idéia de talvez mexer nisso pois não consigo restringir as dimensões em que eles spawnam, mas o Spawnrate acho que posso mexer sim, por favor só me confirme se no nether os Pigmans/Demônios estão de boas!

nether ta de boa pra mim
