### ISSUE TITLE
nao consigo baixar esta dando erro

### ISSUE THREAD

**Issue by Eduzinhoo0** [ArtpokeBr/Minecraft-Ultimato#70]
https://prnt.sc/vujqc9

**Comment by ArtpokeBr** [comment]
Isto infelizmente é um erro da CurseForge pelo visto... então não há muito que eu possa fazer =T vou fechar. mas minha dica é tentar esperar um pouco, a curse acabou de migrar ent durante essa semana ela deve se estabilizar melhor.
