### ISSUE TITLE
Meu erro 

### ISSUE THREAD

**Issue by Phoenix-bravo** [ArtpokeBr/Minecraft-Ultimato#73]
Aparece um erro assim quando tento iniciar 

Erro 
O jogo parou de funcionar
Ocorreu um problema inesperado e o jogo parou de funcionar. Lamentamos
Código de saída: 0

**Comment by ArtpokeBr** [comment]
Primeiro, certifique-se de que alocou a quantidade correta de RAM para o Modpack rodar. segundo, quando for reportar problemas, por favor dê um título mais explicativo e relacionado ao Erro.

**Comment by Phoenix-bravo** [comment]
Como que eu faço isso?

**Comment by Phoenix-bravo** [comment]
Aaa já sei o que está acontecendo o meu cpu não aguenta

**Comment by ArtpokeBr** [comment]
bom, se n aguenta, vou fechar ent pra n ter confusão :)
