### ISSUE TITLE
não consigo criar o mundo ou entrar em nenhum server do modpack

### ISSUE THREAD

**Issue by thorcervejeiro** [ArtpokeBr/Minecraft-Ultimato#74]
[crash-2020-12-02_17.22.54-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5632108/crash-2020-12-02_17.22.54-client.txt)

o crash report é esse, o que devo fazer?

**Comment by ArtpokeBr** [comment]
Quanto de RAM tu alocou pro Modpack? e quanto tem no Seu PC? parece que tu alocou demais... ou de menos!

**Comment by thorcervejeiro** [comment]
meu pc tem 12, eu coloquei 4

**Comment by thorcervejeiro** [comment]
![image](https://user-images.githubusercontent.com/75395377/100934208-3100ad00-34cd-11eb-8395-34fa109ea6e5.png)
e quando abro o jogo aparece isso

**Comment by ArtpokeBr** [comment]
se seu PC tem 12, tenta alocar 6GB. e depois me avisa.

**Comment by thorcervejeiro** [comment]
Tentei, dessa vez o jogo crashou antes de abrir o mapa

**Comment by ArtpokeBr** [comment]
então já nem sei, talvez seu processador seja velho ou só a instalação do Modpack que deve ter ficado incorreta. tenta reinstalar =/
