### ISSUE TITLE
Crash Astral Sorcery

### ISSUE THREAD

**Issue by MarlonBEP** [ArtpokeBr/Minecraft-Ultimato#75]
[crash-2020-12-02_22.29.27-client.txt](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5632898/crash-2020-12-02_22.29.27-client.txt)

**Comment by ArtpokeBr** [comment]
Aparentemente erro do Astral registrando as coisas dele mesmo, tente reinstalar o Modpack, talvez resolva.
