### ISSUE TITLE
Mundo dos Dragões nao gera mais chunks

### ISSUE THREAD

**Issue by LeoCatarro** [ArtpokeBr/Minecraft-Ultimato#76]
CoFH World loaded a new chunk [-29, 72] in dimension 43 (simplevoidworld) while populating chunk [-28, 72], causing cascading worldgen lag.

Nota: Penso que tenha ver com essa linha da consola do servidor

**Comment by ArtpokeBr** [comment]
Isso é normal. é só uma linha n console se referindo que o COFH World está colocando os minérios na dimensão. qual o problema então?

**Comment by LeoCatarro** [comment]
Tem razão, após umas pesquisas eu percebi isso xD

O que acontece é o seguinte. Eu criei um mundo no singleplayer, porque nao o consegui criar em server para ele ser através do Topography mod. 
Ficou tudo bem, o mundo a correr na boa, porém quando entro na dimensão dos dragões apenas me gera um mundo void
Para resolver tive que tirar o mod e basicamente adicionar os Dragoes e tudo mais no overworld e passar a ter uma mundo default gerado

Tentei pesquisar o que poderia estar a dar conflito, inclusive dei-me uma olhada na config do mundo e da dimensão criada(id:43), mas nao consegui em nada resolver o problema

**Comment by ArtpokeBr** [comment]
Não funciona por que mesmo usando o Mapa do Single, o Server PRECISA estar com as generator Settings corretas para poder carregar o Mundo. então isso não é um bug, e sim só confusão já que ainda n existem server files pro Modpack. em breve elas devem sair. vou fechar
