### ISSUE TITLE
FOV BUGADO PARA MIN

### ISSUE THREAD

**Issue by JoaoP016** [ArtpokeBr/Minecraft-Ultimato#77]
Eu uso o QUAKEPRO,POREM QUANDO COLOCO ARMOR PESADAS ELA DIMINIU OK, POREM QUANDO EU USO SPEEDS EM GERAL (ARMOR, POTION, PETS, ETC) O FOV PARECE DIMINUIR COMO SE TIVESSE COM EFEITO DE  SLOW, MAS NO CASO ESTOU COM SPEED.  PODERIA SER ESSE MOD DE MOVIMENTOS ?

**Comment by ArtpokeBr** [comment]
primeiro, sem caps, segundo, nesse tipo de situação por favor faça uma gravação mostrando pois fica infinitamente mais fácil de demonstrar... e esse seu problema não sei do que se trata e não acho que seja um problema tão relevante ao qual eu precise resolver ou possa resolver até kkk Vou fechar.
