### ISSUE TITLE
Blocos Param de Dropar 

### ISSUE THREAD

**Issue by SedexEntrega** [ArtpokeBr/Minecraft-Ultimato#78]
Iniciei um server para jogar com meus amigos, mas depois de 1 hora e pouco de gameplay, simplesmente os blocos param de dropar e mesmo reiniciando o mine o bug volta novamente, tentei reinstalar o modpack, porém o bug volta.

**Comment by ArtpokeBr** [comment]
não sei do que se trata esse problema, sinceramente kkkk, eu não mexi em nada relacionado á drops =/

**Comment by SedexEntrega** [comment]
@ArtpokeBr Será que isso pode ser algo relacionado à algum mod em específico?

**Comment by ArtpokeBr** [comment]
Pior que n faço idéia mesmo kkkk, não tem nenhum mod se bem me lembre que altera os fatores de Drop e afins

**Comment by FDALynch** [comment]
Acho que isso deve ter relação com o TPS do servidor, que deve estar bem alto, ai os blocos param de dropar

**Comment by SedexEntrega** [comment]
@FDALynch se tiver relação como eu resolveria?

**Comment by FDALynch** [comment]
@SedexEntrega TPS tem haver com o Hardwere do pc, se não é tão bom ele fica com o tps alto, para abaixar e só reiniciando o servidor pra resolver.
