### ISSUE TITLE
Jogo fica travado por muito tempo

### ISSUE THREAD

**Issue by zNinjaFrosTz** [ArtpokeBr/Minecraft-Ultimato#79]
Opa, tarde, o meu jogo alem de demorar muito pra abrir, mas muito mesmo papo de 12minutos, ele da umas travada que duram entorno de 3m a 10m, o modpack roda mt bem enquanto nao trava, roda a 120fps cravado, mas em 30-40 min de game, ele da essa travada que dura mt, tenho um i39100f 3.60-4.20Ghz e 7 de ram alocada, e 8gb de ram no pc

**Comment by ArtpokeBr** [comment]
Se você tem 8GB de ram no pc, nunca aloque tanto assim. só o Windows consome 2GB para existir, então abaixe pra 5 ou 6. além disso, seu processador pode ser antigo? não sou o melhor do mundo em Hardware, mas um I3 já é meio antigo.

**Comment by Aficalma** [comment]
Tenho o mesmo problema, são 5GB de Ram alocada e 8 do sistema. Um Rysen 5 3600, ou seja, não é falta de CPU, depois de tanto travar e crashar o mundo corrompeu, e o erro que apresentava era o topography, peguei meus itens e troquei para outro mundo com topography e o erro está se repetindo, vou mudar para um mundo com outro tipo de geração e ver se melhora. Faz backup aí que tem chance de dar ruim.

**Comment by ArtpokeBr** [comment]
Sem o Topography, você não terá acesso aos Dragões do IceAndFire, pelo menos a geração natural deles...

**Comment by zNinjaFrosTz** [comment]
cara, nao sei se é muito antigo nao em, pq ele é de 9°geração com uma velocidade de processamento boa, alem dele ter sido lançado em 2019, mas vou ver se consigo resolver sozin, talvez seja algo com o pc, mas vc falou de diminuir a alocação, quando diminuo, o modpack nem abre p-p

**Comment by ArtpokeBr** [comment]
Aloca exatamente 6GB e testa, o Java é meio doido então a melhor coisa é sempre acertar a quantia certa de RAM.

**Comment by zNinjaFrosTz** [comment]
art, muito obrigado, voce clareou minha vista, e livrou meu caminho, pra quem estiver com o mesmo problema tenta iniciar o game com a alocação no maximo da sua memoria, fecha o game e coloca uns 2gb abaixo do total, bjs art e bom dia
