### ISSUE TITLE
Lamp Middle (não é possível criar o item)

### ISSUE THREAD

**Issue by ErickPariseVitorassi** [ArtpokeBr/Minecraft-Ultimato#80]
O crafting do item **Lamp Middle** está em conflito com o **Iron Chain**, fazendo com que não seja possível cria-lo.

**Comment by ArtpokeBr** [comment]
Tem como fornecer uma print?

**Comment by ErickPariseVitorassi** [comment]
Claro, aqui:

![image](https://user-images.githubusercontent.com/29761991/101084343-98316680-358c-11eb-8a69-5ff049e952e3.png)

![image](https://user-images.githubusercontent.com/29761991/101084313-8a7be100-358c-11eb-8814-61efbc6c516b.png)

**Comment by ErickPariseVitorassi** [comment]
Claro, aqui:

![2020-12-03_18 26 56](https://user-images.githubusercontent.com/29761991/101084521-d890e480-358c-11eb-8a98-9725375d17d4.png)
![2020-12-03_18 27 03](https://user-images.githubusercontent.com/29761991/101084525-d9297b00-358c-11eb-88a7-2e9e446190a3.png)

**Comment by ArtpokeBr** [comment]
Ok, assim que for possível, estará no próximo patch.

**Comment by ErickPariseVitorassi** [comment]
Ok, obrigado!

**Comment by ErickPariseVitorassi** [comment]
Tem uma outra possível solução, colocar esse mod: [](https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict)
