### ISSUE TITLE
Tudo do mystical com Emc totalmente desbalanceado... 

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#84]
Preciso falar alguma coisa? kkkkkkk
![image](https://user-images.githubusercontent.com/54782518/101077437-99aa6100-3583-11eb-9fce-f94242167a4a.png)
![image](https://user-images.githubusercontent.com/54782518/101077457-a2029c00-3583-11eb-9466-6ffd624858b5.png)
![image](https://user-images.githubusercontent.com/54782518/101077483-a7f87d00-3583-11eb-89f0-223cc74e4139.png)
![image](https://user-images.githubusercontent.com/54782518/101077494-acbd3100-3583-11eb-94ea-9dd90d5f831e.png)

**Comment by ArtpokeBr** [comment]
Esse ProjectE é osso.

**Comment by Christtiann** [comment]
@ArtpokeBr removi todas os EMC, se quiser o arquivo :D chama disc
