### ISSUE TITLE
Saturacao do pam's harvest craft

### ISSUE THREAD

**Issue by ViniWagner** [ArtpokeBr/Minecraft-Ultimato#85]
me ensina a tirar esse porcaria de saturação

**Comment by ArtpokeBr** [comment]
Como assim? que saturação do Pam's? eu não coloquei restrição nenhuma no Modpack kkk

**Comment by ViniWagner** [comment]
Nao isso quero ajudar para tirar isso aqui uma carne de porco recuperar uma barrinha
![Screenshot_3](https://user-images.githubusercontent.com/75450983/101086019-0a0aaf80-358f-11eb-8e69-b91ba31524f2.png)

**Comment by ArtpokeBr** [comment]
isso é padrão do Pam's, pra balancear o fato de que existem 500 comidas no jogo... sinceramente, isso é presente em tanto Modpack que é até estranho não ser assim kkk então minha recomendação é só você fazer uma comida mais eficente ora bolas kkk por que não vou simplesmente tirar um Mod por causa disso. sem falar que se você simplesmente tirar o Pam's bugs irão surgir :)
