### ISSUE TITLE
o meu nem sai da tela do multi mc

### ISSUE THREAD

**Issue by Chumzera** [ArtpokeBr/Minecraft-Ultimato#86]
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/vitot/Desktop/JOGOS/MultiMC/instances/ULTIMATO/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Java versão 15.0.1, usando arquitetura de 64 bits.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/vitot/Desktop/JOGOS/MultiMC/instances/ULTIMATO/natives

Libraries:
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/vitot/Desktop/JOGOS/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] 0.0.5a-releasecandidate1
  [📁] 1.12 (folder)
  [✔️] ActuallyAdditions-1.12.2-r152
  [✔️] Advanced Solar Panels-4.3.0
  [✔️] AE2WTLib-1.12.2-1.0.34
  [✔️] aether-1.12.2-v1.5.2
  [✔️] AIImprovements-1.12-0.0.1b3
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] armoreablemobs-1.12.2-1.1.8
  [✔️] armoryexpansion-1.4.2
  [✔️] astralsorcery-1.12.2-1.10.27
  [✔️] AttributeFix-1.12.2-1.0.4
  [✔️] Atum-1.12.2-2.0.20
  [✔️] AutoRegLib-1.3-32
  [✔️] Avaritia-1.12.2-3.3.0.33-universal
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] baubley-heart-canisters-1.12.2-1.2.3
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] BetterFps-1.4.8
  [✔️] bewitchment-1.12.2-0.0.22.44
  [✔️] blockcraftery-1.12.2-1.3.1
  [✔️] BloodMagic-1.12.2-2.4.3-105
  [✔️] BNBGamingCore-1.12.2-0.12.0
  [✔️] BNBGamingLib-1.12.2-2.17.6
  [✔️] bonsaitrees-1.1.4-b170
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] bookworm-1.12.2-2.5.2.1
  [✔️] Born In A Barn V1.8-1.12-1.1
  [✔️] Botania r1.10-363
  [✔️] Bountiful Baubles-1.12.2-0.1.6
  [✔️] BrandonsCore-1.12.2-2.4.19.214-universal
  [✔️] BuildingGadgets-2.8.4
  [✔️] capabilityadapter-1.1.0
  [✔️] carryon-1.12.2-1.12.3.15
  [✔️] Cathedral-1.12.2-1.9.9
  [✔️] chickens-6.0.4
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] ColouredTooltips-1.12.2-1.0.7
  [✔️] compactmachines3-1.12.2-3.0.18-b278
  [✔️] conarm-1.12.2-1.2.5.9
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] CraftTweaker2-1.12-4.1.20.586
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] CustomBackgrounds-MC1.12-1.1.1
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] CustomStartingGear-1.12-1.2.0.9-universal
  [✔️] cyberware-1.12.2-0.2.11.26
  [✔️] DarknessLib-1.12.2-1.1.0
  [✔️] DarkUtils-1.12.2-1.8.230
  [✔️] DoggyTalents-1.12.2-1.15.1.6
  [✔️] Draconic-Evolution-1.12.2-2.3.27.353-universal
  [✔️] DragonMounts2-1.12.2-1.6.3
  [✔️] Earthworks-1.12-1.3.6
  [✔️] emoticons-0.6.1-1.12.2-dist
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15
  [✔️] EnderCore-1.12.2-0.5.76
  [✔️] EnderIO-1.12.2-5.2.60
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] EnderTweaker-1.12.2-1.2.0
  [✔️] environmentaltech-1.12.2-2.0.20.1
  [✔️] Erebus-1.0.31
  [✔️] etlunar-1.12.2-2.0.20.1
  [✔️] ExpandedEquivalence-1.12.2-12.3.16
  [✔️] ExtendedCrafting-1.12.2-1.5.6
  [✔️] ExtraCells-1.12.2-2.6.5
  [✔️] ExtraPlanets-1.12.2-0.7.0
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.67
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] fluxnetworks-1.12.2-4.0.15-32
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] ftb-ultimine-1202.3.5
  [✔️] furniture-6.3.1-1.12.2
  [✔️] GalacticraftCore-1.12.2-4.0.2.280
  [✔️] Galacticraft-Planets-1.12.2-4.0.2.280
  [✔️] Gravitation Suite-3.1.1
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] HammerLib-1.12.2-2.0.6.23
  [📁] hats (folder)
  [✔️] Hats-1.12.2-7.1.1
  [✔️] HuntingDimension-1.12.2-1.0.42
  [✔️] iceandfire-1.9.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] immersivetech-1.12-1.3.10
  [✔️] industrialcraft-2-2.8.170-ex112
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] inventorypets-1.12-2.0.6
  [✔️] jei_1.12.2-4.16.1.301
  [✔️] JurassiCraft-1.12.2-2.1.23
  [✔️] JustEnoughEnergistics-1.12.2-1.0.8
  [✔️] just-enough-harvestcraft-1.12.2-1.7.2
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] LagGoggles-1.12.2-5.8-132
  [✔️] landlust-1.12.2-0.3.6
  [✔️] lazy-ae2-1.12.2-1.1.24
  [✔️] lemonlib-1.12.2-1.3.0
  [✔️] libnine-1.12.2-1.2.0
  [✔️] llibrary-1.7.20-1.12.2
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] mclib-2.1.1-1.12.2
  [✔️] Mekanism-1.12.2-9.8.3.390
  [✔️] MekanismGenerators-1.12.2-9.8.3.390
  [✔️] MekanismTools-1.12.2-9.8.3.390
  [📁] memory_repo (folder)
  [✔️] MetalChests-v6.1.0+mc1.12.2
  [✔️] MicdoodleCore-1.12.2-4.0.2.280
  [✔️] MJRLegendsLib-1.12.2-1.2.0
  [✔️] MmmMmmMmmMmm-1.12-1.14
  [✔️] moartinkers-0.6.0
  [✔️] MobGrindingUtils-0.3.13
  [✔️] modnametooltip_1.12.2-1.10.1
  [✔️] modtweaker-4.0.18
  [✔️] morechickens-1.12.2-3.1.0
  [✔️] morelibs-1.12.2-1.2.2
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] moreplates-1.12.2-5.5.2
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mowziesmobs-1.5.8
  [✔️] MTLib-3.0.6
  [✔️] MutantBeasts-1.12.2-1.0.1
  [✔️] MysticalAgradditions-1.12.2-1.3.2
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] mysticallib-1.12.2-1.9.0
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] Netherending-Ores-1.12.2-1.4.2
  [✔️] NoMoreRecipeConflict-0.13(1.12.2)
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] notenoughwands-1.12-1.8.1
  [✔️] NuclearCraft-2.18y-1.12.2
  [✔️] obfuscate-0.4.2-1.12.2
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-22
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] QualityTools-1.0.7_for_1.12.2
  [✔️] Quark-r1.6-179
  [✔️] randompatches-1.12.2-1.22.1.7
  [✔️] RandomThings-MC1.12.2-4.2.7.4
  [✔️] randomtweaks-1.12.2-2.8.2.0
  [✔️] rats-3.2.14-1.12.2
  [✔️] RebornCore-1.12.2-3.19.4.529-universal
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal
  [✔️] refinedstorage-1.6.16
  [✔️] refinedstorageaddons-0.4.5
  [✔️] Reliquary-1.12.2-1.3.4.796
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftools-1.12-7.73
  [✔️] rftoolsdim-1.12-5.71
  [✔️] roost-1.12.2-2.0.10
  [✔️] rustic-1.1.7
  [✔️] Scannable-MC1.12.2-1.6.3.24
  [✔️] Schematica-1.12.2-1.8.0.169-universal
  [✔️] SimpleStorageNetwork-1.12.2-1.7.11
  [✔️] Simple-Void-World-1.12-1.2.0.9-universal
  [✔️] SimplyJetpacks2-1.12.2-2.2.16.1
  [✔️] SolarFluxReborn-1.12.2-12.4.11
  [✔️] statues-rechiseled-1.12.2-1.0.1
  [✔️] StevesCarts-1.12.2-2.4.32.137
  [✔️] TBone-v1.6.8+mc1.12.2
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] techguns-1.12.2-2.0.2.0_pre3.2
  [✔️] tesla-core-lib-1.12.2-1.0.17
  [✔️] TheBetweenlands-3.7.1-universal
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalCultivation-1.12.2-0.3.6.1-universal
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal
  [✔️] ThermalExpansion-1.12.2-5.5.7.1-universal
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal
  [✔️] TickCentral-3.1
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] tinyprogressions-1.12.2-3.3.34-Release
  [✔️] topaddons-1.12.2-1.13.0
  [✔️] Topography-1.12.2-1.14.4
  [✔️] torchmaster_1.12.2-1.8.4.84
  [✔️] TravelersBackpack-1.12.2-1.0.34
  [✔️] tropicraft-MC1.12.2-7.1.9.115
  [✔️] twilightforest-1.12.2-3.11.1021-universal
  [✔️] UniDict-1.12.2-2.9.8
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] VanillaFix-1.0.10-150
  [✔️] vehicle-mod-0.44.1-1.12.2
  [✔️] Voice Chat Reloaded-1.2.4
  [✔️] WanionLib-1.12.2-2.5
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] WirelessCraftingTerminal-1.12.2-3.12.97
  [✔️] worldedit-forge-mc1.12.2-6.1.10-dist
  [✔️] Xaeros_Minimap_20.27.3_Forge_1.12
  [✔️] XaerosWorldMap_1.11.1_Forge_1.12
  [✔️] yoyos_1.12.2-1.3.3.25
  [✔️] zawa-1.12.2-2.1.0
  [✔️] zerocore-1.12.2-0.1.2.8

Params:
  --username  --version MultiMC5 --gameDir C:/Users/vitot/Desktop/JOGOS/MultiMC/instances/ULTIMATO/minecraft --assetsDir C:/Users/vitot/Desktop/JOGOS/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4000m, -Xmx6000m, -Duser.language=en]

ID do processo do Minecraft: 8732

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
O processo foi encerrado com o código -1.
Clipboard copy at: 03 Dec 2020 17:42:35 -0300

**Comment by Chumzera** [comment]
to com 4 gb de ram minimo e maximo em 6 gb.

**Comment by ArtpokeBr** [comment]
Aumenta a RAM e tenha certeza de que a instalação foi feita corretamente. no MultiMC o mínimo geralmente é o mais importante, então sobe isso pra 5 ou 6 dependendo do seu PC.

**Comment by pgbezerra** [comment]
Você esta utilizando a versão 15 do Java, eu utilizo Linux e a versão que eu utilizo geralmente é a ultima LTS que é a 11 já que sou desenvolvedor, faça a alteração apontando para o Java 8 (1.8) instalado em sua maquina, caso n tenha aponte para a 1.8

![image](https://user-images.githubusercontent.com/22059237/101259082-67287180-3705-11eb-8ff4-5860d09c11d7.png)
