### ISSUE TITLE
quando eu tento iniciar ou criar um mundo plano no modpack ele fala que deu erro ao criar o mundo e o mod responsavel pelo erro e o topography

### ISSUE THREAD

**Issue by gtavmatagui** [ArtpokeBr/Minecraft-Ultimato#88]
quando eu tento iniciar ou criar um mundo plano no modpack ele fala que deu erro ao criar o mundo e o mod responsavel pelo erro e o topography

**Comment by gtavmatagui** [comment]
o kacerte escrevi errado e o mod topographc

**Comment by ArtpokeBr** [comment]
ele da um crash? é isso? me manda o Crash report mais recente. pode ser encontrado numa pasta dentro do diretório do jogo literalmente chamada crash reports, então pega a que for mais recente.

**Comment by gtavmatagui** [comment]
Mano agr ele tá indo de boas mas ele só dava um erro na tela não crashava
nem nada ele só dava um erro que ficava na tela de terra com as mensagens
dizendo que tinha dado erro mas agora ele tá de boas n deu mais esse erro e
eu n mechi nada no modpack pra voltar,mas mano tirando do assunto como vc
faz esses modpacks vc poderia fazer um vídeo né kkkk

Em qua, 16 de dez de 2020 17:13, ArtpokeBr <notifications@github.com>
escreveu:
