### ISSUE TITLE
Jogo congelando após 30 minutos ou mais de gameplay.

### ISSUE THREAD

**Issue by zMigueel** [ArtpokeBr/Minecraft-Ultimato#89]
Os crashes que havia tendo antes foram corrigidos (como não sei), mas agora estou tendo diversos problemas do jogo congelar e não voltar. Não tenho ideia do que fazer, estou alocando 6 de ram e ainda não tive melhora.

**Comment by ArtpokeBr** [comment]
devem ser problema de carregar os Chunks, isso vai estar num próximo patch, mas tenta ir nas configs do Zawa, tem uma chamada Spawn configurations, vai dar trabalho, mas nela tu pode desativar TODOS os spawns dos bixos do Zawa, isso pode ser uma alternativa.

**Comment by ArtpokeBr** [comment]
[ZAWASpawnConfigurations.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5640295/ZAWASpawnConfigurations.zip)
na real, toma aqui, substitui pela que está no seu jogo e vê se ajuda.
