### ISSUE TITLE
Dimensão de dragões não geradas...

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#9]
Se vc joga sozinho a dimensão é criada... 
Se colocar no server não é criado...
![image](https://user-images.githubusercontent.com/54782518/100295122-9271ca80-2f67-11eb-9e30-e1b010424ef4.png)

https://youtu.be/jyQZkZXD9M0

**Comment by Christtiann** [comment]
Passando um mundo para o multiplayer ele nao gera os chunks corretamente...
![image](https://user-images.githubusercontent.com/54782518/100296703-b0d9c500-2f6b-11eb-9a49-0ad052d5e245.png)

**Comment by Christtiann** [comment]
![Uploading image.png…]()

**Comment by ArtpokeBr** [comment]
no singleplayer, basta ter a geração de mundo do topography selecionada pois assim deveria funcionar viu

**Comment by Christtiann** [comment]
@ArtpokeBr mesmo pegando la no singleplayer e colocando no server nao funciona...
