### ISSUE TITLE
Duplicação de dragon forge core

### ISSUE THREAD

**Issue by YuriRibeir0** [ArtpokeBr/Minecraft-Ultimato#90]
Ao quebrar um dragon forge core usando o loot pet do inventory pets é possível duplicar o bloco, algo que normalmente só seria possível com minérios e drops de mobs.

**Comment by ArtpokeBr** [comment]
Tem como mandar uma print mostrando o bloco ou item? na real o melhor seria se pudesse fazer um vid pra me mostrar. ficar melhor pra ver sem eu ter que abrir o Pack.

**Comment by YuriRibeir0** [comment]
[https://www.youtube.com/watch?v=fKkGKuP7um0&feature=youtu.be](url)
Demorei um pouco para responder por que tive que upar o vídeo, o github não suportava mp4, qualquer coisa é só pedir

**Comment by ArtpokeBr** [comment]
Ah kkk, bom trabalho, deixou bem claro o Ocorrido. esses InventoryPets só dão BO mas vou trabalhar nisso assim que for possível.
