### ISSUE TITLE
Problema com texturas no modpack

### ISSUE THREAD

**Issue by Luiz82** [ArtpokeBr/Minecraft-Ultimato#91]
Coloquei uma textura no minecraft ultimato chamada stevens 64x64 para 1.12.2, e quando cliquei em Done, não quis voltar para a tela inicial do modpack ou aparecer a tela da mojang de carregamento, apenas ficou ali. Não imagino que foi travamento do computador, coloquei 4GB de ram para o modpack funcionar. Também já usei essa textura em outros modpacks 1.12.2 e sempre funcionou certinho. Abrindo google e outros apliacativos quando eu estava tendo o problema não teve travamento

**Comment by ArtpokeBr** [comment]
na 1.12 quando tu coloca uma texture, o jogo recarrega TODOS os assets do jogo, então pode ser que por conta do Modpack ser pesado ele puxe muito mais do que 4GB na hora de carregar isso, se seu PC aguentar, tente aumentar a RAM um pouco e ir testando. no geral não é algo que eu possa muito corrigir então se aumentar a RAM e mesmo assim não ir, infelizmente n será possível usar essa textura =/ vou fechar
