### ISSUE TITLE
Modpack não roda mais

### ISSUE THREAD

**Issue by NumSeiQueNadaSei** [ArtpokeBr/Minecraft-Ultimato#92]
O jogo rodava liso mas agr n da nem nenhum passo a mais que trava tudo e eu nem tinha farme ainda pra trava o jogo
n sei oque ta acontecendo mas parece algum mod pra gera mundo que tá travando e trava tudo dps

**Comment by ArtpokeBr** [comment]
[ZAWASpawnConfigurations.zip](https://github.com/ArtpokeBr/Minecraft-Ultimato/files/5640308/ZAWASpawnConfigurations.zip)
Esse arquivo vai desabilitar o spawn das criaturas do Zawa, tente substituir pelo arquivo de configuração já existente dentro da pasta do Zawa localizada nas configs. se n funcionar, n sei oq fazer =/

**Comment by NumSeiQueNadaSei** [comment]
Obrigado deu certo algumas partes do mapa deu bug e tava nascendo um monte de bicho lá vlw desculpa pelo incômodo

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
