### ISSUE TITLE
Cabeças não dropam apos colocar no chão 

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#93]
É isso.
https://youtu.be/qnmX5WN2Omc

**Comment by ArtpokeBr** [comment]
será que isso tem relação com gente que já reportou que as vezes as coisas não dropam? não sei o por que disso, e nem sei se tem algum Mod no Modpack que manipula diretamente os Drops de itens =/ uma pesquisa é necessária.
