### ISSUE TITLE
Tem alguma forma de fazer o modpack rodar com menos memoria? 

### ISSUE THREAD

**Issue by OOrox** [ArtpokeBr/Minecraft-Ultimato#94]
Tenho so 4 gb de ram a placa de video e cpu são bons mesmo que tenha que tirar algum mod.

**Comment by ArtpokeBr** [comment]
se você tem apenas 4GB de RAM Disponível no PC inteiro não há oq fazer.. o mine em si é muito mais baseado na memória do que em outros componentes no PC então infelizmente não posso fazer nada relacionado ao seu problema =/ eu aconselharia comprar um pente novo de memória. vou fechar.
