### ISSUE TITLE
Sugestão de MOD para aumentar/otimizar o TPS dos servidores em geral.

### ISSUE THREAD

**Issue by JCraftplay** [ArtpokeBr/Minecraft-Ultimato#95]
Seguindo com o título, o modpack mostra-se bastante otimizado em termos locais, especialmente o singleplayer. Porém, observei por meio de análises que ele não consegue se manter estável em servidores. Isto deve estar ligado às “ForgeEntities” e por isso venho aqui sugerir um mod que busca solucionar esta situação!

O nome do mod: Tick Dynamic (https://www.curseforge.com/minecraft/mc-mods/tick-dynamic)

Espero ter ajudado, qualquer coisa estou a disposição.

**Comment by ArtpokeBr** [comment]
Não sou eu que diretamente cuido do Servidor kkk, mas de fato, optimizar as coisas pra server é complicado. obrigado pela sugestão :)

**Comment by Christtiann** [comment]
Infelizmente esse mod nao ajuda... Experiencia propria kkk
