### ISSUE TITLE
Tem mods faltando

### ISSUE THREAD

**Issue by annec2019** [ArtpokeBr/Minecraft-Ultimato#96]
eu já reinstalei varias vezes mas ta atualizado na versão 1.0.2 que e a ultima mas oque eu e que ta sem o mod da seta que serve pra quando tem dois crafts iguais n sei o nome mas ta me atrapalhando a fazer o material stonework pq a maquina que faz borracha
precisa de uma engrenagem de  ferro e o anel do aether e igual o craft da  engrenagem do industrial foregoing
![2020-12-04_11 46 12](https://user-images.githubusercontent.com/75489897/101180658-9e762000-362a-11eb-9068-e92c77ab294f.png)

**Comment by annec2019** [comment]
desculpa a escrita

**Comment by ArtpokeBr** [comment]
a versão atual que está disponível na Curse, a 1.0.2, está "desatualizada" em relação aos participantes! eles estão já com a 1.0.3 eu infelizmente não consigo atualizar ainda na Curse pois a plataforma ainda está se estabilizando pós terem migrado de launcher e afins. mas encontrando esse tipo de problema de receita, Me reporte mesmo! esse do Anel de ferro em questão eu já até corrigi na verdade :) se encontrar outros é só avisar! vou fechar o Issue pra n ficar confuso.
