### ISSUE TITLE
Vários recipes em conflito

### ISSUE THREAD

**Issue by desconection** [ArtpokeBr/Minecraft-Ultimato#97]
Vários craftings do modpack tem confilito entre mods, assim sendo impossível craftar certas coisas, recomendaria o uso desse mod
https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict

**Comment by ArtpokeBr** [comment]
os Participantes estão já com uma versão mais recente que possui instalado o Mod, mas na verdade o melhor seria me reportar justamente as receitas em conflito, visto que já resolvi algumas :) então obrigado pela sugestão mas por favor, reporte-me conflitos que encontrar.

**Comment by desconection** [comment]
> os Participantes estão já com uma versão mais recente que possui instalado o Mod, mas na verdade o melhor seria me reportar justamente as receitas em conflito, visto que já resolvi algumas :) então obrigado pela sugestão mas por favor, reporte-me conflitos que encontrar.

Quando vai disponibilizar essa versão mais recente para  o publico?

**Comment by ArtpokeBr** [comment]
Assim que a CurseForge liberar :)
