### ISSUE TITLE
Recomendação

### ISSUE THREAD

**Issue by desconection** [ArtpokeBr/Minecraft-Ultimato#98]
Seria possível inserir esse mod https://www.curseforge.com/minecraft/mc-mods/item-blacklist
esse mod ajudaria a quem quer fazer algum tipo de servidor do mc ultimato, já que tem items que literalmente quebram o servidor.

**Comment by ArtpokeBr** [comment]
Os atuais donos de server já dão conta de desativar os itens então acredito eu que por mais que a sugestão seja boa, não é necessária :)
