### ISSUE TITLE
Bug Com mod RFTOOLS DIMENSION'

### ISSUE THREAD

**Issue by karutoplays** [ArtpokeBr/Minecraft-Ultimato#99]
Boa Tarde Jovens.. estava eu jogando com o modpack Ultimato.. testando algumas dimençoes no mod RFTOOls.. quando do nada.. me trava todo o mod.. mostrando a mensagem que aparece nas imagens que mandei.. so inesperiente nesse mod .. mas se aconteceu cmg pode acontecer com os participantes tbm.. 
![2020-12-04_14 52 01](https://user-images.githubusercontent.com/75497419/101197583-12232780-3641-11eb-8b82-6b6f8320e1cf.png)
![2020-12-04_14 52 13](https://user-images.githubusercontent.com/75497419/101197588-14858180-3641-11eb-81fc-b318a21335dd.png)
![2020-12-04_14 52 22](https://user-images.githubusercontent.com/75497419/101197594-164f4500-3641-11eb-910c-ae76bb0b012a.png)

**Comment by ArtpokeBr** [comment]
Isso é lag de server, tu criou quantas dimensões? e além do mais, pra que tantos FluxPoints? isso também pode ser sido o Motivo! ao mexer com o Rftools Dimensions tu corre esse risco pq se tá literalmente criando dimensões!

**Comment by ArtpokeBr** [comment]
vou fechar.
